### ISSUE TITLE
Detect misuse of except

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#139]
*Original report by [mithrandi](https://launchpad.net/~mithrandi) (@mithrandi?) on [Launchpad](https://bugs.launchpad.net/bugs/848455):*

------------------------------------

It would be nice if pyflakes could detect mistakes like this:

       try:
           oldtime = os.path.getmtime(fname)
       except OSError, IOError:
           oldtime = 0

In the general case, it's obviously difficult to tell whether this is an error or not; but I suspect that handling the exception variable name as a binding would give you a "redefinition of Foo" warning in most of the cases where a mistake has been made.

**Comment by asottile** [comment]
closing given pyflakes has dropped python 2 support
