### ISSUE TITLE
Warn about string exceptions

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#141]
*Original report by [mithrandi](https://launchpad.net/~mithrandi) (@mithrandi?) on [Launchpad](https://bugs.launchpad.net/bugs/848470):*

------------------------------------

These can take several forms:

   raise "shouldn't happen"
   raise 'Cannot determine type of callable: '+repr(callableObject)
   raise "Can't read input parameters file : %s" % options.input_file

Some of these will be harder to detect than others.

**Comment by asottile** [comment]
Should we close this as pyflakes no longer supports python2.5?

**Comment by bitglue** [comment]
yep.
