### ISSUE TITLE
Incorrect line numbers for decorated functions

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#144]
*Original report by [yatc18ks0-9a-ngeefk4xa](https://launchpad.net/~yatc18ks0-9a-ngeefk4xa) on [Launchpad](https://bugs.launchpad.net/bugs/879945):*

------------------------------------

In the code:

```python
def decorator(func):
    return func


@decorator
def defined_twice():
    pass


@decorator
def defined_twice():
    pass
```

Pyflakes gives the error: twice.py:10: redefinition of function 'defined_twice' from line 5

It ought to be: twice.py:11: redefinition of function 'defined_twice' from line 6

**Comment by asottile** [comment]
This will be fixed by python3.8 (which adjusts the line position of decorated function nodes):

```console
$ python3.8 -m pyflakes t.py
t.py:11:1 redefinition of unused 'defined_twice' from line 6
```

**Comment by pradyunsg** [comment]
Any chance of back porting or is this an issue with the parse tree that we're getting?

**Comment by asottile** [comment]
this is the parse tree we're handed from cpython -- we don't really have any control over the ast module

**Comment by asottile** [comment]
the suggestion above about `len(node.decorator_list)` doesn't work as well due to things like:

```python
@foo(
    ...,
)
def f(): pass
```

**Comment by asottile** [comment]
closing this since it'll magically fix itself in py38 and there isn't really anything we can do for this in older versions
