### ISSUE TITLE
Detect broken string templates that will raise ValueError when interpolated

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#148]
*Original report by [jkakar](https://launchpad.net/~jkakar) (@jkakar?) on [Launchpad](https://bugs.launchpad.net/bugs/950369):*

------------------------------------

For example, code like this will break:

  >>> "%(foo)" % {"foo": "bar"}
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ValueError: incomplete format

It'd be awesome if Pyflakes told me about that kind of issue.

**Comment by peterjc** [comment]
I logged https://gitlab.com/pycqa/flake8/issues/513 (out of scope, should be in pyflakes or pycodestyle) for a closely related example -consider this test case, saved as `str_fmt.py`:

```python
"""String formatting test case.

The percent j should be percent i for integer.
"""

a = 123
b = "Hello"
c = "World"

print("%j\t%s\t%s\n" % (a, b, c))
```

Currently flake8 does not report any problem with this file:

```
$ flake8 str_fmt.py ; echo "Return code $?"
Return code 0
```

However, on running it:

```
$ python str_fmt.py
Traceback (most recent call last):
  File "str_fmt.py", line 10, in <module>
    print("%j\t%s\t%s\n" % (a, b, c))
ValueError: unsupported format character 'j' (0x6a) at index 1
```

Static code analysis could spot this kind of error and prevent `ValueError: unsupported format character` exceptions, and also ``ValueError: incomplete format`` as in this issue. In my experience these kinds of error are particularly common in corner cases for error handling or logging code which is not exhaustively tested.

This is analogous to the flake8 warning akin to `W605 invalid escape sequence` (although that does not usually trigger an exception), but for invalid percent placeholders.

**Comment by asottile** [comment]
Took a stab at this (and more) in #443

**Comment by peterjc** [comment]
Looking forward to using this - thank you all.

The new checks seem worth mentioning in the ``NEWS.rst`` file, does that happen as part of the release process?
