### ISSUE TITLE
Please also check python scripts that are not named *.py

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#149]
*Original report by [morph-debian](https://launchpad.net/~morph-debian) on [Launchpad](https://bugs.launchpad.net/bugs/970465):*

------------------------------------

Hello,
as reported on Debian at http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=653890:

"""
It would be great if pyflakes could detect files that are python scripts
but are not named *.py. It would have to read the first two bytes of
each file to check for scripts and then read the rest of the line to
determine if it is a python script. It would need to process stuff like:

#!/usr/bin/python
#!/usr/local/bin/python
#!/usr/bin/env python
#!/usr/bin/python2.6
#!/usr/bin/python3.2
"""

Regards,
Sandro

**Comment by myint** [comment]
@sandrotosi This is fixed in `master` now.

From years ago:

https://bugs.launchpad.net/pyflakes/+bug/970465
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=653890.

**Comment by asmeurer** [comment]
Can you include pythonw in the regex https://docs.python.org/3/using/mac.html?highlight=pythonw#running-scripts-with-a-gui
