### ISSUE TITLE
allow to specify checker mixins

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#154]
*Original report by [ronny-pfannschmidt-deactivatedaccount](https://launchpad.net/~ronny-pfannschmidt-deactivatedaccount) on [Launchpad](https://bugs.launchpad.net/bugs/1114708):*

------------------------------------

this would allow to do propper support for framework specific extra checks/bindings outside of pyflakes

for example, instead of the execnet support, i could pass in a mixin that overrides the check
or instead of the ErrorReturn check, that could also be a mixin

same goes for supporting `__tracebackhide__`

**Comment by asottile** [comment]
A flake8 plugin probably makes the most sense here and not to grow a plugin framework inside of pyflakes
