### ISSUE TITLE
"import as" can cause spurious "imported but unused" warnings

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#159]
*Original report by [bcs26](https://launchpad.net/~bcs26) on [Launchpad](https://bugs.launchpad.net/bugs/1162031):*

------------------------------------

Pyflakes will generate a spurious "imported but unused" warning for the following code:

import selenium as se
import selenium.webdriver

se.webdriver.Firefox("foo")

Note that Pyflakes will, correctly, *not* generate such a warning for the following:

import selenium
import selenium.webdriver

se = selenium

se.webdriver.Firefox("foo")

**Comment by asottile** [comment]
the second import is purely for side-effects -- I believe pyflakes is correct to flag this as a programming error/smell
