### ISSUE TITLE
Don't report unused imports in __init__.py

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#162]
*Original report by [asmeurer](https://launchpad.net/~asmeurer) (@asmeurer?) on [Launchpad](https://bugs.launchpad.net/bugs/1178905):*

------------------------------------

`__init__.py` files are full of unused import warnings, because all they are are imports. But this is one instance where it is correct to import something and not "use" it.

**Comment by vbrozik** [comment]
I think that in case `__init__.py` contains only imports an no other commands, pyflakes should not complain.

**Comment by asottile** [comment]
use `__all__` to indicate the exported members and pyflakes will not complain
