### ISSUE TITLE
"Dead code" after a return

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#170]
*Original report by [asmeurer](https://launchpad.net/~asmeurer) (@asmeurer?) on [Launchpad](https://bugs.launchpad.net/bugs/1274566):*

------------------------------------

Is there a reason pyflakes doesn't warn on "dead code", i.e., code that cannot possibly be run because it comes after a return or a raise in the same block, like

```python
def f():
    return
    g() # cannot be reached
```

I think return, raise, break, and continue are all such statements.  

In a similar vein (should this be a separate issue?), what about unnecessary pass, like

```python
if x:
    pass
    f()
```

Inline non-string literals or bare variable names might also fit into this category, although the latter can be a useful way to squash incorrect "unused variable" warnings.

**Comment by asottile** [comment]
collecting duplicates for "pyflakes doesn't do branch analysis" here: #715

**Comment by asottile** [comment]
@asmeurer you'd need to know which branches lead to early exit to know that the code afterwards is dead.  there could be a simpler version which just sees `return x; y` as y being dead -- but it would be a false security of actually catching dead code

**Comment by asmeurer** [comment]
You can detect dead code without using branch analysis by checking for code after `return` within the same block, like in the initial example. Things like 

```
if x:
   return ...
else:
   return ...
dead_code()
```

are also quite easy to detect (note that the value of `x` is completely irrelevant here).

> but it would be a false security of actually catching dead code

All pyflakes features are limited in what they can do to what simplistic static analysis can detect. I've never heard "false security" as an argument for it not doing something before. That could be applied to everything pyflakes does. If you're worried that the phrase "dead code" would make people think pyflakes does branch analysis we can avoid it and instead use error messages like "code after 'return' statement cannot be run".

**Comment by asottile** [comment]
as soon as you implement some of it, people will want all of it -- if we're going to do it at all we should do it right instead of half doing it
