### ISSUE TITLE
Warn about defining a loop variable that steps on an outer variable.

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#178]
*Original report by [wsanchez](https://launchpad.net/~wsanchez) (@wsanchez?) on [Launchpad](https://bugs.launchpad.net/bugs/1408774):*

------------------------------------

This code may be worth a warning:

```python
foo = 1

for foo in (2,3,4):
    pass
```

It's easy to accidentally step on a variable in a for loop, where usually one only uses the loop variable within the loop.

**Comment by asottile** [comment]
collecting duplicates for "pyflakes doesn't do branch analysis" here: #715
