### ISSUE TITLE
package imports → undefined name

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#198]
*Original report by [spaceone](https://launchpad.net/~spaceone) (@spaceone?) on [Launchpad](https://bugs.launchpad.net/bugs/1270169):*

------------------------------------

```
import foo.bar.baz
baz.blah()

foo/bar/__init__.py:1: 'foo' imported but unused
foo/bar/__init__.py:2: undefined name 'baz'
```

**Comment by asottile** [comment]
pyflakes doesn't perform any dynamic analysis so it can't know what module path an `__init__.py` should be (and then understand that the import has the side-effect of introducing the submodule name) -- I would suggest explicitly importing the module as above (either `from . import baz` or `from foo.bar import baz`)
