### ISSUE TITLE
shadowed variables not noticed after list comprehension

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#209]
*Original report by [warner](https://launchpad.net/~warner) (@warner?) on [Launchpad](https://bugs.launchpad.net/bugs/1373143):*

------------------------------------

With pyflakes-0.8.1 and python-2.7.8, the following test program gets the expected complaint:

```python
import foo
foo()
def bar():
    a = 0
    #a = [1 for foo in []]
    for foo in []:
        pass
    del a
```

pyflakes t.py
t.py:6: import 'foo' from line 1 shadowed by loop variable

But if you uncomment the list comprehension, the pyflakes complaints go away.

I think the presence of the list comprehension should actually *increase* the number of complaints: "foo" is being shadowed in both the list comprehension and the for-loop.

**Comment by asottile** [comment]
closing given pyflakes no longer supports python 2
