### ISSUE TITLE
On Python 3, __class__ can be used without self

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#223]
*Original report by [icordasc](https://launchpad.net/~icordasc) (@sigmavirus24?) on [Launchpad](https://bugs.launchpad.net/bugs/1487725):*

------------------------------------

On Python 3, the following code raises a warning:

```python
class Test(object):
    def __init__(self):
        print(__class__.__name__)
        self.x = 1

t = Test()
```

This is actually valid Python 3 code, but PyFlakes doesn't quite understand that:

    test.py:3: undefined name '__class__'

**Comment by zertosh** [comment]
Sorry for the silly question, but I'm having trouble following how pyflakes releases are done. I don't see the commit that fixes this issue (83ab002d6fab2b717df91e854624c6fdfd9b9213) on master or any other branch in the repo. Is there another staging area for releases?

**Comment by myint** [comment]
I think I might have quickly attempted a fix in a branch, but decided to delete the branch after not liking my solution. I don't remember what was wrong with solution anymore. 😄

**Comment by zertosh** [comment]
Heh thank you gh for keeping track of the commit! Any chance of this issue getting a fix then?

**Comment by myint** [comment]
See #325. Let's see if any one finds any flaws with it since I can't remember.
