### ISSUE TITLE
Highlighting decorators AND function declaration

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#224]
*Original report by [pradyunsg](https://launchpad.net/~pradyunsg) (@pradyunsg?) on [Launchpad](https://bugs.launchpad.net/bugs/1489540):*

------------------------------------

I'm proposing marking ALL decorators AND function declaration on decorated duplicate declaration.

See https://github.com/DamnWidget/anaconda/issues/363 for context.

**Comment by asottile** [comment]
duplicate of #144
