### ISSUE TITLE
Detect duplicate keys in dictionary literals

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#241]
*Original report by [icordasc](https://launchpad.net/~icordasc) (@sigmavirus24?) on [Launchpad](https://bugs.launchpad.net/bugs/1530909):*

------------------------------------

It would be great if PyFlakes could catch users specifying duplicate keys in dictionary literals, e.g.,

    d = {
        'a': 1,
        'b': 2,
        'a': 3,
    }

That second 'a' would be useful to be warned about.

**Comment by jayvdb** [comment]
This was added in https://github.com/PyCQA/pyflakes/pull/72
