### ISSUE TITLE
Reject python2 print syntax in python 3

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#242]
*Original report by [jpinon](https://launchpad.net/~jpinon) on [Launchpad](https://bugs.launchpad.net/bugs/1541912):*

------------------------------------

Using pyflakes 8.1 on this code does not raise error :

import sys
print >>sys.stderr, "Hello"

Launched with :

python3 -m pyflakes hello.py

**Comment by MacBox7** [comment]
@jayvdb  Would like to work on it. Could be easily done if pyflakes is installed with python2 since then the ast will contain `print` node which is not a case with python3 ast. Since here print is represented as a function and can be identified inside the `Name` node.
