### ISSUE TITLE
unused constants

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#243]
*Original report by [jayvdb](https://launchpad.net/~jayvdb) (@jayvdb?) on [Launchpad](https://bugs.launchpad.net/bugs/1543246):*

------------------------------------

Python 3.6 now has a SyntaxWarning for unused constants.

http://bugs.python.org/issue26204

Pyflakes could implement the same for Python 3.5 and lower.

**Comment by myint** [comment]
It looks like this may have been eventually removed:

https://github.com/python/cpython/commit/15a3095d64e96d0fe7448270f2c5b0bf22f9c4e1

I only read a few of the mailing list posts, but here is a relevant one:

https://mail.python.org/pipermail/python-dev/2016-February/143181.html

**Comment by bitglue** [comment]
Also this would seem to violate the "don't fail on things that aren't errors per se" design principle.
