### ISSUE TITLE
undefined name 'unicode' in "wrong" sys.version_info branch

### ISSUE THREAD

**Issue by pyflakes-bot** [PyCQA/pyflakes#246]
*Original report by [cboltz](https://launchpad.net/~cboltz) (@cboltz?) on [Launchpad](https://bugs.launchpad.net/bugs/1585991):*

------------------------------------

pyflakes makes it hard to check code that works on python 2 and 3 because some names are only defined in one version.

For example, take this little module:

```python
import sys

def type_is_str(var):
    ''' returns True if the given variable is a str (or unicode string when using python 2)'''
    if type(var) == str:
        return True
    elif sys.version_info[0] < 3 and type(var) == unicode:  # python 2 also uses the 'unicode' type
        return True
    else:
        return False
```

pyflakes3 errors out with
    undefined name 'unicode'
while pyflakes2 validates this code successfully (because unicode is a valid name in py2).

Can you make pyflakes a bit more intelligent so that it skips branches for the "wrong" version? Or, if that is too hard, add a way to skip a line marked with a special comment like
    # PYFLAKES:IGNORE
?

(The py3 testing was done with python3-pyflakes-1.2.3.)

**Comment by myint** [comment]
It does seem unfortunate that `pyflakes` doesn't run cleanly on its own codebase. I run into this every time I edit `pyflakes/checker.py`.

```
$ pyflakes .
./pyflakes/checker.py:40: undefined name 'unicode'
```

I would at least like to work around this in the `pyflakes` codebase, using something like what @jayvdb suggested in https://github.com/PyCQA/pyflakes/issues/246#issuecomment-304516087.

**Comment by sigmavirus24** [comment]
@myint you mean having pyflakes now look for configuration files? If you're going to go that direction, can I suggest enforcing project-local only configuration files? Don't allow folks to specify things globally on a user-level or system-level scale. You will get requests for that and those features are nightmarish (not to implement but to maintain and debug).

I'm not sold on having environment-level configuration stuck in a random file, personally, but I also haven't thought very much about this.

**Comment by myint** [comment]
@sigmavirus24 Nope, not configuration files. Just make `pyflakes` happy about `checker.py` by adding the following to `checker.py`:

```python
if PY3:
    unicode = str
```

```
diff --git a/pyflakes/checker.py b/pyflakes/checker.py
index 75abdc0..4f85d5d 100644
--- a/pyflakes/checker.py
+++ b/pyflakes/checker.py
@@ -39,6 +39,7 @@ if PY2:
         # workaround str.upper() which is locale-dependent
         return str(unicode(node_class.__name__).upper())
 else:
+    unicode = str
     def getNodeType(node_class):
         return node_class.__name__.upper()
```

**Comment by bitglue** [comment]
Another solution is to just pretend `unicode` is defined in python3, even if it isn't.

**Comment by sigmavirus24** [comment]
So Flake8 added a `--builtins` (or something, I'm jetlagged and sleep deprived) option that we allow people to use to specify extra "builtin" names to PyFlakes. Given that's possible with PyFlakes python api, maybe it should be supported on the CLI?

**Comment by bitglue** [comment]
Design philosophy so far has been to avoid any configuration. If this issue is bothering enough people, I'm more inclined to make the default behavior ignore an undefined `unicode` in python3.

**Comment by asmeurer** [comment]
That seems like it would mask more bugs than false positives. When I take some code that was written for Python 2, pyflakes is a useful tool for seeing which parts won't work in Python 3 (at least as a first pass). 

`if PY3: unicode = str` silences the error, and guards against faulty version checking logic.

**Comment by Kagami** [comment]
Encountered same issue with the code that supports both py2 and py3.

In my opinion best fix is `# noqa: F821`. Emulating py2 objects in py3 might result in nasty bugs.

**Comment by zeroincombenze** [comment]
I met same error using flake8 3.6.0.
Returned to 3.5.0 e 3.4.1 and it works!
