### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by myint** [PyCQA/pyflakes#271]
*I'm moving https://github.com/PyCQA/pyflakes/pull/90#issuecomment-301317699 here since we have GitHub issue support now.*

It looks like the [CPython 3.7 failure](https://travis-ci.org/PyCQA/pyflakes/jobs/231571260) is related to a change in the AST. The docstring is no longer in `node.body`.

https://github.com/python/cpython/pull/46

We can mostly replace our `getDocstring(node.body[0])` call with `node.docstring`. But I'm not sure how to get the line number of the docstring anymore. `node.lineno` is close, but not quite the line number of the docstring.

https://github.com/PyCQA/pyflakes/blob/074c21da3174bc88b2ec02fea767a436e2db643d/pyflakes/checker.py#L873

```diff
diff --git a/pyflakes/checker.py b/pyflakes/checker.py
index 382574e..2c19533 100644
--- a/pyflakes/checker.py
+++ b/pyflakes/checker.py
@@ -870,7 +870,11 @@ class Checker(object):

     def handleDoctests(self, node):
         try:
-            (docstring, node_lineno) = self.getDocstring(node.body[0])
+            if hasattr(node, 'docstring'):
+                docstring = node.docstring
+                node_lineno = ???  # TODO
+            else:
+                (docstring, node_lineno) = self.getDocstring(node.body[0])
             examples = docstring and self._getDoctestExamples(docstring)
         except (ValueError, IndexError):
             # e.g. line 6 of the docstring for <string> has inconsistent
```

I've reported this to the [CPython issue tracker](http://bugs.python.org/issue30497).

**Comment by myint** [comment]
I got some [responses](https://bugs.python.org/issue30497) from the Python bug tracker. They confirm my suspicion that there is no longer an easy way to get the line number of a docstring.

The doctest checking feature has been disabled by default since 5207ca66fe2b61d88d28885ab58d18414981c60a. I'm not sure if I've even used this feature before. My main interest was just to get the unit tests passing in Python 3.7.

I think @jayvdb has worked with the doctest parsing code the most recently out of all of us. And I think @mgedmin contributed the doctest checking feature in 5e962f0449491afd765ad3f9e3e42bcc64ab77dc. What do you guys think would be the appropriate approach to this problem?

**Comment by mgedmin** [comment]
I'm fine with the simplifying assumption that a docstring starts on the next line after the function definition.  Incorrect line numbers in warnings are better than a completely broken feature.

At some point somebody will be sufficiently annoyed that they'll contribute a fix to make the line numbers correct, even if they do so by inspecting the source file to find the first `"""` after the `def`.

**Comment by myint** [comment]
So here is the option we are discussing in code:

https://github.com/PyCQA/pyflakes/compare/python37

**Comment by mgedmin** [comment]
That looks acceptable to me.
