### ISSUE TITLE
Incorrect F401/F822 results when `__all__` is defined from concatenated lists

### ISSUE THREAD

**Issue by edmorley** [PyCQA/pyflakes#276]
Using Python 2.7.13 & pyflakes 1.5.0, and this testcase (extracted from [this file from isort](https://github.com/timothycrosley/isort/blob/0aca83884667f1b20605e3bbef48bacf4f8b77fa/isort/pie_slice.py)):
```python
import sys

PY2 = sys.version_info[0] == 2
PY3 = sys.version_info[0] == 3

common_exports = ['PY2', 'PY3', 'this_does_not_exist']

if PY2:
    from itertools import ifilter as filter
    __all__ = common_exports + ['filter', 'this_does_not_exist_either']
else:
    __all__ = common_exports
```

**Expected:**
* `F822 undefined name 'this_does_not_exist' in __all__`
* `F822 undefined name 'this_does_not_exist_either' in __all__`

**Actual:**
* No F822 errors displayed (when there should be two).
* A false positive `F401 'itertools.ifilter as filter' imported but unused`.

It appears that flake8 ignores the `__all__` export entirely if it is defined from concatenated lists. ie:
```python 
__all__ = [] + ['this_will_be_ignored']

__all__ = ['so_will_this'] + []
```

**Comment by bitglue** [comment]
How could pyflakes correctly handle this case without being a Python interpreter?

**Comment by edmorley** [comment]
> How could pyflakes correctly handle this case without being a Python interpreter?

For the specific testcase above (which I should have reduced a bit further) I agree it's a bit dubious.

However this reduced testcase demonstrates the issue too, and doesn't require pyflakes to be a Python interpreter:

pyflakes correctly reports the F822 in this:
```python
FOO = 'bar'

__all__ = ['FOO']
__all__ += ['this_does_not_exist']
```
(thanks to https://github.com/PyCQA/pyflakes/commit/f4c674a3a6e80c902147b5bb61ceb176dde0fd4a)

...however incorrectly doesn't find any errors in:
```python
FOO = 'bar'

__all__ = ['FOO'] + ['this_does_not_exist']
```

**Comment by bitglue** [comment]
Does anyone ever actually do `__all__ = ['FOO'] + ['this_does_not_exist']`?

**Comment by edmorley** [comment]
Perhaps not.

I just spent a fair bit of time trying to figure out why I was seeing false positives F401s in [this file](https://github.com/timothycrosley/isort/blob/0aca83884667f1b20605e3bbef48bacf4f8b77fa/isort/pie_slice.py) when trying to add flake8 to the isort project (which in itself was just to try and prevent the regressions in its recent releases, since I'm only a consumer of that project -- afternoon of yak shaving) - hence filing.
