### ISSUE TITLE
Support PEP526

### ISSUE THREAD

**Issue by acomagu** [PyCQA/pyflakes#282]
Thanks for cool tool!
I met "Imported but unused" after type hints like below:

```
from typing import Optional
v: Optional[int] = 0
```

This syntax is defined in [PEP526](https://www.python.org/dev/peps/pep-0526/) but seems not to be supported yet on pyflakes.

**Comment by myint** [comment]
What version of `pyflakes` are you using?

```
$ pyflakes
from typing import Optional
v: Optional[int] = 0
✔
```

**Comment by acomagu** [comment]
I'm sorry, the below causes the error for sure.

```
from typing import Optional


class A:
    def __init__(self):
        self.v: Optional[int] = None
```

My version is 1.5.0 also.

**Comment by myint** [comment]
Thanks, I can confirm. I guess this is related to #84, where initial support for PEP 526 was introduced.

**Comment by acomagu** [comment]
It passes by the master branch one. Thank you for kind!
