### ISSUE TITLE
Unused variables are not detected in for loops

### ISSUE THREAD

**Issue by behrtam** [PyCQA/pyflakes#285]
Unused variables are not detected in `for` loops.

```python
def print_data_with_index(data):
    index = 0
    for item in data:
        print(item)
```
```
$ pyflakes check_unused.py
$ check_unused.py:2: local variable 'index' is assigned to but never used
```
```python
def print_data_with_index_enumerated(data):
    for index, item in enumerate(data):
        print(item)
```
```
$ pyflakes check_unused.py
$ 
```

_pyflakes: 1.5.0 Python 3.6.2_

**Comment by asmeurer** [comment]
Unpacked variables aren't considered unused, because if you have a function that returns multiple items and you only want one, you have to unpack the others into something.

**Comment by myint** [comment]
It looks like this was discussed in #143.

**Comment by bitglue** [comment]
Like https://github.com/PyCQA/pyflakes/issues/285#issuecomment-322604976 says, I don't think there's a way to fix this which doesn't introduce false positives. Unpacking a tuple and ignoring some of the results is a common enough and valid thing to do, and there's no explicit way to reason about intent in those cases.
