### ISSUE TITLE
Does not detect used/unused modules within packages

### ISSUE THREAD

**Issue by csilvers** [PyCQA/pyflakes#288]
pyflakes does not raise any errors on the following code:
```
import foo.bar
import foo.baz

foo.bar.fn()
foo.bang.fn()
```
despite the fact that `foo.baz` is an unused import, and `foo.bang` is not imported at all.

Is this behavior intentional?  Is there a way to modify pyflakes so it would warn in (ideally) both cases?

Thanks,
craig

**Comment by myint** [comment]
This looks like a duplicate of #137.

**Comment by csilvers** [comment]
You're right! And I thought I was so careful looking through old bug reports...
