### ISSUE TITLE
Ignore unused imports in a try block with except ImportError

### ISSUE THREAD

**Issue by asmeurer** [PyCQA/pyflakes#297]
A common pattern is to try to import a module to see if it is installed, so code can fail early with a nice error message when it isn't. Something like

```py
try:
    import matplotlib
except ImportError:
    raise ImportError("matplotlib is required")
```

The `raise ImportError` could also be some code that uses a fallback. 

Unfortunately pyflakes gives an unused import warning for blocks like this. You can silence them by rewriting like

```py
try:
    import matplotlib
    del matplotlib
except ImportError:
    raise ImportError("matplotlib is required")
```

but I think this pattern is common enough that pyflakes should just ignore unused imports if the import is inside a try block with an "except ImportError". 

Is there any risk of false negative here? As far as I can tell, the only point of "unused import" warnings is to avoid importing a module that you never actually use, which could add import times and unnecessary dependencies. But in this case, the import is very clearly done intentionally.

**Comment by bitglue** [comment]
Not sure I'd agree this is a common pattern since I've never seen it, but it sounds like a reasonable thing to implement.

**Comment by sigmavirus24** [comment]
> Not sure I'd agree this is a common pattern since I've never seen it,

I'll second this uncertainty. That said, given @asmeurer's background, I'd guess this is a common pattern _in the scientific python community_.

**Comment by The-Compiler** [comment]
FWIW what you could do instead (and what might be easier with many modules) is this:

```python
import importlib

for module in ['matplotlib', ...]:
    try:
        importlib.import_module(module)
    except ImportError:
        raise ImportError("{} is required".format(module))
```

**Comment by asmeurer** [comment]
It's not the most common thing in the world, but it does come up. Here's some examples from SymPy https://github.com/sympy/sympy/search?utf8=%E2%9C%93&q=except+ImportError&type= (note, I don't claim all of those are otherwise using good coding patterns that would pass pyflakes). 

Maybe if I get a chance I'll write a dummy patch for this and run it on some code bases to see how many instances it turns up (or if someone else wants to do it, please do so).

**Comment by bitglue** [comment]
If the idea is to determine how common this pattern is, couldn't that test be done without the test and seeing how many errors come up? Having those data, and seeing the usage in full context, would certainly make the decision easier.

That said, as things stand I'm inclined to accept the patch if someone is willing to write it. False positives are bad and the potential for false negatives is low and noncritical.

**Comment by bje-** [comment]
Any progress on this one?

**Comment by CTimmerman** [comment]
Adding this to my import line worked to silence Prospector, which uses flake8, which uses pyflakes:

`  # noqa; unused here but maybe not elsewhere.`

**Comment by bitglue** [comment]
`# noqa` is a flake8 thing; pyflakes doesn't do anything with comments.

What's wrong with the solution suggested in the issue, using `del` to delete the name after attempting to import it? This suppresses the error _and_ avoids polluting the namespace with an unused name. It's explicit, and shorter than a comment.

If the intention is to maybe import something and not use it in the module, but have it as part of the module's namespace, then it can be treated the same way as other defined-but-not-used names: it can be listed in `__all__`, which will also let everyone (pyflakes, humans) know about the intention.

Are there any circumstances not covered by these solutions? If no, I'm inclined to close.

**Comment by asottile** [comment]
agree on closing, there's three "good" solutions to this:

```python
try:
    import mod
    del mod
except ImportError:
    ...
```

```python
try:
    __import__('mod')
except ImportError:
   ...
```

```python
import importlib

try:
    importlib.import_module('mod')
except ImportError:
    ...
```

**Comment by sigmavirus24** [comment]
Agreed
