### ISSUE TITLE
Make a CHANGELOG easy to find

### ISSUE THREAD

**Issue by w0rp** [PyCQA/pyflakes#299]
I see that there's a relatively recent version of `pyflakes`, and I'm trying to figure out what has changed.

First I looked at the GitHub page, and there's no CHANGELOG file I can see. I looked at the GitHub releases page, and I couldn't see release notes for the latest release on there. I looked at PyPi, and I can't find any list of changes. I looked at the pypi.org project page, and I can't see changes there either.

Could you link to an easy-to-read CHANGELOG file from the GitHub README and on PyPi so it's easy to figure out what has changed between each version?

**Comment by bitglue** [comment]
There's a NEWS.txt: https://github.com/PyCQA/pyflakes/blob/master/NEWS.txt
And you can always read the `git log`: https://github.com/PyCQA/pyflakes/commits/master

**Comment by w0rp** [comment]
Aha! I couldn't spot that. I recommend adding a sentence to the README like "for the a list of changes in each version, see NEWS.txt."

**Comment by bitglue** [comment]
Done. Thanks for the suggestion.

**Comment by w0rp** [comment]
Cheers!
