### ISSUE TITLE
Variables only used in fstrings generating 'never used' warnings.

### ISSUE THREAD

**Issue by mkleehammer** [PyCQA/pyflakes#310]
A variable that is created and only used in an fstring is generating a warning:

    def test():
        x = 'testing'
        print('This uses {x}...')

I'm using this via flake8 (in emacs) which generates:

    warning  F841   local variable 'x' is assigned to but never used (python-flake8)

Since it is actually used, I would not expect a warning.

**Comment by myint** [comment]
That looks like a normal string. Did you mean the following, which Pyflakes handles correctly?

```python
def test():
    x = 'testing'
    print(f'This uses {x}...')
```

**Comment by mkleehammer** [comment]
The example was wrong, but now I don't remember where I was seeing the original problem.  It was a large piece of code and it was probably a similar error.

**Comment by gmagno** [comment]
(leaving this here in case someone else hits this non-issue)
I also thought, for a moment, I was hitting a bug:

![image](https://user-images.githubusercontent.com/46817915/89899961-72391e00-dbb9-11ea-9acd-adfc30468697.png)

In fact, multiline f-strings need the `f` in front of every string:

![image](https://user-images.githubusercontent.com/46817915/89900300-f2f81a00-dbb9-11ea-868f-d30c30ceeee0.png)

**Comment by ben-dyer** [comment]
@gmagno Thank you for sharing, was making the same mistake & I was trusting second line was already an f-string because the syntax highlighting looked good
