### ISSUE TITLE
Option for displaying line:column.

### ISSUE THREAD

**Issue by iogf** [PyCQA/pyflakes#311]
Hi,

i have been developing a plugin for https://github.com/iogf/vy which integrates
with pyflakes. The fact of pyflakes sometimes displaying column number
it makes the parsing of the output harder. It would be interesting if it were possible
to either avoid the displaying of column number in the reports or just always displaying it.

Is it possible?

**Comment by bitglue** [comment]
Why would you want to do this when `Message` has [line number and column attributes](https://github.com/PyCQA/pyflakes/blob/8d0f995dafda7105a6966057fd11383f1ea6fb71/pyflakes/messages.py#L12-L13)?

**Comment by iogf** [comment]
It seems the actual pyflakes version that i have installed it gives me sometimes just the line attribute. In some occasions it displays as well as the column attribute.

~~~

file1.py:1:17: invalid syntax
from mod import :
                ^
irc.py:43: 'os.ppp' imported but unused
[tau@sigma pyflakes]$ 

~~~

**Comment by bitglue** [comment]
Yes, but why are you trying to parse the output at all? Pyflakes has a perfectly good python API. See the tests or flake8 for example.

**Comment by bitglue** [comment]
I think it will be difficult, since not all errors provide that information easily.

You should use the API. The API is tested and stable. The text output is subject to change.

**Comment by iogf** [comment]
What about adding an option to omit the column attribute for all cases and leaving for default the behavior of displaying line:column according to the report's information?

**Comment by bitglue** [comment]
Pyflakes so far has no options, and a one-off use case like this doesn't seem like justification to add one. There's an API which I recommend, but if you really want to parse the text output, discarding the column number is not an intractable parsing issue. A simple regex could do it.
