### ISSUE TITLE
RFE: Check for invalid escape sequences

### ISSUE THREAD

**Issue by yan12125** [PyCQA/pyflakes#312]
In CPython 3.6, invalid escape sequences are deprecated (https://bugs.python.org/issue27364). For example:
```
$ python -W all
Python 3.6.3 (default, Oct 24 2017, 14:48:20) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'C:\Windows\System32'
<stdin>:1: DeprecationWarning: invalid escape sequence \W
'C:\\Windows\\System32'
```
It would be great to check for them.

**Comment by yan12125** [comment]
Oh, pyflakes is based on AST. I guess a patch for CPython is necessary so that it'll expose the original string literal.

**Comment by sigmavirus24** [comment]
Also, pycodestyle already provides this check as W605. I don't think pyflakes and pycodestyle both need to warn on the same things, especially when it would require a change in the AST that would only be present in CPython 3.8 and onwards (which would make it pretty ineffectual)

**Comment by yan12125** [comment]
Thanks for the tip. I didn't check pycodestyle as invalid escape sequences do not sound like a coding style issue for me. Just tried it and it works fine.
