### ISSUE TITLE
"_" should not be flagged

### ISSUE THREAD

**Issue by Eureses** [PyCQA/pyflakes#316]
When saving a result to "`_`" instead of a variable, it should not be flagged as unused. Also, variables preceeded by a "`_`" should not be flagged as unused.

**Comment by sigmavirus24** [comment]
Can you please provide examples where you think this occurs and how you're running pyflakes?

**Comment by Eureses** [comment]
A line like
_ =  self.Refresh()
throws a warning UnusedVariable: local variable '_' is assigned to but never used. I'm running this in the Beacon environment. https://www.beacon.io/

**Comment by sigmavirus24** [comment]
Sorry, I wasn't trying to ask where you work. I meant, how do you get pyflakes' output? Do you run `pyflakes project.py` or `flake8 project.py` or do you do something else?

**Comment by Eureses** [comment]
I'm a Beacon user, but not an employee of their firm, so I see the output within their IDE, but the implementation of it is not visible to me. I raised a bug issue with them and was told that this is actually a pyflakes bug/enhancement.

**Comment by myint** [comment]
See #202 and #73.
