### ISSUE TITLE
Redundant list comprehensions should be flagged

### ISSUE THREAD

**Issue by Eureses** [PyCQA/pyflakes#317]
Functions like "sum" expect an iterable, so code like sum( [ o for o in objs ] ) should be flagged for having a redundant list comprehension.

**Comment by bitglue** [comment]
What if `sum` has been redefined to mutate its parameter? In that case `sum( [ o for o in objs ] )` and `sum(objs)` would be very different things since the former effectively makes a copy.

**Comment by joaoe** [comment]
`pyflakes` exist mainly to detect errors. This problem is mostly about optimization.

**Comment by asottile** [comment]
closing as above

you may find [flake8-comprehensions](https://pypi.org/project/flake8-comprehensions/) helpful :+1:

**Comment by Eureses** [comment]
Thanks, Anthony.

________________________________
