### ISSUE TITLE
Drop support for EOL Python versions?

### ISSUE THREAD

**Issue by hugovk** [PyCQA/pyflakes#319]
I'd like to suggest pyflakes only supports non-EOL Python versions.

Python 2.5, 2.6, 3.2 and 3.3 are EOL and no longer receive security updates.

![image](https://user-images.githubusercontent.com/1324225/33826009-275286e4-de6c-11e7-8f70-781433006423.png)

https://github.com/PyCQA/pyflakes#pyflakes says:

> It is available on PyPI and it supports all active versions of Python from 2.5 to 3.6.

It can be argued that 2.5-2.6 and 3.0-3.3 are no longer active and no longer need support.

Here's the pip installs for pyflakes from PyPI for the last month (via `pypinfo --percent --pip --markdown pyflakes pyversion`) showing low or non-existent numbers for the EOL versions.

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |   54.1% |        582,452 |
| 3.6            |   20.5% |        221,023 |
| 3.5            |   17.2% |        185,122 |
| 3.4            |    6.8% |         72,930 |
| 3.3            |    0.6% |          6,432 |
| 2.6            |    0.4% |          4,789 |
| 3.7            |    0.4% |          4,226 |
| 3.2            |    0.0% |            414 |
| None           |    0.0% |              4 |

Some other PyCQA projects are planning on ending all Python 2 support around mid-2018 when Python 3.7 is due out (https://github.com/PyCQA/meta/issues/19).

**Comment by sigmavirus24** [comment]
Just a note, that information from BigQuery is a little misleading as I understand how it was generated. Folks using python 2.5 don't have an installer that reports the version info to PyPI such that it can't be measured in the most accurate way.

That said, given that a measurable 98.2% of downloads in the last month are for 2.7, 3.4, 3.5, and 3.6 it makes sense to me that we drop 2.6, 2.5, and 3.3. That said, it doesn't appear that dropping 2.7 support will be reasonable in approximately 6 months time. It'd be more reasonable if 2.7 usage dropped to approximately where 3.4 is today.

**Comment by bitglue** [comment]
Would this simplify the pyflakes code? As far as I know, 2.4 and 2.5 aren't requiring any significant work besides what we already must do for 2.7.

**Comment by hugovk** [comment]
@bitglue It'd simplify it not a huge amount but somewhat. At least [this](https://github.com/PyCQA/pyflakes/compare/master...hugovk:rm-eol?expand=1) if dropping all EOL, perhaps a bit more if the `PY32`/`PY33` constants were replaced with `PY2`.
