### ISSUE TITLE
Warn on unreachable code:

### ISSUE THREAD

**Issue by Wilfred** [PyCQA/pyflakes#323]
It would be nice if pyflakes could warn on the following code:

```python
def foo():
    return 1
    print(1) # unreachable

def bar():
    raise Exception('oh no')
    print(1) # unreachable
```

Ideally, it would also cover cases like this:

```python
def foo(x):
    if x:
        return 1
    else:
        return 2
    print(1) # unreachable
```

and possibly even this:

```python
def foo(x):
    if False:
        print(1) # unreachable
```

(although I know mypy can use `if False: import foo` for type definitions that aren't used at runtime.)

Would you be willing to accept a patch to pyflakes that added this?

**Comment by bitglue** [comment]
Sounds reasonable, if exceptions can be made for mypy to avoid false positives. I haven't used mypy, so I don't really know.

**Comment by asottile** [comment]
duplicate of #170
