### ISSUE TITLE
Handler for ARGUMENTS node missing

### ISSUE THREAD

**Issue by MacBox7** [PyCQA/pyflakes#338]
For a code like this:
```
def foo():
    def bar():
        pass
```
while generating pyflakes AST using
```
tree = ast.parse(code)
result = Checker(tree.body[0], filename='test.py')
```
pyflakes result in error:
```
Traceback (most recent call last):
  File "/home/ankit/Documents/GitHub/pyflakes/pyflakes/checker.py", line 1489, in <module>
    result = Checker(tree.body[0], filename='test.py')
  File "/home/ankit/Documents/GitHub/pyflakes/pyflakes/checker.py", line 511, in __init__
    self.handleChildren(tree)
  File "/home/ankit/Documents/GitHub/pyflakes/pyflakes/checker.py", line 861, in handleChildren
    self.handleNode(node, tree)
  File "/home/ankit/Documents/GitHub/pyflakes/pyflakes/checker.py", line 907, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/home/ankit/Documents/GitHub/pyflakes/pyflakes/checker.py", line 736, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'ARGUMENTS'
```

The solution is to either provide a handler or simply ignore it.
Solution is similar like [this](https://github.com/PyCQA/pyflakes/blob/master/pyflakes/checker.py#L971)
```
ARGUMENTS = ignore
```

**Comment by MacBox7** [comment]
Note: Here I am only generating pyflakes AST for a segment of code i.e the inner content of function `foo`.

**Comment by MacBox7** [comment]
As a matter of fact there are quite some nodes defined in [green tree docs](http://greentreesnakes.readthedocs.io/en/latest/nodes.html) whose handler isn't provided. I believe the default mechanism should be to ignore if no handler is present.

**Comment by myint** [comment]
I'm trying to understand the context here. Is this specific to checking a segment of code or can this be reproduced in the general case of checking a full file?

**Comment by MacBox7** [comment]
This is specific to segment of code. I believe there is no harm in in returning pyflakes AST for a segment of code if desired. Plus the work done over [here](https://github.com/PyCQA/pyflakes/blob/master/pyflakes/checker.py#L1186) should be ideally placed in an ARGUMENT handler to improve cohesion.

**Comment by myint** [comment]
So if I'm understanding correctly, you are trying to adapt `Checker()` to support checking subsets of code rather than full modules. `ARGUMENTS` is necessary for this new use case.

And this would be a minimal version of the initial example:

`foo.py`:
```python
import ast

import pyflakes.checker


tree = ast.parse("""\
def bar():
    pass
""")
pyflakes.checker.Checker(tree.body[0])
```

```
$ python foo.py
Traceback (most recent call last):
  File "foo.py", line 11, in <module>
    pyflakes.checker.Checker(tree.body[0])
  File "/Users/myint/projects/pyflakes/pyflakes/checker.py", line 497, in __init__
    self.handleChildren(tree)
  File "/Users/myint/projects/pyflakes/pyflakes/checker.py", line 824, in handleChildren
    self.handleNode(node, tree)
  File "/Users/myint/projects/pyflakes/pyflakes/checker.py", line 870, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "/Users/myint/projects/pyflakes/pyflakes/checker.py", line 700, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'ARGUMENTS'
```

Is this the only such hurdle to checking a subset of the code? I would imagine you would run into other problems given that `Checker()` is meant to consume the AST of a module. For example, `self.scopeStack` is initialized to `ModuleScope()`.

**Comment by MacBox7** [comment]
I was using deadScopes to extract meaningful data from the code. Now the hurdle which I was facing was. Consider the following example:
```
class Foo:
  class Bar:
    pass
```
Now the deadScopes returned from pyflakes would be something like =>
-  module_scope

   - __len__ = {int} 1
   -  Foo {ClassDefinition}

      -  name = {Str}'Foo'
      -  source = [{ClassDef}]

-  class_scopes

   - 0 = {ClassScope}         # Class scope corresponding to Bar

     - __len__ = {int} 0

   - 1 = {ClassScope}         # Class scope corresponding to Foo

     - __len__ = {int} 1
     - Bar {ClassDefinition}  # This scope contains class Bar

       - name = {Str}'Bar'
       - source = [{ClassDef}]

So as you can see the source consists of a [cpython node {ClassDef}](http://greentreesnakes.readthedocs.io/en/latest/nodes.html#ClassDef) but I want this to be a pyflakes node(ClassDefinition in this case) to maintain consistency while traversing. I don't want to switch back to _ast nodes. Thus what I was doing, I was parsing the source object again through pyflakes `Checker` to return pyflakes node. Thus parsing a segment of code. And yes `self.scopeStack` being initialized as ModuleScope() might be a problem. Can this passed as a constructor argument. keeping the default to ModuleScope() to maintain backward compatibility?

The advantage of this is another person can use pyflakes to create more different types of scope. Say `FunctionScope` if you are traversing through a function.

**Comment by myint** [comment]
Passing in the scope to the `Checker` constructor seems reasonable to me.

**Comment by MacBox7** [comment]
So, what all shall be done :sparkles:

**Comment by myint** [comment]
Make the changes and add test cases to demonstrate the new functionality. If you submit a pull request, I can review it.

**Comment by MacBox7** [comment]
Well, there are 2 ways this can be handled.
1. Simply ignore ARGUMENT handler.
2. Transfer [this](https://github.com/PyCQA/pyflakes/blob/master/pyflakes/checker.py#L1186) section inside an ARGUMENT handler and process it there.

Both would work. But the 2 way would be more apt and improve the understanding of the code base.
What's your opinion on this?

**Comment by myint** [comment]
(Somehow I didn't see a notification for this conversation.)

I agree with your assessment about 2.

**Comment by MacBox7** [comment]
Great. Give me some time. I'll create a patch soon.
