### ISSUE TITLE
In Python 3.6 unused variables in f-strings show line number 1

### ISSUE THREAD

**Issue by asmeurer** [PyCQA/pyflakes#349]
I don't know if this is fixable or not, but in Python 3.6, f-strings with unused variables show the line number as 1. This is very annoying as I use an editor plugin that highlights lines that have errors. 

The issue seems to be fixed in Python 3.7. 

```
$cat test.py
def test():
    f"{b}"
```

**Python 3.6**

```
$PYTHONPATH=~/Documents/pyflakes python -m pyflakes test.py
test.py:1: undefined name 'b'
```

**Python 3.7**
```
$PYTHONPATH=~/Documents/pyflakes python -m pyflakes test.py
test.py:2: undefined name 'b'
```

**Comment by CLiu13** [comment]
I cannot seem to reproduce this issue. I ran pyflakes on the same file in a Python 3.6 Docker container with pyflakes 2.0.0 installed, and the result is `test.py:2: undefined name 'b'`

Raw output is below:

`root@f5bb7fcf51ab:/# python --version`
`Python 3.6.7`
`root@f5bb7fcf51ab:/# pyflakes --version`
`2.0.0`
`root@f5bb7fcf51ab:/# python -m pyflakes test.py`
`test.py:2: undefined name 'b`

**Comment by asmeurer** [comment]
Works for me too in Python 3.6.6 and pyflakes 2.0.0.

**Comment by CLiu13** [comment]
Issue has been reproduced with 3.6.0, 3.6.1, 3.6.2 - now investigating.

**Comment by asmeurer** [comment]
I figured it was probably a CPython bug.
