### ISSUE TITLE
F841 "assigned to but never used" doesn't work on module root

### ISSUE THREAD

**Issue by khink** [PyCQA/pyflakes#358]
If i test this file with pytest 1.6.0:
```
jos = 'henk'
```

It passes without error.

If i run it on this file (i called it f841.py):
```
def my_method():
    jos = 'henk'
```
i get `f841.py:2: local variable 'jos' is assigned to but never used`

Why does it not report an error in the first case?

**Comment by jayvdb** [comment]
module scope variables are not unused, as they are implicitly exported, and available to be imported by another module.

locally scoped variables within a function can not be exported, so can be determined whether they are unused or not.

Does that address your query, or did I misunderstand your query?

**Comment by khink** [comment]
That answers my question. Thanks!
