### ISSUE TITLE
Print function with f-string, Fedora Linux.

### ISSUE THREAD

**Issue by Alexound** [PyCQA/pyflakes#359]
The **print()** function shows error "Invalid Syntax", when used with f-string. Python 3.7.
Issue appears on Linux, Fedora 28. 
![screenshot_1](https://user-images.githubusercontent.com/22021219/44043417-e284c26e-9f33-11e8-9aec-8f6c4b683adc.png)

No such problems on Windows 10.

**Comment by asmeurer** [comment]
Are you sure pyflakes is being run in Python 3.7? This is generally indicative of using the wrong version of Python, as pyflakes can only check for the Python version it is being run in. So if you use pyflakes in Python 3.5 or Python 2.7, then it won't know about f-strings and will report them as a syntax error.

**Comment by Alexound** [comment]
@asmeurer:
Hey there. Thanks for the quick reply. The actual problem was, that python-language-server was not
installed for python3. 
Now it's solved.
Sorry for disturbing.
