### ISSUE TITLE
Flake8 check does not catch spaces around typed default arguments

### ISSUE THREAD

**Issue by RoelandMatthijssens** [PyCQA/pyflakes#360]
```
def f(x=1):
    return x
```
Passes flake8 check (Expected)
```
def f(x = 1):
    return x
```
Fails flake8 check (Expected)
```
def f(x: int=1):
    return x
```
Passes flake8 check (Expected)
```
def f(x: int = 1):
    return x
```
Passes flake8 check (Unexpected)

I expect the last check to also fail the flake8 check.

**Comment by MacBox7** [comment]
Flake8 uses pyflakes, but these errors are not specific to pyflakes. Please address your concerns at [flake8 gihub](https://github.com/PyCQA/flake8) or [flake8 gitlab](https://gitlab.com/pycqa/flake8).

**Comment by RoelandMatthijssens** [comment]
Ok thanks :)
