### ISSUE TITLE
Pyflakes not able to handle custom source codec

### ISSUE THREAD

**Issue by mixmastamyk** [PyCQA/pyflakes#361]
Hi,

I'm using a non-standard codec that seems to interfere with pyflakes:
https://github.com/asottile/future-fstrings

A python file:

    # -*- coding: future_fstrings -*-
    pass 

Results in:

    ⏵pyflakes *.py 
    file.py: problem decoding source

Somehow I need to load this codec for pyflakes, but not sure how.  It is just a copy of utf8.

**Comment by bitglue** [comment]
Pyflakes performs no handling of the encoding itself. Are you perhaps installing future-fstrings in python3 but running pyflakes with python2?

**Comment by asottile** [comment]
Works for me 🤷‍♂️ 

```console
$ pip freeze --all
future-fstrings==0.4.4
pip==18.0
pyflakes==2.0.0
setuptools==40.2.0
tokenize-rt==2.0.1
wheel==0.31.1
$ pyflakes t.py; echo $?
0
$ cat t.py 
# -*- coding: future_fstrings -*-
pass
```

**Comment by mixmastamyk** [comment]
head (which pyflakes)
    #!/usr/bin/python3
    …

Doesn't look like it.

Believe the problem is that python has to get involved in the decoding of the source file, but since pyflakes runs as an external command there is no way currently to tell it how to decode it.  Somehow future_fstrings installs itself to be available to python, but pyflakes doesn't notice.

**Comment by asottile** [comment]
@mixmastamyk can you run `/usr/bin/python3 -m pip freeze` and paste the output?

**Comment by mixmastamyk** [comment]
Fixed!  Believe it was something to do with using the wrong virtualenv, your comment helped me figure that out.  Thanks.  I installed elsewhere and it worked.  Cheers,
