### ISSUE TITLE
'local variable 'blah' is assigned to but never used' inconsistent with use of del

### ISSUE THREAD

**Issue by H0R5E** [PyCQA/pyflakes#363]
## Problem Description

The warning "local variable 'blah' is assigned to but never used' is inconsistently triggered when using `del`.

### What steps reproduce the problem?

Consider the following function:

```
def test():
    color = 1
    del color
```

Pyflakes returns nothing in this case, yet

```
def test():
    if True:
        color = 1
        del color
```

gives: "local variable 'color' is assigned to but never used"

### What is the expected output? What do you see instead?

The warning should be produced in all similar circumstances, yet it seems to be only triggered for limited cases right now.

## Versions

python = 2.7.14
pyflakes = 1.6.0 & 2.0.0

**Comment by myint** [comment]
Sounds like #110.
