### ISSUE TITLE
red highlighting difficult for some color schemes

### ISSUE THREAD

**Issue by raphaelcervantes** [PyCQA/pyflakes#364]
My color scheme makes variables purple and I have a dark background. This makes it difficult for me to see what I'm typing while pyflake is highlight an entire line in red (see attached picture).  I couldn't figure out how to change the highlighting scheme, such as how to change the highlight to a different color or make it less strong, or how to have it highlight only the beginning of a line, or to only use underlines instead. I just couldn't find any documentation. Can you point me to it?
![highlighting](https://user-images.githubusercontent.com/18469999/45333325-67d3fc80-b52a-11e8-90ae-8ccbc9b8fbab.png)

**Comment by sigmavirus24** [comment]
Pyflakes does not do this for you in vim, but plugins for vim, e.g., Syntastic do. You'll need to configure that plugin.
