### ISSUE TITLE
Consistency in declaring unused variables

### ISSUE THREAD

**Issue by AbdealiJK** [PyCQA/pyflakes#365]
```
In [56]: pyflakes.api.check("a = 1\nb = 2", 'test.py')
Out[56]: 0

In [57]: pyflakes.api.check("def abc():\n    a = 1\n    b = 2", 'test.py')
    ...:
test.py:2: local variable 'a' is assigned to but never used
test.py:3: local variable 'b' is assigned to but never used
Out[57]: 2

In [58]: pyflakes.api.check("def abc(a, b):\n    pass", 'test.py')
Out[58]: 0

In [59]: pyflakes.api.check("def abc(a=1, b=2):\n    pass", 'test.py')
Out[59]: 0
```

This is confusing for me, because:
If I declare a variable globally it seems like that is not an issue.
Declaring it locally is an issue.
if I pass an unused function argument it is not an issue.
if I pass an unused function keyword arguments with a default value it is not an issue.

Is this expected behaviour ? 
All cases are declaring unused variables. 2,3,4, are doing local unused variables.

**Comment by bitglue** [comment]
It's expected. It has to do with whether or not there are other reasons the variable should exist.

First case, module-level variables: these might be constants set for other modules to import and use.

Second case, variable assignments in a function: no reason to do this, so it's an error.

Third case, unused function parameters: maybe you're writing code which must conform to a particular interface, and you just don't have a reason to use all the parameters in this case. Not an error.

Fourth case, same as previous but with defaults.

In keeping with the [design principles](https://github.com/PyCQA/pyflakes#design-principles), when a thing may or may not be an error, Pyflakes gives the author the benefit of the doubt and doesn't emit an error.
