### ISSUE TITLE
Exclude "import ... as _" from unused-imports

### ISSUE THREAD

**Issue by anntzer** [PyCQA/pyflakes#366]
Similarly to #202/#335 (excluding `_` from unused-variable checks), it would be appreciated if `import ... as _` was excluded from unused-import checks.

An example use case is when the module is imported solely for side-effects, see e.g. https://github.com/matplotlib/matplotlib/pull/12249.

Example repro (pyflakes 2.0 and master):
```
$ python -mpyflakes <(printf 'from foo import bar as _\n')
/proc/self/fd/11:1: 'foo.bar as _' imported but unused
```

**Comment by graingert** [comment]
I tend to use `importlib.import_module("path.to.side.effect.module")` when requiring side effects

**Comment by anntzer** [comment]
IMHO that just seems like "writing less natural code just to make the linter happy"?

**Comment by sigmavirus24** [comment]
Is it really? In my opinion, it's a clearer signal of "We're importing this for some other reason." There's actually a convention of importing something from an internationalization (i18n) library as `_` in many large projects and then calling `_("test to be translated")`.

**Comment by graingert** [comment]
importlib.import_module also has the benefit of not being moved my isort

**Comment by anntzer** [comment]
Fair point re: collision with gettext (well, I haven't ever used it, but I can guess the idea).
OTOH if someone just writes `importlib.import_module("foo")` at the toplevel I don't think it would be particularly clear that they're intentionally doing an import for side-effects -- at least to me `import foo as _` is clearer given that binding to `_` is a standard convention for "do something and ignore its results".
In any case, I think that even if there are alternatives (i.e. importlib.import_module) available, pyflakes *could* still support `import ... as _`?

**Comment by sigmavirus24** [comment]
If we "support" that, then people importing any i18n library and aliasing it as `_` will not be warned when they're no longer using it in that module which seems bad

**Comment by anntzer** [comment]
But gettext even supports `gettext.install` (https://docs.python.org/3/library/gettext.html#gettext.install) which patches *builtins* with `builtins._` and there's no way for pyflakes to detect whether `_` is used at all.
Or you could also special-case `from gettext import _` and handle that import as a "normal" one.

**Comment by mgedmin** [comment]
In many projects I've imported gettext-equivalent translation functions as `_`.  I appreciate flake8 telling me when those are no longer used and can be removed.

To me the canonical spelling of "this import used for side effects only" is
```python
import something  # noqa: does thins thing as a side effect that we need done here
```

**Comment by graingert** [comment]
another option:

```python
import something
assert something
del something
```

**Comment by bitglue** [comment]
This won't be accepted.

- [people find the existing behavior useful](https://github.com/PyCQA/pyflakes/issues/366#issuecomment-633699332)
- `_` is just one convention, but it's not universal.
- [`del` is a better solution](https://github.com/PyCQA/pyflakes/issues/366#issuecomment-633701748): it's explicit, universal, and guarantees the import is not referenced, as intended.
