### ISSUE TITLE
Error in function inside function

### ISSUE THREAD

**Issue by midnio** [PyCQA/pyflakes#368]
```python
import re

def transpile(code: str) -> str:
  def generate(parsed: list) -> str:
    ...
```

This code gives error.

**Comment by bitglue** [comment]
Can you please provide a complete example, including the specific error produced, and what you expect to happen and why?

**Comment by midnio** [comment]
It should not give an error. Because there is nothing wrong it this code snippet.

**Comment by bitglue** [comment]
The only error I get is that `re` is imported and unused, which seems correct. Please provide more information, including what version of pyflakes and python you are using, how you ran it, and what error you got.

**Comment by midnio** [comment]
`import re` doesnt gives an error. the error is at:
```python
def generate(parsed: list) -> str:
                         ^
                         |
                       Here
```

**Comment by midnio** [comment]
Oh, after updating it the error is gone. Thanks.
