### ISSUE TITLE
Silently ignored unparsed __all__

### ISSUE THREAD

**Issue by jayvdb** [PyCQA/pyflakes#383]
Following on from https://github.com/PyCQA/pyflakes/pull/382 , there are a lot of other possible uses of statically understandable logic to build `__all__` which are not handled, or will cause errors.

not handled:
```
__all__ = ['a', 'b', 'c', 'd']
__all__ -= ('d', )
```

not recognised:
```
__all__ = ['a'] + ['b'] * 3
```

error:
```
b = 'b'
__all__ = ['a'] + [b] + ['c']
```
> ValueError: malformed node or string: <_ast.Name object at 0x7f0e15a50908>

The parser should be more conservative , and either discard things it doesnt recognise, or handle more cases when that is easier and more sensible.  It isnt worth going too far, as filling `__all__` using logic is quite rare, and limited to a few types of logic that are useful. i.e. `*3` is never useful.

pyflakes should not emit an error message for unparsed `__all__` logic, and there should be a test to ensure that it doesnt.  To do this now, we need to identify a valid logic for `__all__` which pyflakes will likely never correctly understand, and use that as the test to verify it doesnt emit an error.

On the other hand, if pyflakes recognises a logic operation on `__all__` which it 100% understands and knows is illogical, that could be an error message.  The `*3` is a possible candidate for that. While `__all__` should have unique items in it, logic which adds the same item multiple times is probably not an error, as that could be due to them being `+=`'d in different branches of logic, and `['a'] * 3` is intentionally filling it with duplicates.  But filling it with integers is always wrong.

**Comment by seeeturtle** [comment]
@jayvdb ,
```
__all__ = ['a', 'b', 'c', 'd']
__all__ -= ('d', )
```
this makes error, since list doesn't accept sub with tuple (nor list).
```
>>> l = [1, 2, 3]
>>> l -= (1,)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for -=: 'list' and 'tuple'
```
However, pyflakes doesn't emit any error. I think this should be another issue.

**Comment by joaoe** [comment]
`TypeError: unsupported operand type(s) for -=: 'list' and 'tuple'`

That's a runtime exception that will be easily detected when the script runs. `pyflakes` does not need to do type checking or making assumptions how specific operators are implemented in specific built-in types. There is type hinting and `mypy` for that.

**Comment by asottile** [comment]
the crash here has been fixed, I see no reason to handle `-=` or `*` in `__all__` -- they're both nonsensical and cannot succeed at runtime
