### ISSUE TITLE
Warn about `return` inside `finally`

### ISSUE THREAD

**Issue by joaoe** [PyCQA/pyflakes#404]
Hi.

There is a feature in many programming languages (e.g. Java and python) in which a `return` from a `finally` block will silence the exception. It is a dangerous feature of the languages as errors can easily be suppressed unknowingly, e.g.
```
def task(data):
  try:
    complex_task(data)
  finally:
    if not data:
      return # in case of an exception, it is dropped
    logger.info("Blah...")
    another_complex_task(data)
    cleanup(data)
```
Silencing of exception should always be done explicitly with a proper `except ExceptionType` block with a `pass` or `return`. If you want to break from the `finally` block then you can refactor the code not to use a `return`.

Hence, I suggest this shall be flagged as a warning
```
def anything():
  raise ValueError()

def main():
  try:
    anything()
  finally:
    return

main()
```

**Comment by joaoe** [comment]
Doh, someone incorrectly closed the pull request :(

**Comment by asmeurer** [comment]
I didn't know about this behavior. It is [documented](https://docs.python.org/3/reference/compound_stmts.html#try), but the documentation also seems to imply that it is only done this way for technical reasons ("The exception information is not available to the program during execution of the finally clause."). 

I wonder if you can point to some references that this is universally bad behavior. pyflakes only warns about things that are 100% always wrong, to avoid false positives. It seems that doing a return in a finally could have a legitimate use-case. Granted, most people won't know that this happens, but I don't necessarily see that as a valid argument to disallow it from a linter (most people also don't know how for/else works, but that doesn't mean that it's a construct that should never be used). 

The closest parallel I can think of to this is a bare `except:` block. It's almost always used incorrectly, silencing more exceptions than desired, and it is not technically needed (it's syntactically equivalent to `except BaseException:`). But it does have legitimate uses, and if pyflakes warned about it (it doesn't), there would be a lot of false positives.

**Comment by joaoe** [comment]
> The exception information is not available to the program during execution of the finally clause

That is not true:
```
import sys
try:
  raise ValueError()
finally:
  print(sys.exc_info())
```

> It seems that doing a return in a finally could have a legitimate use-case.
The two cases are: 
1. supress an exception, but it is the best practice to do that explicitly with an `except`  block
2. return from the function but the code can easily be refactored not to rely on the `return` inside the `finally`

Another broken behavior of `return` inside finally is when running `finally` after a return
```
def a():
	try:
		return 1
	finally:
		return 2

print(a())
```
The original return value is lost. So this is dangerous behavior that can introduce subtle bugs

From my POV returns in finally are generally considered a bad practice.
https://cwe.mitre.org/data/definitions/584.html

**Comment by bitglue** [comment]
Agreed this could be surprising behavior, but pyflakes doesn't have "warnings", only errors. As a matter of [design principle](https://github.com/PyCQA/pyflakes/#design-principles) it emits errors only in cases where there is certainly no legitimate use case for a particular construction. This is why pyflakes doesn't have any options to configure what gets checked.

On the other hand rules are more like guidelines, and if you can show that implementing the proposed check, when run on a large corpus of diverse and generally high-quality, tested code turns up actual bugs with very few false positives, there's room for pragmatism.

Otherwise, a check as proposed might be more suitable in something like https://pypi.org/project/flake8-bugbear/

**Comment by Hanaasagi** [comment]
There is a proposal about this. https://www.python.org/dev/peps/pep-0601/

**Comment by joaoe** [comment]
Moved to https://github.com/PyCQA/flake8-bugbear/issues/99
