### ISSUE TITLE
pyflakes Does not play well with Mypy type annotations

### ISSUE THREAD

**Issue by vasanthaganeshk** [PyCQA/pyflakes#407]
I'm using pyflakes `2.0.0` with flake8.

**Example code for false positive error:**

```
from typing import List
a = foo(
      a=123, b=234
    ) # List[SomeObject]
```

**Comment by asottile** [comment]
`# List[SomeObject]` is not a type annotation according to mypy, you want `# type: List[SomeObject]`

**Comment by asottile** [comment]
for the spec on type comments, check out [PEP 484](https://www.python.org/dev/peps/pep-0484/#type-comments)
