### ISSUE TITLE
wrong range for undefined variable diagnostics

### ISSUE THREAD

**Issue by AmjadHD** [PyCQA/pyflakes#417]
![screenshot_1](https://user-images.githubusercontent.com/33235928/51709853-cc9a7a00-2027-11e9-8bae-e884278e612b.png)

As you can see the range of the diagnostic "foo may be undefined or defined from star imports: mod" does not end at the end of `WIDTH` but continues to the end of the line.

Note: the screenshot is sublime text 3 with LSP.
this is the corresponding entry in the diagnostics array sent bypyls to LSP:
`{'message': "'SOUNDS_FOLDER' may be undefined, or defined from star imports: settings", 'range': {'end': {'character': 91, 'line': 29}, 'start': {'character': 52, 'line': 29}}, 'source': 'pyflakes', 'severity': 2}`

**Comment by sigmavirus24** [comment]
We don't control the sublime text 3 behaviour and only provide a line number if I remember correctly. We don't provide a range otherwise.

**Comment by asmeurer** [comment]
It could be useful to give column numbers for undefined variable errors. Pyflakes already emits column numbers for syntax errors. I don't know if the syntax generally supports ranges, but if it does that could be useful as well.  Otherwise the column of the first character of the first instance of the variable should be sufficient. 

I agree for this issue Sublime is doing its own thing, so this is not a valid Pyflakes issue. It's probably guessing the location based on the name of the undefined variable.

**Comment by sigmavirus24** [comment]
I've forgotten how after so many years, but Flake8 reports columns, I think.

**Comment by sigmavirus24** [comment]
@AmjadHD This is the raw output from pyflakes

```
~ ❯❯❯ cat foo.py                                                                                                                                                                                                                                                                                                             ⏎
from os.path import *

print(exists(__file__))
~ ❯❯❯ pyflakes foo.py
foo.py:1: 'from os.path import *' used; unable to detect undefined names
foo.py:3: 'exists' may be undefined, or defined from star imports: os.path
```

I can guarantee you that we are not in fact defining anything other than the line number. `pyls` or `sublime` is doing the wrong thing here.

**Comment by AmjadHD** [comment]
> I can guarantee you that we are not in fact defining anything other than the line number

Well I believe that's not accurate, it would be an enhancement to provide the colon number too.

**Comment by sigmavirus24** [comment]
> Well I believe that's not accurate

If you read the output above, your belief would change 😄 Specifically, `foo.py:1: 'from ...` shows that we explicitly only return the line number. And you've already edited your original message to show this is not a pyflakes bug. To keep the conversation clear and on topic, I'd suggest filing a separate issue for including the column number

**Comment by AmjadHD** [comment]
Ok I'll file a separate issue, but mean while is there a way to ignor this warning ?

**Comment by AmjadHD** [comment]
I was going to open an issue, when I found #158, isn't this related and why was it closed ?
