### ISSUE TITLE
2.1.0 is broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [PyCQA/pyflakes#422]
https://travis-ci.org/borgbackup/borg/jobs/486513787

**Comment by asottile** [comment]
while this isn't a very quality bug report it gave me enough information to find a minimal reproduction.  @ThomasWaldmann  in the future it would be good to include the stacktrace, the project, the version information, etc. in the issue (even the filename if you could identify it)

I've managed to boil this down to a minimal case:

```python
x = lambda f: f

@x
def t():
    pass

y = lambda f: f

@x
@y
def t():
    pass

@x
@y
def t():
    pass
```

**Comment by asottile** [comment]
#423 has a fix for this

**Comment by sigmavirus24** [comment]
That's a question for @bitglue, ~grumpy cat~ @ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
Update: besides failing all our travis-ci test runs, it also hangs flake8 in our local vagrant-based test setup, see link directly above.

**Comment by sfstpala** [comment]
This issue is not fixed

**Comment by sfstpala** [comment]
Deleted my comment. I thought you guys would be more welcoming. 👎
