### ISSUE TITLE
F811 (redefinition of unused variable) incorrectly triggered with @overload decorator

### ISSUE THREAD

**Issue by smoehrle** [PyCQA/pyflakes#434]
This bug was fixed for functions in #320. It still occurs if the function is inside a class and/or has multiple decorators (e.g. @staticmethod, @classmethod):
```python
from typing import overload


class test:
    @overload
    def utf8(value: None) -> None:
        pass

    @overload
    def utf8(value: bytes) -> bytes:
        pass

    @overload
    def utf8(value: str) -> bytes:
        pass

    def utf8(value):
        pass  # actual implementation
```

```
test.py:9:5: F811 redefinition of unused 'utf8' from line 5
test.py:13:5: F811 redefinition of unused 'utf8' from line 9
test.py:17:5: F811 redefinition of unused 'utf8' from line 13
```

```python
from typing import overload


def do_nothing(func):
    return func


@overload
@do_nothing
def utf8(value: None) -> None:
    pass


@overload
@do_nothing
def utf8(value: bytes) -> bytes:
    pass


@overload
@do_nothing
def utf8(value: str) -> bytes:
    pass


def utf8(value):
    pass  # actual implementation
```

```
test.py:14:1: F811 redefinition of unused 'utf8' from line 8
test.py:20:1: F811 redefinition of unused 'utf8' from line 14
test.py:26:1: F811 redefinition of unused 'utf8' from line 20
```

**Comment by asottile** [comment]
can confirm, thanks for the report -- one of these is easy to fix -- trying to figure out the other one right now :+1:

**Comment by asottile** [comment]
@smoehrle want to try out the branch in #435?

**Comment by smoehrle** [comment]
@asottile Can confirm the fix :) Thanks for the fast response

**Comment by fr0der1c** [comment]
I am wondering... Should the `@overhead` decorator be put below or above other decorators?

PyCharm complains if I put the `@overhead` decorator above other decorators.
![image](https://user-images.githubusercontent.com/16500161/53536856-db061500-3b42-11e9-968a-dfc2eca06d6c.png)

**Comment by asottile** [comment]
I think it ends up not mattering, since you won't ever be calling the `@overload` decorated methods, but the definition below them.

probably a bug that pycharm reports that

https://github.com/python/cpython/blob/4173772031747a9b249be4100b4aa9eda805ea23/Lib/typing.py#L1049-L1084
