### ISSUE TITLE
Detect invalid string escape sequences

### ISSUE THREAD

**Issue by asmeurer** [PyCQA/pyflakes#437]
As of Python 3.6, strings with invalid escapes sequences, like `'\l'` can be set to raise a warning with `python -W:invalid`. The warning is DeprecationWarning, and supposedly they will eventually be a syntax error. 

Unfortunately, I don't think these can be caught in the ast, as it sees `'\l'`, `'\\l'`, and `r'\l'` as the same thing. Meaning the only options are to tokenize the input, or to wrap the `ast.parse` line with a warnings filter. 

Also unfortunately the column position of the error is not reported, and the line number for multiline strings is always the last line (this is a major upstream issue IMO, but it hasn't been addressed), and only one escape error is shown per string. This could be solved by tokenizing the input, but I don't know how that would affect performance.

**Comment by asottile** [comment]
`pycodestyle` detects these fwiw

```console
$ ~/opt/venv/bin/pycodestyle t.py
t.py:1:2: W605 invalid escape sequence '\s'
```

so if you're using `flake8` you already have this available

**Comment by asmeurer** [comment]
I guess pycodestyle does do tokenization, as that's the only way to detect style errors relating to whitespace.

I personally avoid pycodestyle/flake8 because I don't like style warnings. pyflakes is nice because it only warns about actual logical errors. Invalid escapes could be considered a style issue, except for the fact that they are deprecated by the language and are a "future syntax error". So I'd love to see pyflakes support them. I guess the limited support that doing it with ast requires would be OK considering other tooling does it better.

**Comment by asottile** [comment]
you can get what you want out of flake8 via:

```
$ flake8 --select=F,W605 ...
```

that'll just turn on pyflakes + this specific code

**Comment by asmeurer** [comment]
Yes, you've convinced me that flake8 does indeed warn about this error. But this issue is about adding the warning to pyflakes, not flake8.

**Comment by asottile** [comment]
>  and the line number for multiline strings is always the last line (this is a major upstream issue IMO, but it hasn't been addressed)

fwiw I fixed this in python3.8:

```console
$ python3.7 -c 'import ast; n = ast.parse('"'"'"""\n"""'"'"').body[0]; print(n.lineno, ",", n.col_offset)'
2 , -1
$ python3.8 -c 'import ast; n = ast.parse('"'"'"""\n"""'"'"').body[0]; print(n.lineno, ",", n.col_offset)'
1 , 0
```

**Comment by asmeurer** [comment]
That's nice, but now it seems it's always the first line instead of the last. 

```
$python -We:invalid
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:37:09)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.parse("'''\n\\d'''")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/anaconda3/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
SyntaxError: invalid escape sequence \d
```

```
>>> import ast
>>> ast.parse("'''\n\\d'''")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aaronmeurer/Documents/cpython/Lib/ast.py", line 39, in parse
    return compile(source, filename, mode, flags)
  File "<unknown>", line 1
SyntaxError: invalid escape sequence \d
```

Ideally it would give the line (and column) of the actual error. And for the warning, it would warn about all instances.

```
$./python.exe
Python 3.8.0a2+ (heads/master:53b9e1a1c1, Feb 26 2019, 13:34:15)
[GCC 7.3.0] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> '''
... \l
... \p
... '''
<stdin>:1: SyntaxWarning: invalid escape sequence \l
'\n\\l\n\\p\n'
```

**Comment by asmeurer** [comment]
Python 3.8 also appears to make the invalid escapes an unconditional SyntaxWarning. That's good, but there is still the issue (aside from the ones I mentioned above), that it only occurs once, when the file is compiled. That's the case even if you set `-We:invalid` (it would be nice if the -W flag forced recompilation if it matched any warnings that are only found at compile time).

**Comment by asottile** [comment]
fwiw I believe all of those problems are solved in pycodestyle's reporting and imo we shouldn't duplicate that code here

**Comment by asmeurer** [comment]
My suggestion for pyflakes would be about five new lines of code. 

```diff
diff --git a/pyflakes/api.py b/pyflakes/api.py
index 6226e5d..2bd9e9f 100644
--- a/pyflakes/api.py
+++ b/pyflakes/api.py
@@ -8,6 +8,7 @@ import os
 import platform
 import re
 import sys
+import warnings

 from pyflakes import checker, __version__
 from pyflakes import reporter as modReporter
@@ -37,6 +38,8 @@ def check(codeString, filename, reporter=None):
     if reporter is None:
         reporter = modReporter._makeDefaultReporter()
     # First, compile into an AST and handle syntax errors.
+    old_filters = warnings.filters.copy()
+    warnings.filterwarnings('error', 'invalid', DeprecationWarning)
     try:
         tree = ast.parse(codeString, filename=filename)
     except SyntaxError:
@@ -69,6 +72,8 @@ def check(codeString, filename, reporter=None):
     except Exception:
         reporter.unexpectedError(filename, 'problem decoding source')
         return 1
+    finally:
+        warnings.filters = old_filters
     # Okay, it's syntactically valid.  Now check it.
     file_tokens = checker.make_tokens(codeString)
     w = checker.Checker(tree, file_tokens=file_tokens, filename=filename)
```

(actually that reports a column number of `-1`, so that would need to be fixed as well)

If it seems in scope I can send a PR.

**Comment by asottile** [comment]
oh, didn't search the issue tracker but given the resolution in #312 I don't think this will happen

you can however get what you want by running `PYTHONWARNINGS=error pyflakes ...` without needing to write warnings filter code in pyflakes

**Comment by asmeurer** [comment]
> fwiw I believe all of those problems are solved in pycodestyle's reporting and imo we shouldn't duplicate that code here

I don't follow the reasoning here. pyflakes is a dependency of pycodestyle, not the other way around. If we want this functionality, we should 1) decide so on its own merits, and 2) implement it from scratch, since pyflakes should be dependency free. pycodestyle can then reuse pyflakes' implementation if removal of code duplication is desired.

I also don't understand this comment from @sigmavirus24 from #312: 

> especially when it would require a change in the AST that would only be present in CPython 3.8 and onwards (which would make it pretty ineffectual)

I think I showed here that this can be done without using AST analysis, since Python already supports showing the warning natively from `ast.parse`. But even if it only worked in 3.8+, what would be wrong with that? 3.8 isn't going to be an unreleased version of Python forever.

**Comment by asottile** [comment]
pyflakes isn't a dependency of pycodestyle, it's more of a sibling when condsidering flake8 -- my main point is that we shouldn't duplicate efforts here and there, especially when pycodestyle can already do this better than pyflakes ever could given access to the token stream

**Comment by asmeurer** [comment]
Ah sorry I confused the two. 

Still, are pycodestyle and pyflakes the same maintenance team? If we really can't duplicate anything between the two, then anything that can go in pyflakes by scope should. Again, many of us don't care to use tools that aren't pyflakes, or at least don't have pyflakes' philosophy of no style warnings and no false positives.

> especially when pycodestyle can already do this better than pyflakes ever could given access to the token stream

Maybe I'm missing something here too, but is there a limitation of my suggested 5 line patch that can only be remedied by tokenization? https://github.com/PyCQA/pyflakes/issues/437#issuecomment-468015029

**Comment by asottile** [comment]
The problem with that patch is it would hide all other errors in the file since the parse would fail

**Comment by asmeurer** [comment]
It looks like `warnings.catch_warnings` can capture warnings without turning them into exceptions:

```py
>>> with warnings.catch_warnings(record=True) as c:
...     warnings.warn('test')
...     print('testing')
testing
>>> c
[<warnings.WarningMessage object at 0x7f12705b7278>]
```

**Comment by asottile** [comment]
closing given pycodestyle handles this already with access to the token stream
