### ISSUE TITLE
Class-level `TypeVar` resulting in "undefined name" error

### ISSUE THREAD

**Issue by K0Te** [PyCQA/pyflakes#441]
Minimal sample:
```
from typing import TypeVar


class IdClass:
    Y = TypeVar('Y')

    def id(self, x: Y) -> Y:
        return x
```
Result:
```
# pyflakes t.py 
t.py:7: undefined name 'Y'
```

MyPy supports such typing annotations and does not complain about this file.
Probably this issue is related to similar ones #427 and #126

**Comment by Tinche** [comment]
Don't think this is limited to typevars, unions are also affected. A valid program:

```
from typing import Union


class Test:
    Resp = Union[int, str]

    def test(self) -> Resp:
        return 1

```

**Comment by Hanaasagi** [comment]
I found something more interesting.

Following code

```Python
from typing import TypeVar


class IdClass:
    Y = TypeVar('Y')

    def id(self, x: Y) -> Y:
        return x
```

will report `t.py:7: undefined name 'Y'`

But if I defined `Y` in method body, like

```Python
from typing import TypeVar


class IdClass:
    Y = TypeVar('Y')

    def id(self, x: Y) -> Y:
        Y = 2
        return x
```

It will pass.

And if I do not define `Y`

```Python
class IdClass:

    def id(self, x: int) -> Y:
        return x
```

It will report same error twice
```
t.py:3: undefined name 'Y'
t.py:3: undefined name 'Y'
```

I used 2.1.1 Python 3.7.0 on Darwin.
