### ISSUE TITLE
False positive F811 "redefinition of unused" involving imported symbol and class member

### ISSUE THREAD

**Issue by rec** [PyCQA/pyflakes#445]
Was https://gitlab.com/pycqa/flake8/issues/540

The following code gives a false positive "failure.py:10:5: F811 redefinition of unused 'COLORS2' from line 3".  `COLORS2` is not actually being redefined...

    COLORS1 = None
    from colors import COLORS2  # noqa: F401

    class Class:
        def COLORS1(self):
            pass

        def COLORS2(self):
            pass

**Comment by asottile** [comment]
Is this a dupe of #430?

**Comment by rec** [comment]
You're right. I did look at #430 quickly, but I got diverted by the `range` in the subject. Closed!
