### ISSUE TITLE
False positive when method return annotation is an inner class

### ISSUE THREAD

**Issue by bmerry** [PyCQA/pyflakes#446]
This code is valid Python (or at least, both CPython and mypy are happy with it). However, pyflakes 2.1.1 on Python 3.6.6 gives the error `undefined name 'B'` on the return type annotation:

```python
class A:
    class B:
        pass

    def foo() -> B:
        pass
```

Strangely pyflakes is also happy if `B` is used as an argument type annotation - it's only in a return type that it is unhappy.

**Comment by asottile** [comment]
please search the tracker before posting: #427

**Comment by bmerry** [comment]
> please search the tracker before posting

I did but somehow missed that one. I'll close this.
