### ISSUE TITLE
Flake8 warning B010 spurious when inside lambda

### ISSUE THREAD

**Issue by madig** [PyCQA/pyflakes#449]
(I'm assuming flake8's B010 comes from pyflakes)

I have this code snippet: 

```Python
    glyphname = property(
        lambda self: self.name, lambda self, value: setattr(self, "name", value)
    )
```

Flake8 complainst about "B010 Do not call setattr with a constant attribute value, it is not any safer than normal property access". I can't use normal assignment inside a lambda, so this warning is spurious.

**Comment by sigmavirus24** [comment]
It doesn't come from pyflakes

**Comment by jamesbraza** [comment]
@madig there's an open issue within `flake8-bugbear` for this: https://github.com/PyCQA/flake8-bugbear/issues/122
