### ISSUE TITLE
Incorrect position reported for "f-string: empty expression not allowed"

### ISSUE THREAD

**Issue by haqle314** [PyCQA/pyflakes#450]
For example, this is the content of the input file
```
foo = f"""{}
foo"""
```
pyflake doesn't point to the position of `{}`, it instead returns
```
foo.py:2:-1: f-string: empty expression not allowed
foo"""
    ^
```

**Comment by asottile** [comment]
This is a bug in cpython, not pyflakes -- fortunately it is fixed in python3.8 (the ast doesn't properly record the position of triple-quoted-strings) -- see https://bugs.python.org/issue16806:

```python
import ast


with open('t.py', 'rb') as f:
    contents = f.read()
    try:
        ast.parse(contents)
    except SyntaxError as e:
        print(e.args)
```

```console
$ python3.6 y.py
('f-string: empty expression not allowed', ('<unknown>', 2, -1, None))
$ python3.8 y.py
('f-string: empty expression not allowed', ('<unknown>', 1, 7, None))
```

**Comment by asottile** [comment]
found a related (funny) bug in python3.8 while poking at this: https://bugs.python.org/issue37433

**Comment by asottile** [comment]
closing given this is a cpython bug that we can't really do anything about
