### ISSUE TITLE
`__path__` should not be a NameError in `__init__.py`

### ISSUE THREAD

**Issue by glyph** [PyCQA/pyflakes#458]
When defining a package, `__path__` exists at import time as a list, and pyflakes should know that so it doesn't report spurious errors.

**Comment by asottile** [comment]
🤔 this seems to already be the case:

```console
$ echo __path__ > t.py
$ python -m pyflakes t.py
t.py:1:1 undefined name '__path__'
$ mkdir x/
$ echo '__path__' > x/__init__.py
$ python3 -m pyflakes x/__init__.py 
$
```

**Comment by glyph** [comment]
Oh… interesting. Invoking it directly does indeed do the right thing!  I reported the error because I see the squiggly red underline in my editor, but this is apparently a combination of a mypy bug and a flycheck bug; probably it's generating an incorrect temporary file name.

Thanks for checking!
