### ISSUE TITLE
RFE: check for missing comma in list literals containing strings

### ISSUE THREAD

**Issue by mgedmin** [PyCQA/pyflakes#465]
Recently I've found myself making this kind of error:

```python
some_list = [
    'a list'
    'of items',
    'etc.',
]
```

which evaluates to `some_list == ['a listof items', 'etc.']` instead of the expected `['a list', 'of items', 'etc.']`.

It would be nice if pyflakes could warn about this sort of mistake.

**Comment by mgedmin** [comment]
... actually now that I think about it, this can be hard to detect from the AST.

Should I reassign this bug to pycodestyle, which has a tokenizer based checker?  All I care about is that flake8 warns about this.

**Comment by asottile** [comment]
I don't think this belongs in either pyflakes or pycodestyle

pyflakes is intended to be very very low false positive rates (meaning if it gives a lint error, it's almost always soething that needs fixing) and uses the ast

pycodestyle is a set of rules based on pep8, of which I don't believe this is mentioned at all

You'd probably be best to write your own separate linter / flake8 plugin

**Comment by mgedmin** [comment]
Well, this is something that should have very very low false positive rates because if anyone intentionally write string literals like in my original issue description instead of

```python
intentional_multiline_thingy = [
    ('this item'
     'is long and nees to be split'),
    'this item is short',
    'etc.',
]
```

then they should feel bad about it.

PEP-8 being silent on this is why I originally filed a pyflakes bug rather than a pycodestyle bug. The discussion on issue #437 convinced me that it might be appropriate for pycodestyle (PEP-8 is silent on invalid string escapes too)!

Writing my own flake8 plugin does not appeal to me.  I am motivated enough to attempt a pull request to the appropriate flake8 plugin, assuming there is one.

**Comment by asottile** [comment]
"should feel bad about it" and "is always a problem" are very different things

for instance I think this is reasonably readable:

```python
x = [
    'foo'
    'bar',

    'baz',
]
```

**Comment by mgedmin** [comment]
> for instance I think this is reasonably readable:

Let's agree to disagree then.

**Comment by asottile** [comment]
sg2m

**Comment by asmeurer** [comment]
Is pycodestyle still tied to PEP 8 things only? I agree too many people use this intentionally for it to be in pyflakes, but it's also surely something a more opinionated checker should have an opinion on.
