### ISSUE TITLE
F401 when quoting OrderedDict type hint in Union

### ISSUE THREAD

**Issue by dms-cat** [PyCQA/pyflakes#469]
Because of a [mypy issue](https://github.com/python/mypy/issues/7539) I have to quote a type hint like `"OrderedDict[Any, Any]"`. This causes `flake8` to report

> F401 'collections.OrderedDict' imported but unused

*when the quoted type hint is part of a `Union`:*

```text
$ cat t.py
from typing import TYPE_CHECKING, Any, Union


if TYPE_CHECKING:
    from collections import OrderedDict


def t(x: Union[Any, "OrderedDict[Any, Any]"]) -> None:
    pass
$ flake8 t.py 
t.py:5:5: F401 'collections.OrderedDict' imported but unused
$ python --version
Python 3.6.8
$ flake8 --version
3.7.8 (mccabe: 0.6.1, naming: 0.8.2, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.6.8 on Linux
```

Workarounds:

- `from collections import OrderedDict  # noqa: F401`
- Quote the *whole* type hint: `"Union[Any, OrderedDict[Any, Any]]"`

**Comment by asottile** [comment]
are you sure you're using the latest?

```console
$ flake8 --version
3.7.8 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.6.8 on Linux
$ flake8 t.py
$ echo $?
0
```

```python
from typing import Any
from typing import OrderedDict


def t(x: 'OrderedDict[str, Any]') -> None:
    pass
```

**Comment by dms-cat** [comment]
@asottile Yes, but on Python 3.6.

**Comment by asottile** [comment]
can you show a sample file?

**Comment by dms-cat** [comment]
I must've updated the wrong dependencies, because I can't reproduce today. Thank you for the help!

**Comment by dms-cat** [comment]
Clarified – it turns out the problem only manifested when the quoted expression is part of a `Union`.

**Comment by asottile** [comment]
known issue, on phone or I'd find the dupe for ya -- workaround is to quote the entire thing

**Comment by asottile** [comment]
would you like to review the solution in #479 to see if it fixes your problem for you?
