### ISSUE TITLE
F401 (imported but not used) in __init__.py

### ISSUE THREAD

**Issue by crusaderky** [PyCQA/pyflakes#471]
Virtually every medium to large library package I've encountered so far is structured as follows:

- ``impl.py`` defines objects
- ``__init__.py`` imports them, so that the library users don't need to know about ``impl.py``.

At the moment, the ``__init__.py`` modules of packages that use flake8 are littered with either ``# noqa: F401`` on every single line or ``# flake8: noqa`` at the top of the module which blanket disables everything.

This change request is to add a special case in pyflakes that disables F401 (only) when the file name is ``__init__.py``.
An alternative approach would be to add to flake8 the ability to suppress specific errors at module level, e.g. ``# flake8: noqa: F401``.

**Comment by asottile** [comment]
If you list the things you export in `__all__` (a best practice for `__init__.py` files which export names) you will not need to disable anything -- that marks the names as used

**Comment by crusaderky** [comment]
When you have a large amount of objects, it's convenient to define ``__all__`` programmatically, which pyflakes doesn't figure out:

```python
__all__ = tuple(k for k in locals() if not k.startswith("_"))
```

**Comment by asottile** [comment]
sure, I was just giving the suggestion from the duplicate issue #162
