### ISSUE TITLE
Falsely raise F401: imported but unused if forward reference of type annotation does not encapsulate entire type in string literal

### ISSUE THREAD

**Issue by tamias65** [PyCQA/pyflakes#473]
When using pyflakes for type annotation, pyflake recognizes import usage of type in string literals, but only if the entire type declaration is a string literal even thought both are valid forward references.

```
from typing import TYPE_CHECKING, List

if TYPE_CHECKING:
    from a import B

def some_function(arg: 'List[B]') -> None: # This is okay

def some_function(arg: List['B']) -> None: # This raises F401
```

**Comment by asottile** [comment]
dupe #447

**Comment by asottile** [comment]
@tamias65  would you like to review the solution in #479 to see if it fixes your problem for you?
