### ISSUE TITLE
F821 with mypy 0.730 error code ignores

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/pyflakes#475]
The new [mypy 0.730 release](https://mypy-lang.blogspot.com/2019/09/mypy-730-released.html?spref=tw) allows more specific `# type: ignore` annotations such as:

```python
        assert value is not configutils.UNSET  # type: ignore[comparison-overlap]
```

However, this causes pyflakes to complain:

```
qutebrowser/config/websettings.py:96: undefined name 'ignore'
qutebrowser/config/websettings.py:96: undefined name 'comparison'
qutebrowser/config/websettings.py:96: undefined name 'overlap'
```

**Comment by asottile** [comment]
have you tried against master?

**Comment by asottile** [comment]
#455 already fixed this

**Comment by The-Compiler** [comment]
Whoops - just after opening the issue I took a look at the code and found fa92556ca04214fbe292b3d007b34059e8490b5e as well.

Indeed works fine on master, sorry for the noise!

**Comment by ze-phyr-us** [comment]
Hi, I second @Artimi in https://github.com/PyCQA/pyflakes/issues/373#issuecomment-549320632 – please, please, please, release a version 🥺. This has been fixed for three months but nobody can benefit from it unless they install a non-released version from Git which is (rightly) considered bad practice. Thank you so much!

**Comment by asottile** [comment]
we'll release when we're ready 🙏 -- commenting "please release" is one of the least productive (and borderline rude) things you can do on an open source project ;)

**Comment by ze-phyr-us** [comment]
'Borderline rude'? Good heavens, no, that's not at all what I intended. I am sorry if it came out that way. As for 'least productive',... as a user, I just wanted to help by providing feedback that this feature is sought after. Do as you will with that feedback, but it saddens me to hear you consider it unproductive. 

Surely we would call submitting a PR a 'productive' thing. But until there is a release all that was _produced_ by contributors (~17 PRs since 2.1.1) has little usable value.

**Comment by asottile** [comment]
Sorry, it might not be what you intended but it falls into the same category as comments that are like "is this project dead?" "when will someone fix this bug?" etc. etc. -- please remember that the people working on most open source projects are doing it out of their own good will and free time (and _free_ time).  A comment asking for a release is not going to get you a release any faster -- trust us we already know there are unreleased changes on master which will be released eventually!

If you want, you can always install from `git` until a true release is made (`pip install git+https://github.com/pycqa/pyflakes`)

**Comment by ze-phyr-us** [comment]
Thank you for your good will and free time. Please don't waste it any longer on this pointless conversation.

If someone else finds this thread, make sure you pin your dependencies and don't install from Git blindly. `pip install git+https://github.com/pycqa/pyflakes.git@SOME_COMMIT`. For example, to install the latest master as of the time of this comment, `pip install git+https://github.com/pycqa/pyflakes.git@1911c203a13826d2eb03d582d60874b91e36f4fc`.
