### ISSUE TITLE
F811 (redefinition of unused variable) should ignore underscores

### ISSUE THREAD

**Issue by clbarnes** [PyCQA/pyflakes#480]
There is an official convention that underscores are used when you have to assign a variable but you are not going to refer to it again. For example, `[my_queue.get() for _ in range(10)]`, or `c, _ = (a, b)`.

By convention, the entire point of the underscore, therefore, is that it is A) unused, and B) can be redefined without issue. F811 should not be triggered if `_` is redefined.

**Comment by krader1961** [comment]
Note that there is precedent for this. See issue #202; especially my [comment](https://github.com/PyCQA/pyflakes/issues/202#issuecomment-386648451).

**Comment by clbarnes** [comment]
Great! It seems like the feature requested here would increase consistency, then.

**Comment by asottile** [comment]
do you have a sample? the code in the issue doesn't trigger a lint afaik

**Comment by krader1961** [comment]
@clbarnes Your examples also do not trigger the warning for me. Is it possible you're using an old version of pyflakes that does not incorporate my change? From the *NEWS.rst* file it looks like my enhancement was included in the 2.1.0 (2019-01-23) release.

**Comment by clbarnes** [comment]
We're using pyflakes through flake8, and using the most recent version of that (3.7.8). flake8 master depends on pyflakes > 2.1.0, < 2.2.0: the build is using 2.1.1.

The example I'm working with at the moment is a bit of an involved build, but here it is: https://travis-ci.org/catmaid/CATMAID/jobs/597906521 . It installs flake8 at log line 2055 and runs it at 2371.

Apologies if I've missed something.

**Comment by asottile** [comment]
can you paste a minimal code sample?

**Comment by clbarnes** [comment]
Hm, you're right that a minimal example doesn't seem to be triggering it. Weird that the build is. Maybe there's some other version of flake8 floating around in that environment which has snuck into the PATH before the pip installed one.

**Comment by asottile** [comment]
ah so it is coming from this file: https://github.com/catmaid/CATMAID/blob/8c1a4ce36a4f3d10490d3efdf57c90477e466fcb/django/applications/catmaid/control/importer.py#L23

where the `ugettext` import *is unused* -- so I think the error is correct?

**Comment by krader1961** [comment]
If this import exists solely for the side-effects of doing the import that is a gross anti-pattern:

```
from django.utils.translation import ugettext as _
```

As far as I'm concerned that should be flagged as a problem.

**Comment by asottile** [comment]
I don't think it's even for side-effects there, conventionally gettext is implemented as `_` and then used as `_('string literal')` -- just in this case the import was unused entirely :)

**Comment by clbarnes** [comment]
Thanks for getting to that before I did! It is indeed a convention for internationalisation stuff. I was focusing on the redefinition line rather than the original definition.

Anyway, it looks like this is a problem on our end. Thanks for your quick responses!
