### ISSUE TITLE
Broken walrus support

### ISSUE THREAD

**Issue by canassa** [PyCQA/pyflakes#481]
Hello, 

The latest release of pyflakes doesn't seem to support the walrus operator at all:

```
"pyflakes" failed during execution due to "'FlakesChecker' object has no attribute 'NAMEDEXPR'"
```

I tried to install the master version but it still doesn't work properly:

```
models.py:309:66: E231 missing whitespace after ':'
        biocompatible = {m.name: "" for d in data["items"] if (m := d["material"]).biocompatible}
```

**Comment by asottile** [comment]
E231 is not pyflakes, that's [pycodestyle](https://github.com/pycqa/pycodestyle)

#457 fixed the first error (which is already on master)
