### ISSUE TITLE
python 3.8 SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by zzzeek** [PyCQA/pyflakes#483]
Hi there -

I searched a bit for this but couldn't find it.   This is a warning generated by Python 3.8 and I think it's new.  It's very hard to get pytest to raise for this, so it would be better if it were in pyflakes / flake8.

demo:

```
"""test a syntax warning."""

x = 5

if x is ():
    print("hi")

```

```
$ /opt/python3.8/bin/python3 -m py_compile test.py
test.py:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if x is ():

```

**Comment by asottile** [comment]
pycodestyle already has this. if you're using flake8>=3.7 you should have this

**Comment by zzzeek** [comment]
OK what am I doing wrong:

```
$ /opt/python3.8.0a4/bin/python3 -m flake8 --version
3.7.8 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.8.0a4 on Linux
[classic@photon2 ~]$ /opt/python3.8.0a4/bin/python3 -m flake8 test.py 

```

**Comment by asottile** [comment]
:thinking: 

```console
$ flake8 --version
3.7.8 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 3.6.8 on Linux
$ flake8 /dev/stdin <<< $'x = 5\nx is 5'
/dev/stdin:2:1: F632 use ==/!= to compare str, bytes, and int literals
```

**Comment by asmeurer** [comment]
See https://github.com/PyCQA/pyflakes/issues/437. I still think pyflakes should print warnings for things that give syntax warnings in the interpreter.

**Comment by zzzeek** [comment]
> ```
> flake8 /dev/stdin <<< $'x = 5\nx is 5'
> ```

@asottile  that's....not the same code

```
# your example
[classic@photon2 ~]$ flake8 /dev/stdin <<< $'x = 5\nx is 5'
/dev/stdin:1:1: D100 Missing docstring in public module
/dev/stdin:2:1: F632 use ==/!= to compare str, bytes, and int literals

# code that python 3.8 py_compile emits SyntaxWarning for
[classic@photon2 ~]$ flake8 /dev/stdin <<< $'x = 5\nx is ()'
/dev/stdin:1:1: D100 Missing docstring in public module

```

**Comment by zzzeek** [comment]
@asmeurer  I don't know about your suggestion that pyflakes should catch the warnings directly, for one thing that means I have to run flake8 in the correct Python interpreter to get the warnings which is a bit inconvenient sometimes.    It should just be another "F" rule, this can't be that hard to do.   should I just write a custom extension ?

**Comment by asottile** [comment]
oh I see now, yeah I'm wrong about pycodestyle. it seems that pyflakes should also handle tuple literals in this check, should be an easy extension

**Comment by asmeurer** [comment]
These are definitely easy to add direct tests for. But pyflakes already requires the same Python interpreter version for syntax errors (like 2 vs. 3 stuff).

**Comment by asmeurer** [comment]
Also pyflakes already has the `assert tuple` syntax warning built in. I don't know if there are other syntax warnings out there (other than the bad string escapes) that should be added as well.

**Comment by zzzeek** [comment]
Oh please make it a separate code, SQLAlchemy ignores the existing code because we use '== None' in SQL expressions

**Comment by asmeurer** [comment]
I don't think `is None` vs. `== None` is part of this. Both are correct and neither raise a syntax warning. "Literal" here means specifically a string or integer literal.

**Comment by asottile** [comment]
@zzzeek can you try out the branch in #484 (and possible review the code as well) -- thanks!

**Comment by smdelacruz** [comment]
Having the same issue since Python 3.8 upgrade.

**Comment by asottile** [comment]
@smdelacruz please review / try out #484 and then we can get it into the next pyflakes!

**Comment by sh138** [comment]
same error now what to do

**Comment by asottile** [comment]
@sh138 can you provide more information? what are you running and what are you seeing?

**Comment by raju10101997** [comment]
Try
pip install pyflakes
