### ISSUE TITLE
user manual

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [PyCQA/pyflakes#492]
It would be really nice to have a user manual.

**Comment by asottile** [comment]
Just curious, what would you like that's more than the current [README](https://github.com/pycqa/pyflakes) or the output of `pyflakes --help`?

**Comment by Phillip-M-Feldman** [comment]
Hello Anthony,

I made the mistake of typing `pyflakes` without any options, and it simply
sat there doing nothing until I killed it off.

When I run `pyflakes --help`, here's what I see:

Usage: pyflakes-script.py [options]

Options:
  --version   show program's version number and exit
  -h, --help  show this help message and exit

Are there really no other options?  What types of checks does `pyflakes`
do?  Is there any mechanism for disabling any specific checks that one
might not want?

Phillip

**Comment by asottile** [comment]
with no arguments it reads from `stdin` (mostly, I think, for editor configuration)

It indeed doesn't have any options or ways to disable checks -- you probably want `flake8` if you want those features

**Comment by bitglue** [comment]
Here's why pyflakes doesn't have much of a manual:

![image](https://user-images.githubusercontent.com/1232472/70100838-f200f880-15e7-11ea-9ccc-1356bc5415ee.png)
https://xkcd.com/1343/

> Are there really no other options?

What options would you want?

> What types of checks does `pyflakes` do?

See [messages.py](https://github.com/PyCQA/pyflakes/blob/master/pyflakes/messages.py) or see [the tests](https://github.com/PyCQA/pyflakes/tree/master/pyflakes/test) for code examples.

> Is there any mechanism for disabling any specific checks that one might not want?

No. According to the [design principles in the README](https://github.com/PyCQA/pyflakes#design-principles), pyflakes "will never complain about style, and it will try very, very hard to never emit false positives." So if pyflakes was emitting errors that people often wanted to disable, this would be a design flaw in pyflakes.

Are there some checks you want to disable?

Reading from stdin in the absence of options is a fairly common thing for a command-line program to do. For example, `wc`, `cat`, `sort`, `uniq`, `awk`, `sed`, `cut`, and `tar`. If you'd like, documenting this behavior in the `--help` output would be a welcome PR.

**Comment by asmeurer** [comment]
Surely the --help output could actually include a description.
