### ISSUE TITLE
Warning for redefined functions

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/pyflakes#493]
I often find myself installing Pylint for the sake of a single check:  
```
pylint --score=no --disable=all --enable=function-redefined .
```

While I generally prefer the flake8 ecosystem, it doesn't catch the occasional problem of someone copy-pasting a test, changing it, and forgetting to change the name.  Unfortunately `pytest` doesn't catch this either, because the name is simply redefined and the first use forgotten.

I don't think this needs to be too complicated - something like the existing redefined-name (`F811`) warning would be plenty 😄

**Comment by asottile** [comment]
Do you have an example?

```console
$ ~/opt/venv/bin/pyflakes t.py
t.py:2: redefinition of unused 'f' from line 1
t.py:6: redefinition of unused 'g' from line 5
$ cat t.py 
def f(): ...
def f(): ...

class C:
    def g(): ...
    def g(): ...
```

**Comment by Zac-HD** [comment]
Welp... it seems to be a configuration problem somewhere, since I can't reproduce it once I move the file to a clean directory 😓

**Comment by asottile** [comment]
no problem! cheers 🎉
