### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bmerry** [PyCQA/pyflakes#494]
It looks like there have been a lot of bug fixes since the last release in February. Are there any plans to create a new release?

In my case the issue is #427, which I've been working around for now by pinning an older version (before the bug was introduced), but the older version doesn't work with Python 3.8. I'm sure everyone has their own favourite issue though.

**Comment by asottile** [comment]
Usually we try and time these with releases of pycodestyle + flake8 so they can all go out around the same time.

Currently flake8 is in the middle of a pretty large configuration refactor and isn't really ready for the 3.8 release.

I'd also like to see a few more changes in pyflakes merge before we cut a release, for example: #479 #484 #485 #490

**Comment by bmerry** [comment]
Ok thanks for the explanation.
