### ISSUE TITLE
Improper Handling of the PEP 515 Extension

### ISSUE THREAD

**Issue by evarga** [PyCQA/pyflakes#495]
pyflakes reports an `invalid syntax` error when it encounters a code containing PEP 515 stuff. For example, the next valid line will trigger an error:

`amount = 10_000`

**Comment by asottile** [comment]
cannot reproduce, make sure you're using the latest version and have pyflakes installed to a 3.6+ interpreter:

```console
$ cat t.py 
1_000
$ ~/opt/venv/bin/pyflakes t.py
$ ~/opt/venv/bin/pyflakes --version
2.1.1 Python 3.6.8 on Linux
```
