### ISSUE TITLE
F821 false positive for type aliases

### ISSUE THREAD

**Issue by ammen99** [PyCQA/pyflakes#496]
Testing this with Pyflakes 2.1.1 installed from pip and python 3.8.

Consider the following snippet:
```
class A:
    B = int

    def get(self) -> B:
        return 1
```
Python accepts it and writing a small test `print(A().get())` returns `1`. MyPy also does not detect any errors. So I think this must be a bug in pyflakes.

**Comment by asottile** [comment]
this is fixed on master by #448

```console
$ python3 -m pyflakes t.py
$ cat t.py
class A:
    B = int

    def get(self) -> B:
        return 1
```
