### ISSUE TITLE
how do I use pep484 type hints in Python 2 while also catching for F821?

### ISSUE THREAD

**Issue by zzzeek** [PyCQA/pyflakes#501]
hey there, SQLAlchemy guy here, I just need to know how I'm supposed to handle this.

I want to enable F821 in the codebase.   But in a few places I have a pep484 type hint, written as a comment because this codebase is still supporting Python 2, like this:

```
    def self_group(self, against=None):
        # type: (Optional[Any]) -> Union[Grouping, TextClause]
        if against is operators.in_op:
            return Grouping(self)
        else:
            return self

```

it's just a comment, so hooray, who can possibly complain about that?   but it looks like pyflakes has gone through all the trouble of policing these:

```
./lib/sqlalchemy/sql/elements.py:1883:9: F821 undefined name 'Optional'
        # type: (Optional[Any]) -> Union[Grouping, TextClause]
        ^
./lib/sqlalchemy/sql/elements.py:1883:9: F821 undefined name 'Any'
        # type: (Optional[Any]) -> Union[Grouping, TextClause]
        ^
./lib/sqlalchemy/sql/elements.py:1883:9: F821 undefined name 'Union'
        # type: (Optional[Any]) -> Union[Grouping, TextClause]
        ^

```

I can't define Optional, Any, or Grouping because there's no "typing" module in Python 2!   

Per [pep484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code):

"Tools that support this syntax should support it regardless of the Python version being checked. This is necessary in order to support code that straddles Python 2 and Python 3."

it of course also says this:

"Like other type comments, any names used in the annotations must be imported or defined by the module containing the annotation."

so....maybe this is not a flake8 problem but how on earth are type comments supposed to be useful if the most fundamental elements of the typing system like Any, Optional etc. are required to be imported but aren't available in Python 2 ?

**Comment by asottile** [comment]
for python 2 (and so you can use type comments with mypy) you'd install the `typing` backport and import it as usual

**Comment by asottile** [comment]
here's an example [from flake8 itself](https://gitlab.com/pycqa/flake8/blob/20906d43046096c31dfcd9b8bc536dbd21f043ef/setup.cfg#L48)

**Comment by zzzeek** [comment]
> for python 2 (and so you can use type comments with mypy) you'd install the `typing` backport and import it as usual

so this means that SQLAlchemy has to add a dependency (we've gone for about 15 years with zero) so that we can have **comments** of a particular syntax in the codebase.   I get that this is pep484 but this basically means I will remove all pep484 comments from SQLAlchemy and I can't work on them at all until we are fully python 3 only in a year or so.

**Comment by zzzeek** [comment]
or I can just make a fake stub library in compat, I guess.   thanks for your help.

**Comment by asottile** [comment]
you can also use the deferred typing imports:

```python
if False:  # in python3.5.3+ use `from typing import TYPE_CHECKING` and `if TYPE_CHECKING:`
    from typing import ...
```

**Comment by zzzeek** [comment]
yeah I considered that too....but flake8 would figure that one out correctly?    so far "sqlalchemy.util.typing" seems to be simple enough.

**Comment by asottile** [comment]
yep! pyflakes doesn't do branch analysis so it doesn't know it's any different -- this is also what mypy suggests for other similar situations (py2 / circular imports / etc.)

**Comment by zzzeek** [comment]
that's great too because those imports are not flagged as unused imports too!   will go with that.

**Comment by bsolomon1124** [comment]
@asottile thanks for this gem. I'm unable to find mention of `if False` in https://www.python.org/dev/peps/pep-0563/ (just `typing.TYPE_CHECKING`).  Do you know of a canonical reference for how the `if False` is actually handled by mypy and the like?

**Comment by asottile** [comment]
- https://github.com/python/mypy/issues/3216
- https://github.com/python/typing/issues/230
- https://stackoverflow.com/q/59615062/812183

just a few -- I googled `"mypy" "if False"`
