### ISSUE TITLE
Erroneous "undefined name" error on un-imported quoted type annotation

### ISSUE THREAD

**Issue by andrewminer** [PyCQA/pyflakes#502]
I'm working on a pair of classes which each import the other.  For example, perhaps I have a file `alpha.py`:
```python
class Alpha(object):
    
    def some_method(self, value: "Bravo"):
        ....
```
and another file, `bravo.py`:
```python
from .alpha import Alpha

class Bravo(object):

    def some_method(self, value: Alpha):
        ...
```

In this example, I've chosen to import `Alpha` into `bravo.py`, which, of course, means I can't import `Bravo` into `alpha.py`.  However, pyflakes is giving me an error in `alpha.py` saying: "undefined name 'Bravo'`.  I've read through the other open issues (and a good many of the closed ones), and I don't see anything else reported for this particular problem.

My versions:
```
> pyflakes --version
2.1.1 Python 3.7.4 on Darwin
```

**Comment by asottile** [comment]
this is in line with pep 484 

if you need a forward annotation for a circular import which is compatible with pep 484 add the import in an `if TYPE_CHECKING:` block (`if False:` if you need to support python 3.5.0-3.5.2)

**Comment by andrewminer** [comment]
Got it.  Thanks!
