### ISSUE TITLE
Undefined Name for return annotation defined in class

### ISSUE THREAD

**Issue by nielsbuwen** [PyCQA/pyflakes#506]
Consider this code:

```python
class Class:
    xyz = 1

    def f(self, x) -> xyz:
        pass
```

The variable `xyz` is defined inside the class and used as a return annotation in a method.

`pyflakes` reports this as an error (`flake8` too, but i hope this is the correct repo to report it?)

> file.py:4: undefined name 'xyz'

However this runs successfully with `python3.6` `python3.7` `python3.8`. The correct behaviour would be not to report anything here.

_In case you are interested: This is my use case:_

```python
from typing import TypeVar, Generic

T = TypeVar('T')


class MyClass(Generic[T]):
    Self = TypeVar('Self', bound='MyClass[T]')

    def copy(self: Self) -> Self:
        return self  # implementation omitted


reveal_type(MyClass[int]().copy())  # Revealed type is MyCass[int]
```

So `mypy` accepts this and `python` also accepts this.

**Comment by sigmavirus24** [comment]
> `pyflakes` reports this as an error (`flake8` too, but i hope this is the correct repo to report it?)

This is the correct repository to report it.

**Comment by asottile** [comment]
dupe #441 -- please try against master
