### ISSUE TITLE
Cut a new release?

### ISSUE THREAD

**Issue by pipermerriam** [PyCQA/pyflakes#509]
It appears there has not been a release since February 28th, 2019, almost a full year ago.

https://pypi.org/project/pyflakes/#history

I'm specifically running into an issue which was fixed here: https://github.com/PyCQA/pyflakes/pull/455

I'm curious if the maintainers are around and able to cut a new release or if there is anything I can do to assist in making this happen such as compiling release notes?

**Comment by asottile** [comment]
here's the current status: https://github.com/PyCQA/pyflakes/issues/494#issuecomment-561303887

if you'd like to help, reviewing open PRs helps a lot!

**Comment by pipermerriam** [comment]
Thank you.  I searched but failed to find that issue.
