### ISSUE TITLE
Spurious 'unused import' in conjunction with quoted generic stub types

### ISSUE THREAD

**Issue by jnsnow** [PyCQA/pyflakes#515]
This one's a mouthful, but I did verify that this is still an issue with 2.1.1-23-g0af480e -- current master as of writing.

Consider this example:

```python
from __future__ import annotations
from os import PathLike
from typing import Union

_PathType = Union[str, 'PathLike[str]']

def foo(arg: _PathType) -> str:
    return str(arg)
```

First, note that `PathLike[str]` is a case where MyPy uses a Generic type stub, but that the runtime object here is not subscriptable. In these cases, such types *must* be string quoted, even when using delayed annotations support from PEP 563.

See here for more information on this circumstance:  https://mypy.readthedocs.io/en/stable/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

The warning produced is:
```
example.py:2:1 'os.PathLike' imported but unused
```

Next, even when moving this import below a TYPE_CHECKING stanza, pyflakes still warns.

Lastly, this is an error in pylint (https://github.com/PyCQA/pylint/issues/3299) and pycharm (As of 2019.3.2) as well. Worse, each tool has separate pragmas to silence the error.

This error appears related to #247 but that was about PEP 484 type hint *comments*, not string quoted type hints. The issue is *possibly* distinct from #510 because PEP 563 delayed annotations have no effect here: quoted types are a requisite; but these two reports may share a root cause. Pull #479 does not resolve this problem.

Hopefully that's good homework. :)
--js

**Comment by asottile** [comment]
https://github.com/PyCQA/pyflakes/issues/510#issuecomment-586426576 includes this problem as well -- will probably solve both of them at the same time 👍 

thanks for the thorough issue (let's continue the discussion there!)
