### ISSUE TITLE
The Next Release (pyflakes 2.2.x)

### ISSUE THREAD

**Issue by asottile** [PyCQA/pyflakes#520]
:wave: I'd like to organize the next release of pyflakes

I'll be pinning this issue and collecting feedback on things that should end up in this release

Due to the number of contributions that have gone into `pyflakes` since the last release, I'm planning to do this as `2.2.0a1` first (an alpha pre-release) -- this should hopefully expand the number of people trying the release (though I suspect not all that many will use the alpha still)

___

How you can help:

- try out the latest master on your repositories: `pip install --force-reinstall git+https://github.com/pycqa/pyflakes`
- review [open PRs](https://github.com/PyCQA/pyflakes/pulls)

**Comment by asottile** [comment]
I'd especially like to see the following land before release: #517, #516, #512, #511 -- though reviewing open PRs helps us a ton!  (pyflakes operates with dual-signoff)

**Comment by psandana** [comment]
Please add #448

**Comment by asottile** [comment]
@psandana that's already in master so of course it'll be included

**Comment by asmeurer** [comment]
What is the general release cadence for pyflakes and what is the timeline for getting things into this release?

**Comment by asottile** [comment]
> What is the general release cadence for pyflakes and what is the timeline for getting things into this release?

- there hasn't really been a release cadence -- on average pyflakes releases a minor release ~about once a year
- there isn't really an urgency to releasing this so no deadlines currently (though I do want to at least see those above changes land before we cut one)

**Comment by Tinche** [comment]
```pip install --force-reinstall git+https://github.com/pypa/pyflakes``` is incorrect, it should be ```pip install --force-reinstall git+https://github.com/PyCQA/pyflakes```

**Comment by asottile** [comment]
derp, thanks -- pip on the brain 🤦‍♂

**Comment by asottile** [comment]
I've put together a changelog for 2.2.0a1 in #524

**Comment by samuelcolvin** [comment]
Would be great to get this released ASAP.

> there isn't really an urgency to releasing this

I disagree. pyflakes is currently incompatible with (arguably) the number 1 headline feature of the latest version python, that was fixed in #457 8 (!!!) months ago. 

AFAIK you currently have the options of disabling linting or not using walrus operators. 

I therefore think a release is very urgent.

---

Sorry to nag and sound negative, pyflakes is great and I know how thankless maintaining OS libraries like this can be. Thank you all for your hard work.

**Comment by samuelcolvin** [comment]
Please could someone explain why my comment was marked as "off-topic"?

You may disagree with it, but it is absolutely not off-topic - it relates directly to the the subject of this issue.

**Comment by asottile** [comment]
it's spam, please use the reactions (+1/etc.) -- there's also an example of how to upgrade to the latest git version in the original post so you're not blocked

**Comment by asmeurer** [comment]
@asottile it's *very* disappointing to see this sort of behavior on a project this important. You and the other maintainers should strongly consider adding a code of conduct to this repo and following it.

**Comment by asottile** [comment]
@asmeurer please clarify which behaviour is disappointing, we're trying to make a release as fast as possible and comments "release faster" are not helpful to getting that done.  everything is in place within my power to get that out as fast as possible and we're all currently waiting.

**Comment by asmeurer** [comment]
Censoring comments, calling things "spam" and "off topic" when they aren't, and being rude in general. @samuelcolvin even went out of his way to thank you for your work. 

I'm hopeful this is just one of those "you're having a bad day" situations. I would suggest stepping back and revisiting this tomorrow when you can get a fresh look at what happened here. 90% of the time this sort of thing can be resolved amicably simply by taking some time to let things cool off.

**Comment by asottile** [comment]
alright well the whole reason I made this issue here was to stop the "please make a release comments" so that people can come to a place and see exactly what the status of that is.

[claiming that a release is urgent and nagging](https://github.com/PyCQA/pyflakes/issues/520#issuecomment-603997743) (as the sorry indicates) is precisely what I wanted to prevent by making this issue :(  commenting to that effect does not help the situation and it doesn't help anyone make the release faster.  

there is no censorship -- or at least that was not the intention.  I hid the comments to keep the discussion about the release (I didn't edit or delete them -- I agree that would be censorship!)

 when github added the reactions feature I think that's one of the best things that's come out of github's feature department in a long time because it greatly reduces the "+1", "I have this issue too", etc. type comments which are a nuisance.

I'll take another fresh look at this tomorrow but I suspect you're _interpreting_ my behaviour as rude, I'm not trying to hurt anyone here, just trying to keep this conversation on topic, civil, and helpful without outside individuals having to sift through the noise. 

___

the most useful information I can give at this time has already been given [in a comment above](https://github.com/PyCQA/pyflakes/issues/520#issuecomment-600685295), we're ready to try and make the next alpha release but it needs someone with pypi permission to do so

**Comment by asottile** [comment]
2.2.0 has been released 🎉

**Comment by PeterJCLaw** [comment]
@asottile thanks for organising this and getting it out :)

Should there be a tag for this release in the repo?

**Comment by asottile** [comment]
I just tagged the release, should be present now -- thanks for the pointer @PeterJCLaw !

**Comment by asottile** [comment]
for those looking for a flake8 release containing this, I've put up 3.8.0a2 a few days ago which enables this (still an alpha as we're taking a more cautious rollout of both pycodestyle and flake8)

try it out with either `pip install --pre --upgrade flake8` (or if you're using pre-commit: `pre-commit autoupdate`)

**Comment by flamableconcrete** [comment]
@asottile: you are my hero! I just saw this and moved to using `flake8==3.8.0a2` and I am SO HAPPY that I can lint my python 3.8 walrus operators now!

Feel free to mark this as off topic too, BTW since it isn't directly related to the release, I just wanted to say thank you!

**Comment by brettcannon** [comment]
@asottile is there a reason why pyflakes 2.2.0 doesn't list Python 3.8 support but flake8 3.8.0a2 does? Or do you just need a PR to add Python 3.8 to CI, classifiers, and README for pyflakes?

**Comment by asottile** [comment]
seems a simple oversight, nothing tests the classifiers

**Comment by brettcannon** [comment]
@asottile OK, then I'll try to get you a PR this week.
