### ISSUE TITLE
Nested functions

### ISSUE THREAD

**Issue by cerealkill** [PyCQA/pyflakes#526]
```py
    def report_success():
        ...

    def report_failure():
        ... 
       str(err)

    for i in range(0, 10):
        try:
            rpc_request = {
                ...
            }
            response = requests.post(**rpc_request)
            response.raise_for_status()
            report_success()
        except requests.exceptions.RequestException as err:
            report_failure()
        except requests.exceptions.SSLError as err:
            report_failure()
        except Exception as err:
            report_failure()
```
I get:
```
asd.py:99: [E] E0602 undefined name 'err' [pyflakes]
asd.py:112: [W] W0612 local variable 'err' is assigned to but never used [pyflakes]
```

Is it possible to fix?

**Comment by asottile** [comment]
this is a tricky one for pyflakes -- the `err` name is only defined inside the except block and so pyflakes assumes any code outside of the except block cannot reference that name (as an except block ~effectively has a `del err` at the end of it

you'd probably be best to refactor the code to pass the exception as an argument

you'll see a similar case for:

```python
def f():
    def g():
        print(a)

    a = 1
    g()
    del a
```

**Comment by cerealkill** [comment]
Yeah, I get it, but this is perfectly sound Python. 

PyCharm lints it correctly, for example, and can identify when the variable doesn't exist.

The beauty of Python and nested functions is to make the code easy to read. The refactored code is not that elegant anymore. I still believe it is worth the shot to fix this.

**Comment by sigmavirus24** [comment]
> The refactored code is not that elegant anymore, has "loose" functions that only serve the purpose of the that big function.

I think "clever" is a better word than "elegant". The refactored code that passes in the `err` value explicitly is (in my opinion) clearer because it is less clever.  I'm also a little shocked that the code you have even works on Python 3.

**Comment by asottile** [comment]
you can still do this with nested functions -- I'm just suggesting adding a parameter to your nested function -- and arguably taking arguments in functions will make them _more_ readable since you won't have to hunt for what variables are being used in closure (especially *after* the function definition)

**Comment by cerealkill** [comment]
Ok, I agree with that adding the parameter to the function will make it easier to read, even if it works without. :)

**Comment by asottile** [comment]
this duplicates #265
