### ISSUE TITLE
f-strings incorrectly marked as syntax error

### ISSUE THREAD

**Issue by hamdav** [PyCQA/pyflakes#527]
I am not sure whether this is a problem I should post here or on the vim-flake8 GitHub but I think it belongs here. 
I am running vim on a mac with syntastic and vim-flake8 installed (via vim-plug) and whenever I write something like `print(f"The value of x is {x}")` it says that it is a syntax error.

**Comment by sigmavirus24** [comment]
What version of Python is flake8/pyflakes running on? f-strings are syntax errors on older versions of Python. Also there's not enough information here to help if this were a bug in pyflakes because you haven't given us the pyflakes version of python version

**Comment by hamdav** [comment]
Sorry, I think this was caused by me not realizing that there was a mismatch between versions of syntax checkers and the python I was coding in.
