### ISSUE TITLE
F821 when using cls as a function return type

### ISSUE THREAD

**Issue by SylannBin** [PyCQA/pyflakes#528]
I reuse the template for a flake8 issue because I really encounter this problem with flake8.
But flake8 says we should report the issue where it belongs, so here it goes.

---
*Please describe how you installed Flake8*

```
$ pip install flake8
```

---
*Please provide the exact, unmodified output of `flake8 --bug-report`*

```json
{
  "dependencies": [
    {
      "dependency": "setuptools",
      "version": "40.6.2"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "3.7.2",
    "system": "Darwin"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.4.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.0.0"
    }
  ],
}
```
  
---
*Please describe the problem or feature*
*If this is a bug report, please explain with examples (and example code) what you expected to happen and what actually happened.*

flake8 (pyflakes) reports that `cls` is undefined in the following code example:

```py
class SomeClass:
    def __init__(self, whatever):
        self.what = whatever

    @classmethod
    def from_something(cls, whatever) -> cls:
        return cls(whatever)
```

When running `python3 -m flake8 path/to/file.py`, I receive the following error message:
`F821 undefined name cls`

Same behavior with the quotes: `'cls'`.

**EDIT**: ~~The intellisense of vscode understands the return type of this classmethod~~ (but it does so without the return type as well, so not really relevant)
since cls is almost like a keyword, maybe it should not be considered undefined in this case.

---
This is somewhat similar to [#259](https://github.com/PyCQA/pyflakes/issues/259).
However I think it is not the same problem.

**Comment by asottile** [comment]
that code isn't valid according to PEP484, mypy also agrees:

```console
$ mypy t.py
t.py:8: error: Name 'cls' is not defined
t.py:11: note: Revealed type is 'Any'
Found 1 error in 1 file (checked 1 source file)
```

(the `reveal_type` on line 11 is showing what mypy thinks of this)

___

from pep 484:

[acceptable type hints](https://www.python.org/dev/peps/pep-0484/#acceptable-type-hints)

> Annotations must be valid expressions that evaluate without raising exceptions at the time the function is defined (but see below for forward references).


[forward references](https://www.python.org/dev/peps/pep-0484/#forward-references)

> When a type hint contains names that have not been defined yet, that definition may be expressed as a string literal, to be resolved later.

**Comment by asottile** [comment]
I believe the correct type-annotated code for that is:

```python
class SomeClass:
    def __init__(self, whatever):
        self.what = whatever

    @classmethod
    def from_something(cls, whatever) -> 'SomeClass':  # or use the bare name if you are py37+ and using `from __future__ import annotations`
        return cls(whatever)
```

**Comment by SylannBin** [comment]
Yeah but this solution does not handle inheritance.
Anyway...

**Comment by asottile** [comment]
perhaps this instead? (but this is admittedly a little bit of an odd case to have a factory function outside of `__init__` that's "generic" on it's child subclasses)

```python
from typing import Type
from typing import TypeVar

TBase = TypeVar('TBase', bound='Base')


class Base:
    def __init__(self, s: str) -> None:
        self.s = s

    @classmethod
    def make(cls: Type[TBase], s: str) -> TBase:
        return cls(s)


class C(Base):
    pass

reveal_type(Base.make('s'))  # revealed type is t.Base*
reveal_type(C.make('s'))  # revealed type is t.C*
```

**Comment by SylannBin** [comment]
Thanks for taking the time to put this answer together. I had already seen this solution from Guido VR, but that is way too complex.
For the record, I don't think it's an edge case to have a factory method be consistent across inheritance, since subclasses could differ in both structure and behaviour and still have the same init signature.
But anyway thanks for your time.

**Comment by asottile** [comment]
feel free to reach out to [typing-sig](https://mail.python.org/mailman3/lists/typing-sig.python.org/) to discuss further -- we don't really manage how PEP 484 is designed / specified, we just implement a linter that's compatbile with it

**Comment by yasirroni** [comment]
How if the convetion of the repository is not using type hint?

```
class SomeClass:
    def __init__(self, whatever):
        self.what = whatever

    @classmethod
    def from_something(cls, whatever):
        return cls(whatever)
```

It still say that cls is undefined. What is the solution?

**Comment by asottile** [comment]
that code doesn't produce an error -- if it's not type annotation related then this isn't the right issue -- perhaps open a new issue with a more specific reproduction?

**Comment by yasirroni** [comment]
My bad, I miss read the location of `cls`. It is called from non-classmethod, so pyflakes work as intended. My bad.
