### ISSUE TITLE
(flake8) Use of exclude clause on windows results in 5k files to check!

### ISSUE THREAD

**Issue by guidoavvisati** [PyCQA/pyflakes#536]
Running python 3.7.7 on windows 7 with a virtual environment. I installed flake8 and configured it via tox.ini as per below
```
[flake8]
exclude =
    .git,
    *migrations*
max-line-length = 88
max-complexity = 8
ignore = F401
```
Without the exclude clause, it runs on the code base in few seconds. When I switch on the exclude clause, it wants to check some 4900ish files.

**Comment by asottile** [comment]
this is the wrong repository, you want https://gitlab.com/pycqa/flake8

that said, the way `exclude` works is if you specify it it overrides the default `exclude` which is `.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg`

you probably want to use `extend-exclude` which is available in flake8>=3.8.0a2
