### ISSUE TITLE
Undefined name '__builtin__'

### ISSUE THREAD

**Issue by OverLordGoldDragon** [PyCQA/pyflakes#538]
Migrated from [Spyder 4.1.2](https://github.com/spyder-ide/spyder/issues/12585): `__builtins__` isn't flagged, but `__builtin__` is also a default in `__main__`'s global namespace. While it isn't defined in non-main modules, the red flag does remain a false positive in `__main__`. Is this intended?

![image](https://user-images.githubusercontent.com/16495490/80908376-717a2b80-8d30-11ea-822d-3f051bc44423.png)

**Comment by sigmavirus24** [comment]
We need more context than what you've provided here. What version of pyflakes are you using? Can you give us _real_ example code to debug this? What version of Python are you using? etc.

**Comment by OverLordGoldDragon** [comment]
pyflakes 2.1.1, Spyder 4.1.2, Python 3.7.5. There isn't much to "debug", really - the problem is reproducible by typing `__builtin__` in any file, but it happens to be defined in `__main__`, making it a false red flag:

![image](https://user-images.githubusercontent.com/16495490/80965052-fb0a2600-8e22-11ea-9533-e255c15554f2.png)

**Comment by sigmavirus24** [comment]
Can you reproduce this with _just_ pyflakes? And can this be reproduced with pyflakes 2.2.0 (the latest release on PyPI)?

I'm also not sure what you mean _exactly_ by `__main__` do you mean `__main__.py` or a script where you're doing something else? There's no clear `__main__` in your screen shots which are not searchable, and are not understandable or readable by developers using screen readers. Please give us an example file on which running `pyflakes thefile.py` gives the false positive

**Comment by OverLordGoldDragon** [comment]
@sigmavirus24 Reproduced w/ 2.2.0 via terminal; [demo.mp4](https://puu.sh/FGaqf/4ff5171568.mp4)

**Comment by sigmavirus24** [comment]
I can't play that video. Can you just copy and paste the text (the stuff that's actually accessible)?

**Comment by OverLordGoldDragon** [comment]
![image](https://user-images.githubusercontent.com/16495490/80992297-5b608e00-8e4a-11ea-9cfe-8bad0b4d2052.png)

**Comment by asottile** [comment]
I don't think this issue is valid, `__builtin__` is only a thing in _interactive_ mode:

```console
$ pyflakes --version
2.2.0 Python 3.8.2 on Linux
$ cat t.py
__builtins__
__builtin__
$ pyflakes t.py
t.py:2:1 undefined name '__builtin__'
$ python3 t.py
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    __builtin__
NameError: name '__builtin__' is not defined
```

**Comment by OverLordGoldDragon** [comment]
@asottile Fair enough; this is also confirmed from within Spyder by "running" the file (even as `__main__`) instead of 'per-snippet'.
