### ISSUE TITLE
F841 doesn't work with unpacked function return

### ISSUE THREAD

**Issue by bread22** [PyCQA/pyflakes#540]
Unused variables assigned from unpacked function return don't generate violations.

Exmaple below:

```python
def new():
    return 1, 2


def flake8_bug():
    a, b = new()
```

variables `a` and `b` are assigned but not used, it should generate F841, but flake8 didn't
```
C:\temp>flake8 flake8_bug.py

C:\temp>
```

I can reproduce this on both Linux and Windows 10. Using latest 3.7.8 flake8 with pyflakes 2.1.1

bug-report below:
```json
{
  "dependencies": [
    {
      "dependency": "entrypoints",
      "version": "0.3"
    }
  ],
  "platform": {
    "python_implementation": "CPython",
    "python_version": "2.7.16",
    "system": "Windows"
  },
  "plugins": [
    {
      "is_local": false,
      "plugin": "mccabe",
      "version": "0.6.1"
    },
    {
      "is_local": false,
      "plugin": "pycodestyle",
      "version": "2.5.0"
    },
    {
      "is_local": false,
      "plugin": "pyflakes",
      "version": "2.1.1"
    }
  ],
  "version": "3.7.8"
}
```

**Comment by asottile** [comment]
this [appears to be intentional](https://github.com/PyCQA/pyflakes/blob/da385d5d65c6f515ae0ca88338b0a2e7a5c19c9c/pyflakes/checker.py#L525-L528) 🤔

**Comment by bread22** [comment]
> this [appears to be intentional](https://github.com/PyCQA/pyflakes/blob/da385d5d65c6f515ae0ca88338b0a2e7a5c19c9c/pyflakes/checker.py#L525-L528) 🤔

OK, seems we have to live with it. 
Thanks for the explanation.
