### ISSUE TITLE
False positive ForwardAnnotationSyntaxError

### ISSUE THREAD

**Issue by poofeg** [PyCQA/pyflakes#542]
False positive ForwardAnnotationSyntaxError in this code:
```
from pydantic import BaseModel, constr


class Vehicle(BaseModel):
    vin: constr(min_length=17, max_length=17, regex=r'[A-HJ-NPR-Z0-9]{17}')
```
flake8 output:
`./false_F722.py:5:53: F722 syntax error in forward annotation '[A-HJ-NPR-Z0-9]{17}'`

**Comment by asottile** [comment]
pydantic's types are not pep 484 compatible:

```console
$ mypy t.py --ignore
t.py:5: error: Invalid type comment or annotation
t.py:5: note: Suggestion: use constr[...] instead of constr(...)
Found 1 error in 1 file (checked 1 source file)
```

when [PEP 593](https://www.python.org/dev/peps/pep-0593/) is implemented I believe that will have a solution for that (and pyflakes will need to handle `Annotation`)

**Comment by mixmastamyk** [comment]
Not sure what I'm supposed to do with this. I have code with dictionaries passed in the annotations.  Even `Annotated[...]` doesn't seem to help.

This is a real problem so not sure the ticket should be closed.  If pyflakes can't handle the situation, it should be quiet IMHO.

**Comment by asottile** [comment]
@mixmastamyk `Annotated` is implemented on the master branch
