### ISSUE TITLE
unused variable warning when deleting in loop

### ISSUE THREAD

**Issue by JohannesBuchner** [PyCQA/pyflakes#551]
Hi all,

Thanks for creating pyflakes, it is a great help. 

I was wondering if the output below for the following input is expected behaviour:

test.py:
```
def myfunc():
	largest = 0
	for i in range(10):
		tmp = max(i, largest)
		del largest
		largest = tmp
```
pyflakes test.py
```test.py:6:3 local variable 'largest' is assigned to but never used```

Clearly largest is being used in the first 9 iterations.

It also occurs in this, perhaps more useful alteration:
```
def myfunc(widths):
	largest = 0
	for i, w in enumerate(widths):
		widths[i] = max(w, largest)
		del largest
		largest = widths[i]
```

**Comment by sigmavirus24** [comment]
Yes this is expected behaviour. Numerous closed issues explain this behaviour

**Comment by asottile** [comment]
fwiw, you don't need `del` in either of those examples

pyflakes doesn't do branch analysis (which is pretty difficult to get correct) and ~essentially sees all loops and if statements flattened.  so in this case, it sees a single name assigned at the end and then nothing after it (leading to the unused assignment)

**Comment by asottile** [comment]
collecting duplicates for "pyflakes doesn't do branch analysis" here: https://github.com/PyCQA/pyflakes/issues/715
