### ISSUE TITLE
When a reserved keyword appears in a f-string, the error only shows as `[flake8] E999: SyntaxError: invalid syntax` on the first line

### ISSUE THREAD

**Issue by otakutyrant** [PyCQA/pyflakes#553]
For example:

```
#!/usr/bin/env python

print(f"""{try}""")
```

I think that the error could be more readable, like showing `reserved keyword used in f-string` and locating the specific position rather than the line 1.

**Comment by asottile** [comment]
if flake8 can't parse the file at all you're going to get E999 -- there's no ast to lint if it can't be parsed to ast.

**Comment by otakutyrant** [comment]
Sorry for reporting the issue in the wrong place.

**Comment by asottile** [comment]
fwiw, this is what `pyflakes` gives (also on line 1

```console
$ ~/opt/venv/bin/pyflakes <<< $'\n\nf"{try}"'
<stdin>:1:2: invalid syntax
(try)
 ^
```

so it's probably a bug in cpython

**Comment by asottile** [comment]
and it looks like it's (partially) fixed in python3.9:

```console
$ pyflakes --version
2.2.0 Python 3.9.0b1 on Linux
$ pyflakes <<< $'\n\nf"{try}"'
<stdin>:3:2: invalid syntax
(try)
 ^
```
