### ISSUE TITLE
Complex annotation expressions yield errors

### ISSUE THREAD

**Issue by huettenhain** [PyCQA/pyflakes#554]
Consider the following code:
```python
class Annotation:
    def __init__(self, *args, **kwargs):
        pass


def test(a: Annotation('Yikes', 'This is fine.', foo=NotImplemented, bar=12)):
    return a


print(test(12))
```
Running this with **Python 3.8.3** works fine, and it is also valid code according to [the PEP](https://www.python.org/dev/peps/pep-3107/), quote:

> Function annotations are nothing more than a way of associating arbitrary Python expressions with various parts of a function at compile-time.

However, running **Pyflakes 2.2.0** produces the following output:
```
$ pyflakes test.py
test.py:6:24 undefined name 'Yikes'
test.py:6:33 syntax error in forward annotation 'This is fine.'
```

**Comment by asottile** [comment]
PEP 593 is not yet implemented (it was not accepted / ready when pyflakes 2.2 was released) but we would be happy to accept a patch to improve the situation there.  there's similar specific handling for `Literal` and `cast` already that you may find helpful for implementing this

**Comment by asottile** [comment]
oh actually this is separate, your code isn't valid under PEP 484:

```console
$ mypy t.py 
t.py:6: error: Invalid type comment or annotation
t.py:6: note: Suggestion: use Annotation[...] instead of Annotation(...)
Found 1 error in 1 file (checked 1 source file)
```

**Comment by asottile** [comment]
(484 has superseded 3107 in case that's not clear from above)
