### ISSUE TITLE
False positive with .format(...) unused positional arguments / F523?

### ISSUE THREAD

**Issue by mika** [PyCQA/pyflakes#559]
Stumbled upon this with flake8 v3.8.3 (reporting it as F523), while flake8 v3.6.0 didn't show this behavior.

STR:

```
% cat demo.py 
source = "foo"


class CriticalException(Exception):
    """Throw critical exception if the exact error is not known but fatal.
    @Exception: message"""


raise CriticalException(
    (
        "Error executing mount: %s already mounted - "
        "please unmount before invoking grml2usb"
    ).format(source)
)
```

Old pyflakes3 wasn't reporting this:

```
% pyflakes3 demo.py 
% pyflakes3 --version
2.0.0
% flake8 --version
3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.7.3 on Linux
```

While recent version(s) report it as follows:

```
% pyflakes3 demo.py 
demo.py:10:5 '...'.format(...) has unused arguments at position(s): 0
% pyflakes3 --version
2.2.0 Python 3.8.3 on Linux
% flake8 --version
3.8.3 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.3 on Linux
```

Could it be that pyflakes is parsing this wrong? FTR, code has been extracted from a project and was formatted by [black](https://github.com/psf/black) as such.

Thanks for pyflakes!

**Comment by mika** [comment]
Oh, instead of:

```
"Error executing mount: %s already mounted - "
```

that should be:

```
"Error executing mount: {0} already mounted - "
```

Wasn't really obvious for me and went unnoticed for way too long. :)
Thanks for the hint to @apollo13!

pyflakes/flake8 ftw :)

**Comment by asottile** [comment]
I added this rule!  good to see it's catching real problems in your code :)
