### ISSUE TITLE
Too many positional arguments?

### ISSUE THREAD

**Issue by pwinston** [PyCQA/pyflakes#560]
On this test program:
```
def func():
    return 42

func(1, 2, 3)
```
`pylint` says `E1121: Too many positional arguments for function call (too-many-function-args)` but `pyflakes 2.2.0` has no errors or warnings.

Is this by design? Is there some technology pylint is using here that flake8 doesn't have?

**Comment by asottile** [comment]
from the README of pyflakes:

> Pyflakes analyzes programs and detects various errors. It works by parsing the source file, not importing it, so it is safe to use on modules with side effects. It's also much faster.

in more words, pyflakes works entirely statically and does not do any type analysis (it does not follow imports or function calls, etc.).  this design is chosen to keep pyflakes fast and simple and focus on syntax that will always cause errors / warnings.  If you're looking for type analysis, you're best to use a type checker such as mypy or a tool like pylint.  I like to refer to what pylint / other type checkers do as "dynamic" analysis (I may have coined this term, not sure if there's a better way to refer to it), that is it requires some knowledge about your project setup / import path / dependencies / etc. to work properly (which necessarily means a more complex setup to get linting working and some (sometimes significant) performance overhead to perform the analysis.

note that you could implement type analysis on top of `flake8`, but pyflakes does not do that.

**Comment by pwinston** [comment]
Thanks for the explanation. It's not totally obvious that "wrong number of arguments" requires "type analysis". Naively it seems like it could notice the number of arguments was wrong without knowing the types of those arguments?

But I can see if function calls are just not looked at, then certainly it can't find this problem.

Thanks again.

**Comment by asottile** [comment]
in python, the shape of a callable _is its type_ (number of parameters, kwonly, posonly, defaulted, collecting, etc.)

**Comment by pwinston** [comment]
Yeah makes sense, thanks.
