### ISSUE TITLE
Possible false negatives being thrown in F541 for Django urls.py

### ISSUE THREAD

**Issue by chocoelho** [PyCQA/pyflakes#563]
pyflakes is throwing F541 for this chunk of code, saying that this f-string has nothing to interpolate. The approach used in the sample is consistent with PEP-0498 [raw f-strings](https://www.python.org/dev/peps/pep-0498/#raw-f-strings) section.

```python
    re_path(
        fr"^{VAR_X}/some-url/{VAR_Y}/$",
        MyView.as_view(),
        name="my-view",
    ),
```

pyflakes==2.2.0

**Comment by asottile** [comment]
I cannot reproduce, please include the actual code causing your problem:

```console
$ ~/opt/venv/bin/pyflakes
VAR_X = VAR_Y = 1
fr"^{VAR_X}/some-url/{VAR_Y}/$"
$
```

**Comment by chocoelho** [comment]
🤦‍♂️ sorry, I misread the line it indicated and it wasn't a false positive 
closing this issue
