### ISSUE TITLE
False positive: F821 on `Generic[TypeVar('T')]`

### ISSUE THREAD

**Issue by zackw** [PyCQA/pyflakes#565]
This test case produces a spurious F821 error:

```
from typing import Generic, TypeVar


class C(Generic[TypeVar('T')]):   # F821: undefined name 'T'
    pass
```

This does not happen if I assign the type variable to an actual variable (even if it has a different name than the argument to TypeVar):

```
from typing import Generic, TypeVar
X = TypeVar('T')


class C(Generic[X]):
    pass
```

but I don't think I should have to do that; this is the only place in the file where this particular type variable is used, and neither mypy nor the core interpreter cares whether TypeVar objects are bound to global names.

This is with pyflakes 2.2.0 (run via flake8 3.8.3).

**Comment by asottile** [comment]
because I'm curious for the usecase, what's the point of making a class generic if the typevar is never used?

I agree that it shouldn't be flagged, if this is actually a valid pattern (I can't think of a usecase myself unfortunately)

**Comment by zackw** [comment]
I'm working around a gap in the typing module.  Here's a little more context:

```
# mypy understands asyncio.Future to be a generic type, but the regular
# interpreter doesn't, and there is no alias for it in typing.  This is
# only used in type annotations so it doesn't need any detail for the
# regular interpreter.
if TYPE_CHECKING:
    from asyncio import Future as AIOFuture
else:
    class AIOFuture(Generic[TypeVar('T')]):
        pass

...

def store_result(fut: AIOFuture[SiteResults], site: str) -> None:
    ...
```

I have to make the stub `AIOFuture` inherit from `Generic` so that I can write `AIOFuture[SiteResults]` in the function's parameter type annotation, and `Generic` insists on being parametrized with at least one type variable.

**Comment by asottile** [comment]
oh, the usual thing to do for that is to quote the type:

```python
def store_result(fut: 'AIOFuture[SiteResults]', site: str) -> None:
```

alternatively if you're python3.7+ you can use `from __future__ import annotations`

___

note that mypy does reject inline `TypeVar`, so I think this issue is invalid:

```python
from typing import Generic, TypeVar

class C(Generic[TypeVar('T')]):
    pass
```

```console
$ mypy t2.py
t2.py:3: error: Invalid base class "Generic"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by jonathanslenders** [comment]
I'm having a false positive in this code:
```python
from typing import Dict

def test() -> None:
    class Tree(Dict[str, "Tree"]):
        def __missing__(self, key: str) -> "Tree":
            self[key] = Tree()
            return self[key]
```
```
/tmp/x.py:4:26 undefined name 'Tree'
```
Is that the same issue? Or should I open a new one?

**Comment by asottile** [comment]
that's different, please open a new issue
