### ISSUE TITLE
Feature Request: Check for if statements with truthy/falsey literals which determine the truth value

### ISSUE THREAD

**Issue by lucaswiman** [PyCQA/pyflakes#568]
Add a check that alerts when the branch taken in an `if` statement is determined by a boolean clause with a falsey or truthy literal. Examples that would be cause an error:
```python
if True:
if False:
if True or ...:
if False and ...:
if x=="value" or "other value":
if True and (False and (True or False)):  # i.e. it applies the check recursively to each clause
if {} or 0 or 0.0 or [] or '' or False:
```
Examples that would still be allowed:
```python
if 1 == 1:
if "foo" in ("foo", "bar"):
if False or ...:
if True and ...:

x = True
if x:
```
I would be amenable to implementing this check if it's a good fit for pyflakes/flake8, or I could make it a flake8 plugin if not. Feel free to close this issue if it's not a good fit for pyflakes.

## Rationale
Recently at my job, we had a bug in production due to code along the following lines
```python
def foo(bar):
    if bar == 'bar' or 'baz':
        print('always executed')
```
Clearly the author intended `bar == 'bar' or bar == 'baz'`. It's a bit difficult to catch this in code review, since the code _almost_ looks right, but isn't. Generally if you want deterministic behavior that does not depend on variables, you wouldn't write an if statement in the first place. I'm not aware of any valid reason for this sort of code.

I also use the following sort of idioms for debugging, which I wouldn't want to accidentally check in:
```python
if False and ...:
    # Code I want to skip, e.g. because it is not relevant to what I'm debugging and is slow.
if True or ...:
    # code I want to force to be executed.
if False:
    # indented code I don't want executed.
```

**Comment by asottile** [comment]
this seems like it might be too high false positive for pyflakes, especially when `if False:` is a common idiom for `mypy` (for forward / circular type references) but it should be very easy to write a flake8 plugin for this

**Comment by lucaswiman** [comment]
@asottile Don't `from __future__ import annotations` and `if TYPE_CHECKING: ...` and using strings take care of most of those issues?

That said, it's plausible that enough people use boolean literals that a check could be annoying. What about having the check only apply to literals other than True/False?

**Comment by asottile** [comment]
@lucaswiman that only works for python3.7+ (`annotations`) or 3.5.2+ (`TYPE_CHECKING`, yes it was introduced in a patch release)

I'd encourage you to write this as a flake8 plugin, especially because you can require modern python where pyflakes cannot and you can have a little more leniency on false positives (due to flake8 having `noqa` / etc.) where pyflakes cannot.
