### ISSUE TITLE
typing not working with pyflakes  google cloud shell editor 

### ISSUE THREAD

**Issue by girirajthara** [PyCQA/pyflakes#570]
<img width="1003" alt="Screenshot 2020-08-13 at 4 00 01 PM" src="https://user-images.githubusercontent.com/24633011/90124579-3d29f880-dd7e-11ea-8b9a-cff49dcb94f9.png">

**Comment by sigmavirus24** [comment]
Can you please paste the sample code and the exact error along with the version info? Screenshots are inaccessible to folks who need to use screen reader like accessibility tools. Further, it's not searchable at all.

**Comment by asottile** [comment]
you'll get this error if you're running pyflakes using python2, make sure you're matching the target python version

with a python3 pyflakes you get:

```console
$ ~/opt/venv/bin/pyflakes t.py
t.py:18:1 undefined name 'reveal_type'
t.py:19:1 undefined name 'reveal_type'
```

with a python2 pyflakes you'd get the syntax error:

```console
$ pyflakes t.py 
t.py:11:17: invalid syntax
    def make(cls: Type[TBase], s: str) -> TBase:
                ^
```
