### ISSUE TITLE
False positive: unused import for quoted generic parameters and TypeVar bounds

### ISSUE THREAD

**Issue by rraval** [PyCQA/pyflakes#571]
Similar to #447, it seems that quoted types are not handled when passed as a generic parameter to a base class:

```python
from typing import TYPE_CHECKING, Generic, TypeVar

if TYPE_CHECKING:
    # imagine this being some module that has circular imports
    from threading import Thread  # <--- pyflakes: 'threading.Thread' imported but unused

T = TypeVar("T")

class Base(Generic[T]):
    pass

class Derived(Base["Thread"]):
    pass
```

Perhaps worth a different issue, but the same thing occurs when using a `bound` for `TypeVar`:

```python
from typing import TYPE_CHECKING, Generic, TypeVar

if TYPE_CHECKING:
    # imagine this being some module that has circular imports
    from threading import Thread  # <--- pyflakes: 'threading.Thread' imported but unused

T = TypeVar("T", bound="Thread")

class Base(Generic[T]):
    pass
```

Version information:

```
$ pyflakes --version
2.2.0 Python 3.6.8 on Linux
```

**Comment by asottile** [comment]
user generics can't really be supported without solving some sort of halting problem -- currently only types from the `typing` module are supported.  could you please open a separate issue for the `TypeVar(... bound=)` bit?

**Comment by teocasse** [comment]
Hi, can you elaborate on the blockers for proper support for user generics, any plans to remove them? I'm currently facing similar issues (on Python 3.6) with quoted types raising F401 when passed as a generic parameter, minimal example here.

foo.py:
```
from typing import TYPE_CHECKING, Generic, TypeVar

if TYPE_CHECKING:
    from bar import Bar  # needed to avoid circular imports

T = TypeVar("T")


class Foo(Generic[T]):
    pass


class Test(Foo["Bar"]):
    pass
```

bar.py:
```
class Bar:
    pass
```

Test results:
```
~:test $ flake8 .
./foo.py:4:5: F401 'bar.Bar' imported but unused
```

Forward references should be allowed as generic parameters but it looks like `pyflakes` doesn't recognize them. Is there any solution, other than adding `# noqa: F401` to the offending import?

**Comment by asottile** [comment]
as above:

> user generics can't really be supported without solving some sort of halting problem

note that the halting problem is unsolvable

**Comment by teocasse** [comment]
thanks for the quick reply. That's unfortunate, but at least there is a workaround.

Can't test on Python 3.7+ right now, but I guess that by using `from __future__ import annotations` and changing the forward reference to the actual type, the problem should go away, right?

**Comment by asottile** [comment]
hmmm I don't think `from __future__ import annotations` would help since it's not in an annotation context but in an actual runtime context

**Comment by teocasse** [comment]
mmm valid point, I think you are right. Generic parameters are not in scope for postponed evaluation of annotations. Thanks anyway!

**Comment by asottile** [comment]
it's possible some improvements could be made for generics within the same file (keep a registry of classes that inherit from `Generic`, treat those as special generics) that may help a subset of this problem?  that might be enough to make your examples pass (but as soon as those generics cross an import boundary there's nothing pyflakes can do)

**Comment by teocasse** [comment]
That would not help in my case, since unfortunately my generics are crossing an import boundary and I cannot easily refactor them. But I see how it could help in some other cases.

**Comment by last-partizan** [comment]
I've come here to report this issue, and found it already reported and closed.

I'm using django-types https://github.com/sbdchd/django-types which uses following notation

```python
from django.db import models

# 'someapp.models.User' imported but unused
from someapp.models import User


class Book(models.Model):
    user = models.ForeignKey["User"]("auth.User", models.CASCADE)
```

This is real unsolved issue, and it should be left open. Even if there is some unsolvable problem, maybe we could find workaround, or solution that will work good enough for most people, even if not 100% correct.

**Comment by asottile** [comment]
there is no reason to leave an unsolvable issue open

**Comment by last-partizan** [comment]
@asottile are you sure there is no way to solve this?

could you point me in the direction where i should look, if i want to try to fix this?

**Comment by asottile** [comment]
in order to solve this pyflakes would have to follow imports to discover generics [which it intentionally does not do](https://github.com/PyCQA/pyflakes#pyflakes)

**Comment by last-partizan** [comment]
So, TypeVar support is hardcoded?

I think, user-defined generics could be supported by providing support for listing them in config file, or env variable?

**Comment by asottile** [comment]
pyflakes does not have a configuration file or options currently (also intentionally)

**Comment by last-partizan** [comment]
Looks like it uses env variables for similar purpose? I mean PYFLAKES_BUILTINS

**Comment by asottile** [comment]
you're probably best to just ignore them via flake8

or in your example above un-quote the type
