### ISSUE TITLE
Pandas df.query() not supported

### ISSUE THREAD

**Issue by r0f1** [PyCQA/pyflakes#582]
Consider the following code:
```
import pandas as pd
df = pd.DataFrame({"a": [1,2,3], "b": [10,20,30]})
good_a = [1,2]
df.query("a in @good_a")
```
This creates a pandas DataFrame, and selects all rows where column `a` matches one of the values in the provided list `good_a`.
Running pyflakes on this piece of code, results in the following error:
```
myfile.py:3: local variable 'good_a' is assigned to but never used
```

**Comment by asottile** [comment]
no surprise here, if you're using eval / exec / frame hackery you're going to need to ignore errors

if you're using `flake8` you can `# noqa` comment the line

but yeah there's nothing for pyflakes to do here -- the linter by-design reports errors on eval / exec as it's not statically traceable
