### ISSUE TITLE
Unused arguments

### ISSUE THREAD

**Issue by r0f1** [PyCQA/pyflakes#589]
Hi,
This is more of a features request: Is it possible that pyflakes detects unused arguments?
I think, the following function should raise an error, because `c` is unused.

```python
def func(a, b, c):
    return a + b
```

Thanks, Flo

**Comment by asottile** [comment]
it could, but it would be very high false positive which goes against pyflakes's design goals:

> Pyflakes makes a simple promise: it will never complain about style, and it will try very, very hard to never emit false positives.

A few other tools such as pylint, dead, vulture, etc. have this detection
