### ISSUE TITLE
pyflakes fails to warn about undefined variable that's defined inside nested try blocks

### ISSUE THREAD

**Issue by alexei** [PyCQA/pyflakes#591]
We have a piece of code that essentially looks like:
```python
class Foo:
    class Exc(Exception):
        pass


def test():
    try:
        try:
            foo = Foo()
        except Exception:
            return 1
    except foo.Exc:
        return 2
```

Running `flake8 test.py` or `pyflakes test.py` doesn't output anything.

I was expecting it to point out `foo` at line 12 is undefined e.g. `test.py:12:12: F821 undefined name 'foo'`

We have fixed our code in the meantime (it's clearly in the wrong), but I thought it appropriate to file this and you can decide whether it constitutes a bug or not.

FWIW I'm using `pyflakes` version 2.1.1 (indirectly through `flake8`), Python is 3.7.9, platform is Darwin.

**Comment by asottile** [comment]
pyflakes doesn't perform branch analysis so it can't know that it's possible for `foo` to be undefined in that scenario

to pyflakes it looks ~something like this:

```python
foo = Foo()
foo.Exc
```

there's a few other issues in the tracker about implementing proper branch detection, but it's exceptionally difficult and would be a major breaking change -- you're better to use something like `mypy` to detect that.

the other problem with branch detection (beyond it being a combinatoric explosion for even just a few if statements) is we'd potentially break a lot of existing code

something like this:

```python
if cond_a:
   a = 1

...

if cond_b:
    print(a)
```

would likely be flagged, but the static analysis tool can't possibly know that `cond_a -> cond_b` and so the code is correct

**Comment by asmeurer** [comment]
The code you posted works without any problems. I'm assuming you transcribed it incorrectly. Even if `Foo()` raised an exception, causing `foo` to not be defined, it would return before `foo` is referenced.

**Comment by asmeurer** [comment]
Sure, if the report here is "pyflakes doesn't catch that a variables defined in a try block might not be defined if an exception is raised before the definition happens", then you are right that pyflakes can't really do much about that. The only way to fix it would be to require that variables are defined outside of a try block, which would be a false positive for any "correct" code. I wouldn't even put that in the same class a branch analysis (IMHO, pyflakes *should* be doing a form of "branch analysis" where variables are required to be defined in every branch of an if/elif construct).

But it isn't obvious to me that that's what @alexei actually intended with his example.

**Comment by alexei** [comment]
@asmeurer indeed the code works, except for one instance a couple of days ago where `Foo()` in the example triggered a `SystemExit` which in turn triggered an `UnboundLocalError`, like @asottile pointed out it might. I could have done a better job illustrating the problem:
```python
$ cat test.py 
class Foo:
    class Exc(Exception):
        pass

    def __init__(self):
        raise SystemExit()


def test():
    try:
        try:
            foo = Foo()
        except ValueError:
            return 1
    except foo.Exc:
        return 2


test()
$ flake8 test.py 
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 12, in test
    foo = Foo()
  File "test.py", line 6, in __init__
    raise SystemExit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 19, in <module>
    test()
  File "test.py", line 15, in test
    except foo.Exc:
UnboundLocalError: local variable 'foo' referenced before assignment
```

I think our approach in the code was wrong, and a fellow developer fixed it since. When I got notified about the issue, my first thought was "why didn't flake8 catch that?" and figured I must have misconfigured it or something. I now realise this is an odd case which might be difficult to detect. And besides, I'm satisfied with pyflakes as it is 🙏
