### ISSUE TITLE
F821 with PEP593 Annotated

### ISSUE THREAD

**Issue by yuyu2172** [PyCQA/pyflakes#594]
Hi. I have encountered an unexpected error when using PEP593 Annotated.

This is how the problem is reproduced.
Copy to `sample.py`:
```python
from typing_extensions import Annotated


t = Annotated[str, "metadata"]
```

```console
$ python -m pyflakes sample.py
sample.py:4:20 undefined name 'metadata'
```

The version of pyflakes is as follows:
```python
$ pyflakes --version 
2.2.0 Python 3.8.5 on Linux
```

Thanks in advance.

**Comment by asottile** [comment]
should be pretty easy to add -- there's currently special handling for `Literal` and the handling for `Annotated` was planned (but at the time the PEP had not been finalized)

**Comment by yuyu2172** [comment]
Nice to hear that the support for `Annotated` is planned. Thanks!

**Comment by JacobHayes** [comment]
Looks like https://github.com/PyCQA/pyflakes/pull/580 solves this, but it's just pending a release?

**Comment by asottile** [comment]
ah indeed -- then it's already solved!

**Comment by FFY00** [comment]
Hey, any chance we can get this released? Thanks :blush:

**Comment by asottile** [comment]
@FFY00 your comment is unhelpful, please see the pinned topic
