### ISSUE TITLE
Python 3.9

### ISSUE THREAD

**Issue by Richardk2n** [PyCQA/pyflakes#602]
Python 3.9 introduced new features like PEP593, which are apperently already implemented (see #594).
Is there an overview what is left to do before a complete 3.9 release can be done?

And if you don't mind me asking:
Is there any planned timeframe for when to expect such a release?

**Comment by asottile** [comment]
I think that's all that's really relevant to pyflakes

I'll try and organize a release in the next couple of weeks -- have to do one last release in flake8 as well before dropping python 2
