### ISSUE TITLE
The next release (pyflakes 2.3.0)

### ISSUE THREAD

**Issue by asottile** [PyCQA/pyflakes#607]
I'd like to make one last release of pyflakes before [removing EOL python support (2 / 3.5) in flake8](https://gitlab.com/pycqa/flake8/-/issues/690)

I've done a bit of work to check for regressions -- I also think I might productionize this in some way such that we can check each PR against a bunch of repositories to look for changes as they're committed.

I'm essentially running against all of my python code as well as a few larger open source repositories and checking the difference in output against the different pyflakes versions.  So far the only blocker I see for releasing is #605

**Comment by asottile** [comment]
#608 for the changelog

**Comment by shadchin** [comment]
When can expect the release?
