### ISSUE TITLE
wrong line number from f-string

### ISSUE THREAD

**Issue by Akuli** [PyCQA/pyflakes#612]
```
$ cat a.py
# comment goes here
foo = f"{aaa.0}"

$ pyflakes a.py
a.py:1:7: invalid syntax
(aaa.0)
      ^
```

This causes the error marker to show up in the wrong place when using pyflakes through python-language-server:

[a](https://user-images.githubusercontent.com/18505570/105067199-25227780-5a88-11eb-82b5-ff52849645c1.mp4)

**Comment by asottile** [comment]
that error message and line number come from python directly -- there isn't anything we can do about this -- I'd suggest reporting this upstream at bugs.python.org (though I believe there's already an existing bug for it there as well)

**Comment by Akuli** [comment]
Python itself reports it correctly:

```
  File "<fstring>", line 1
    (aaa.0)
         ^
SyntaxError: invalid syntax
```

Notice how it says `File "<fstring>"`. But unfortunately, it doesn't say which f-string it is, so maybe pyflakes can't do much...

**Comment by sigmavirus24** [comment]
We literally get the offset (column) from Python's AST library: https://github.com/PyCQA/pyflakes/blob/43541ee1dd394ec4691625e7295f701b3b073dca/pyflakes/checker.py#L1443-L1448

**Comment by Akuli** [comment]
That is doctest parsing code, unrelated to f-strings.

**Comment by sigmavirus24** [comment]
You're right. This is where we handle the offset and printing of the syntax error: https://github.com/PyCQA/pyflakes/blob/43541ee1dd394ec4691625e7295f701b3b073dca/pyflakes/reporter.py#L39-L66 

My guess is that the offset math we've done (without issue in the past) is wrong and you're on a Python 3.8 or 3.9 and the check we have isn't sufficient. That said, you've given us no information to appropriately reproduce

**Comment by Akuli** [comment]
>you've given us no information to appropriately reproduce

I provided an example file with a syntax error inside an f-string. I showed how `pyflakes a.py` says that syntax error is on line 1 even though the f-string is on line 2. Because this is no information, can you tell me what is the information you need to appropriately reproduce the problem?

**Comment by Akuli** [comment]
I guess I should mention:

```
$ pyflakes --version
2.2.0 Python 3.7.3 on Linux
```
