### ISSUE TITLE
Please consider making type variable string bounds visible

### ISSUE THREAD

**Issue by NeilGirdhar** [PyCQA/pyflakes#614]
```python
from typing import Any, TypeVar

T = TypeVar('T', bound='Any')

def f(x: T):
    pass
```
Gives:
```
a.py:1:1 'typing.Any' imported but unused
```
This causes problems with automatic import removal done by autoflake: https://github.com/myint/autoflake/issues/84.

**Comment by asottile** [comment]
already considered and implemented on master

**Comment by NeilGirdhar** [comment]
@asottile Hooray!  That was fast.  Sorry for the noise.
