### ISSUE TITLE
Make F841 ignore setting to `__` variable and setting to variables prefixed with `_`

### ISSUE THREAD

**Issue by jack1142** [PyCQA/pyflakes#615]
While `_` is commonly used to name a "throw-away variable", it doesn't work for codebases that use gettext and assign it to a variable called `_`. In such cases, "throw-away variables" can be named `__` instead (I think it's common to gettext-based projects, but I don't have much to prove that). Another thing that I've noticed being used among different projects is to have a "throw-away variable" be prefixed with `_`, e.g. `_some_unused_variable`. So, I was wondering if it would be possible to support either of these use cases. I know pylint does support these, amongst a few other patterns and it definitely seems useful to have at least some other way to mark a variable as "throw-away", especially that it is common for i18n projects to use `_` for gettext instance.

**Comment by asottile** [comment]
please show an example, pyflakes already ignores all variables in unpackings which is the only place you would need to make a throwaway variable:

```python
__, bar = (1, 2)
```

```console
$ pyflakes t.py
$ echo $?
0
```

**Comment by jack1142** [comment]
Sorry, I wrongly assumed that this happens for any code.

Here's a small repro:
```py
def main():
    __, bar = (1, 2)
    return bar


print(main())
```
λ pyflakes test.py
test.py:2:5 local variable '__' is assigned to but never used
λ echo %errorlevel%
1
```

**Comment by asottile** [comment]
#202 (and other linked duplicates)
