### ISSUE TITLE
F821 "ellipsis" in typing is not an error

### ISSUE THREAD

**Issue by henryiii** [PyCQA/pyflakes#616]
In MyPy, to actually type an ellipsis, say for implementing `__getitem__`, you use the following weird construction (using Python 3.6 syntax, since that's what I'm actually using):

```python
from typing import Union

def f(x: Union[int, "ellipsis"]) -> None:
    pass

f(1)
f(...)
```

This passes MyPy `--strict`. However, pyflakes (flake8 error code F821) is being too clever, can reports that `ellipsis` is an undefined. This should be a special case - it is a defined name when used in a string / string annotation. Personally, I think there should be a real base class for ellipsis in typing or something, but there isn't as far as I know (which is why the weird workaround above works).

PS: Same issue in string annotation mode, `mypy --strict tmp.py --python-version 3.7` passes and `pyflakes tmp.py fails`:

```python
from __future__ import annotations

def f(x: int | ellipsis) -> None:
    pass

f(1)
f(...)
```

**Comment by asottile** [comment]
there's no mention of this in [PEP 484](https://www.python.org/dev/peps/pep-0484/), I think an update needs to happen there first (and agreement across the type checkers) before a special case is implemented here.  Ideally it would just be spelled `Ellipsis` similar to `True` / `False` / `None` and then a special case would be unnecessary here (as it would resolve directly to the builtin)

**Comment by henryiii** [comment]
Ellipsis already had a meaning in type checking, like in `Tuple[int, ...]`. If you differentiate between `Ellipsis` and `...` just in type checking, perhaps? But that would also be a little odd, but mypy currently does not allow Ellipsis to be used where `...` is, so I think it would work.

**Comment by asottile** [comment]
I'd suggest starting a thread in typing-sig@python.org -- should be a pretty straightforward edit to the PEP (though a little weird as it violates other parts of typing about importability, etc.)

**Comment by henryiii** [comment]
Looks like it's come up before https://mail.python.org/archives/list/typing-sig@python.org/thread/277RFXNQYLT6D3R4EYZZOPPGX56SNIK6/#HVNJAVV6BVRGAPVRHWDDXRDGS334XHJC - sounds promising for a possible `Ellipsis` which would be much more discoverable than `ellipsis`. Will start a thread with a reference to that one.

**Comment by henryiii** [comment]
For reference, here is the new thread: https://mail.python.org/archives/list/typing-sig@python.org/thread/CZO2IRIVY43SZUBQMDRIPGT2W4FFD6ZH/

**Comment by henryiii** [comment]
The following, suggested in typing-sig, fixes the issue with pyflakes:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from builtins import ellipsis
```

This is because this is implemented in builtins.pyi but not builtins.py. This is weird, but less ugly than pulling it out of thin air and a reasonable workaround until this is implemented properly, either with EllipsisType or a special cased Ellipsis. The response looks pretty encouraging on the thread for this improving in the future. Thank you!
