### ISSUE TITLE
F821 false positive?

### ISSUE THREAD

**Issue by Sh3Rm4n** [PyCQA/pyflakes#618]
I stumbled upon this issue because of an update to `flake8 v3.9`, which itself updates `pyflakes` to `v2.3`. 
Manual downgrades via `pip install flake8==3.8.4 pyflakes==2.2`, "solves" the issue. 

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""This is a docstring."""


class _FromImport:
    @staticmethod
    def test():
        pass


ObjectWithAnnotation: _FromImport


def _make_global():
    global ObjectWithAnnotation


def _test_function(**kwargs):
    ObjectWithAnnotation.test()


def test():
    """The function, which is called."""
    _make_global()
    _test_function()
```

results into `/tmp/flake8-test.py:21:5: F821 undefined name 'ObjectWithAnnotation'`

Maybe I understand it incorrectly, but isn't `ObjectWithAnnotation` defined in this case?

```diff
20a21,22
>     global ObjectWithAnnotation
>
```

suppresses the lint, though `global` should not be needed here, because ObjectWithAnnotation is not being changed inside the function. 

https://www.flake8rules.com/rules/F821.html is not really helpful in this regard.

Is this a misunderstanding on my side, or is this a false positive?

**Comment by bitglue** [comment]
If I add a `test()` at the end so the function actually gets called, and run the program:

```
$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    test()
  File "test.py", line 27, in test
    _test_function()
  File "test.py", line 21, in _test_function
    ObjectWithAnnotation.test()
NameError: name 'ObjectWithAnnotation' is not defined
```

This would indicate it is a legitimate error.

I believe the explanation here is `ObjectWithAnnotation: _FromImport` is not an assignment, but a [type alias](https://www.python.org/dev/peps/pep-0613/). As such, `ObjectWithAnnotation` isn't a variable, but a type. You can use it in a type annotation, but trying to use it as a variable will always raise `NameError`.

`global ObjectWithAnnotation` works because it declares a new global variable (which happens to have the same identifier as a type annotation).

Does that make sense?

**Comment by bitglue** [comment]
I should add that while `global ObjectWithAnnotation` declares "When I say `ObjectWithAnnotation` I mean the global thing named that", the code doesn't assign any value thereafter, so the statement doesn't really have any effect. If you add `ObjectWithAnnotation = _FromImport()` in `_make_global()`, you get a different behavior. While it works in a way, it's pretty confusing to have an identifier that refers to both a type alias and a variable, so I wouldn't recommend it.

**Comment by Sh3Rm4n** [comment]
Thanks for the help. 
This error you pointed out is pretty obvious in hindsight and definitely makes sense.

I have to further work on a good minimal example to get the exact behavior, which I observe on the codebase I am working on right now. I left out some important details it seems. I'll try to get a better minimal example.

**Comment by bitglue** [comment]
OK. I'm going to close this for now, but please do open a new issue when you have an example.

**Comment by bitglue** [comment]
FYI #617 could be related.
