### ISSUE TITLE
Consider `import X as X` import to be used

### ISSUE THREAD

**Issue by bluetech** [PyCQA/pyflakes#620]
### Background info

The typing PEP 484 [specifies](https://www.python.org/dev/peps/pep-0484/#stub-files) the syntax `import X as X` to signify that the module re-exports the name `X` in stub files:

> Modules and variables imported into the stub are not considered exported from the stub unless the import uses the import ... as ... form or the equivalent from ... import ... as ... form. (UPDATE: To clarify, the intention here is that only names imported using the form X as X will be exported, i.e. the name before and after as must be the same.)

While this is specified only for stub files AFAIU, mypy and I believe other type checkers also treat it in this way in inline annotations as well. The mypy documentation for this is [here](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport).

Example file:

```py
from ._private import PublicClass as PublicClass  # x.py:1:1 '._private.PublicClass' imported but unused
```

### Problem

Reexport files often just do the reexports and nothing else. Currently, the X is not considered used and a `imported but unused` lint is issued.

### Proposed solution

pyflakes already treats being in `__all__` as a use, I propose that `import X as X` (and `from Y import X as X`) to be considered a use as well.

I can try to implement this if it sounds OK.

**Comment by asottile** [comment]
dupe #474
