### ISSUE TITLE
colon after column number

### ISSUE THREAD

**Issue by treverhines** [PyCQA/pyflakes#627]
Would it be possible to add a colon after the column number [here](https://github.com/PyCQA/pyflakes/blob/95fe313ba5ca384041472cd171ea60fad910c207/pyflakes/messages.py#L16)? I ask because it would simplify parsing the output by being consistent with the syntax error message [here](https://github.com/PyCQA/pyflakes/blob/95fe313ba5ca384041472cd171ea60fad910c207/pyflakes/reporter.py#L58).  

Thanks!

**Comment by asottile** [comment]
if anything I think the SyntaxError messaging should be made more like the other messaging (which is far more common and far less likely to break someone)

fwiw, you're probably going to have a better time using `flake8` to get structured output, perhaps using `flake8-json`.  If you're just interested in pyflakes errors you'd use `--select=F`

**Comment by treverhines** [comment]
Thanks for the response! `flake8 --select=F` gives the output I was looking for.

For background, I am raising this issue because nano uses pyflakes by default to lint python files, and it has not been able to parse pyflakes output since messages started including the column number. Nano would be able to parse the output if pyflakes included colons after column numbers, because the format would then be consistent with other supported linters. Changing the linter to "flake8 --select=F" resolves the issue. Thank you for the recommendation.

**Comment by asottile** [comment]
ah yeah, I used to have that in my nanorc as well: https://github.com/asottile/scratch/blob/ccee062dbb87b5d984ba31b26866466c0c1afe06/nanorc/python.nanorc#L3 (I've since been working on my own text editor as nano removed `^T` formatters in a later version (though I haven't added it back yet into [babi](https://github.com/asottile/babi)))

**Comment by treverhines** [comment]
FWIW the latest versions of nano support formatters again. Since version 5, they can be invoked with ^T and then ^O.
