### ISSUE TITLE
Possible F821 false positive getting attributes of members of variables named `typing`

### ISSUE THREAD

**Issue by gmarkall** [PyCQA/pyflakes#628]
The following:

```python
from collections import namedtuple

s = namedtuple('s', ('t',))
typing = s(t={'x': 'int'})

print(typing.t['x'])
```

executes as I'd expect:

```
$ python repro.py 
int
```

but running pyflakes on it results in:

```
$ pyflakes repro.py 
repro.py:6:16 undefined name 'x'
```

with:

```
$ pyflakes --version
2.3.1 Python 3.9.2 on Linux
```

I think that the F821 message is produced in error here - is there some subtlety about the above code that I'm missing?

**Comment by asottile** [comment]
unfortunately full type analysis cannot be done so pyflakes makes an assumption that things named `typing` are the [typing module](https://docs.python.org/3/library/typing.html) such that support for static type annotations (including forward annotations) can be done -- I'd recommend picking a different name if possible

**Comment by gmarkall** [comment]
Thanks for the quick response! Should I close this issue?

**Comment by asottile** [comment]
ah yeah but don't think it's actionable at this time

**Comment by gmarkall** [comment]
OK - many thanks!
