### ISSUE TITLE
Column number of 0 for multiline strings .format(...) unused positional arguments / F523

### ISSUE THREAD

**Issue by jackgrimes** [PyCQA/pyflakes#629]
Hello, I'm experiencing an issue using pyflakes and python==3.7.5, where a multiline string with no {} but with .format() on the end (F523) returns a pyflakes error with column/character number of 0. This causes a problem with sonarcloud, which is expecting non-0 column numbers.

Steps to reproduce: 

python==3.7.5
pyflakes==2.3.1

```
% cat demo.py
"""this is a multiline string
more string
`more string""".format("string_to_input")
```

```
% pyflakes demo.py
demo.py:3:0 '...'.format(...) has unused arguments at position(s): 0
```

Upgrading to python=3.8.0, still with pyflakes=2.3.1 and running pyflakes again, I don't see this issue:

```
% pyflakes demo.py
demo.py:1:1 '...'.format(...) has unused arguments at position(s): 0
```

So I imagine this is not intended behaviour, but it would be great to know either way.  

Thank you!

**Comment by asottile** [comment]
this was a bug in cpython:

```console
$ python3.7
Python 3.7.10 (default, Feb 20 2021, 21:15:28) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> vars(ast.parse("'''\n'''").body[0].value)
{'s': '\n', 'lineno': 2, 'col_offset': -1}
```

I fixed it in python3.8:

```console
$ python3.8
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> vars(ast.parse("'''\n'''").body[0].value)
{'value': '\n', 'kind': None, 'lineno': 1, 'col_offset': 0, 'end_lineno': 2, 'end_col_offset': 3}
```
