### ISSUE TITLE
assignment expression in comprehension should target outer scope

### ISSUE THREAD

**Issue by paullemarchand** [PyCQA/pyflakes#633]
Please consider the following example, which finds the first String in a list that contains the Substring "OH":

```
list = ["STEVE", "JOHN", "YOANN"]
pattern = re.compile(".*%s.*" % "OH")
word = ""

if any((match := pattern.match(item)) for item in list):
    word = match.group(0)
print(word)
```

The code works as intended and outputs "JOHN", but I am getting the following warning from flake8 at 
the line ```word = match.group(0):```

```
F821 -- undefined name 'match'
```

I made a post on [StackOverflow](https://stackoverflow.com/questions/67547135/why-does-flake8-give-the-warning-f821-undefined-name-match-when-using-match), where Anthony Sottile recommended me to post the issue here. I'm using flake8 3.9.2 (mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.9.5 on Windows.

**Comment by bbolli** [comment]
It's even worse: the code

```python
if msg := job_status_msg() and not yesno(msg + "\nContinue"):
    sys.exit(1)
```

reports both (in flake8) `F841 local variable 'msg' is assigned to but never used` for the first `if` term and `F821 undefined name 'msg'` for the second one.

I'm not sure it this is the same issue, though.

**Comment by asottile** [comment]
that's not the same issue, please open a new one

**Comment by asottile** [comment]
oh actually looking closer -- you're missing parentheses so it is right to flag that -- you want:

```python
if (msg := job_status_msg()) and not yesno(msg + "\nContinue"):
    sys.exit(1)
```

what you had written was equivalent to:

```python
msg = job_status_msg() and not yesno(msg + "\nContinue")
if msg:
    sys.exit(1)
```

**Comment by yannsartori** [comment]
Have there been any developments on this issue? I noticed the same thing in my code, using pyflakes 2.4.0.

**Comment by yannsartori** [comment]
Have there been any developments on this issue? I noticed the same thing in my code, using pyflakes 2.4.0.

**Comment by asottile** [comment]
@yannsartori do you see any comments or linked PRs or have you tried the latest version of master? (the question is rhetorical)

**Comment by yannsartori** [comment]
@asottile No, I suppose I do not. The reason I was asking was because I was wondering if there was any development on this issue considering Python 3.8 has been out for 2.5 years and a [similar example](https://peps.python.org/pep-0572/#scope-of-the-target) is present on the PEP introducing this feature. Additionally, the readme states that Pyflakes supports all active versions of Python after 3.6, which by this example, is not entirely correct.
