### ISSUE TITLE
False positive F821 on Python 3.9+ for postponed evaluation of annotations

### ISSUE THREAD

**Issue by ShadowLNC** [PyCQA/pyflakes#637]
Similar to [flake8#247](https://github.com/PyCQA/flake8/issues/247) and #356 but not the same. Similar report (by me) in [pylint#4490](https://github.com/PyCQA/pylint/issues/4490).

Given the following code:

```
class X:
    def func(self) -> X:
        pass
```

I get the following:

```
pyflakes .\repro.py
.\repro.py:2:23 undefined name 'X'
```

I would expect that F821 is not raised as postponed evalutation of annotations are enabled by default in Python 3.9.

If I specify `from __future__ import annotations`, it is (correctly) not raised.

Version:

```
pyflakes --version
2.3.1 Python 3.10.0b1 on Windows
```

**Comment by asottile** [comment]
they are not enabled by default until 3.11 at the moment so this issue is invalid

**Comment by ShadowLNC** [comment]
Sorry, not sure where I read that it was 3.9 (mypy does not report the error so I will now file a ticket there).

Looking at https://docs.python.org/3/library/__future__.html it says 3.10, did this change to 3.11 somewhere?

**Comment by asottile** [comment]
yeah it was a big controversy -- check the 3.10 version of the docs

**Comment by asottile** [comment]
also just try executing the code, it will crash

**Comment by ShadowLNC** [comment]
Thanks for the info 😄
