### ISSUE TITLE
unused variable not catched

### ISSUE THREAD

**Issue by xrmx** [PyCQA/pyflakes#640]
Hello, wondering if the following snippet is something that can be catched by pyflakes, thanks!

```python
def doesnotwarn():
    x = (1, 2)
    a, b = x
    return b
```

**Comment by asottile** [comment]
dupe #540

**Comment by xrmx** [comment]
I've done a quick experiment by removing the assignment check in `unusedAssignments`. Got a ton of false positive for function parameters but spotted a few valid places. So tweaked the check a bit to just ignore the arguments and I got quite a bit of legit unused bindings with the following:

```
diff --git a/pyflakes/checker.py b/pyflakes/checker.py
index 135ad33..4416ad0 100644
--- a/pyflakes/checker.py
+++ b/pyflakes/checker.py
@@ -648,7 +648,7 @@ class FunctionScope(Scope):
                     name != '_' and  # see issue #202
                     name not in self.globals and
                     not self.usesLocals and
-                    isinstance(binding, Assignment)):
+                    not isinstance(binding, Argument)):
                 yield name, binding
 
 ```

I've run it against the contrib module of a Django 3.1 branch checkout reporting 56 warnings, all the samples I've looked at look legit.

**Comment by asottile** [comment]
if you click through the duplicate it mentions that this is intentional -- so I don't think a change would be welcome here

**Comment by xrmx** [comment]
I've read it but haven't found a reason so I gave it a try anyway for fun. Thanks.
