### ISSUE TITLE
Double underscore and RedefinedWhileUnused

### ISSUE THREAD

**Issue by michaelkryukov** [PyCQA/pyflakes#641]
Command `pyflakes a.py` for file `a.py` with the following content:

```
def _():
    return 1


def _():
    return 2


def __():
    return 21


def __():
    return 22
```

Prints `a.py:13:1 redefinition of unused '__' from line 9`. It correctly ignores the first two functions as they were purposely named `_` name, which shows that these functions won't be called by name. In my actual case, they decorated as routes in fastapi. I named functions as double underscore, as I use pydash imported as `_` and I want to avoid name conflicts.

As far as I can see, `_` case is hardcoded, so I suppose linting can ignore the redefinition of the names that contain only `_`?

**Comment by asottile** [comment]
`_` is special cased, `__` is not
