### ISSUE TITLE
New check idea: Readable spacing for more complex kwarg values

### ISSUE THREAD

**Issue by ThiefMaster** [PyCQA/pyflakes#647]
I just had a line like this in a PR review:

```python
something(foo=bar, asdf=None if x == y else something)
```

I think this is poorly readable, since `asdf=None` looks like it belongs together, and the ` if x == y else something`  is separate from it.

Adding parentheses makes this much more readable:

```python
something(foo=bar, asdf=(None if x == y else something))
```

It would be nice if there was a flake8/pyflakes check for this that warns whenever there's an expression containing top-level spaces outside parentheses after a `=` without whitespace around it.

**Comment by asottile** [comment]
> Pyflakes makes a simple promise: it will never complain about style

this check isn't appropriate for pyflakes, but you could always make your own flake8 plugin
