### ISSUE TITLE
Import reported as unused when used for type hint of attribute with same name and default value

### ISSUE THREAD

**Issue by antonagestam** [PyCQA/pyflakes#648]
This is a weird one. Minimal example to reproduce:

```python
from types import MappingProxyType

class A:
    MappingProxyType: MappingProxyType = ...
```

This outputs (using `python3 -m pyflakes odd.py`):

```
odd.py:1:1 'types.MappingProxyType' imported but unused
odd.py:4:5 redefinition of unused 'MappingProxyType' from line 1
```

Doing any of: aliasing the type to a different name (`import ... as ...`), removing the default value, or changing the name of the attribute all make the example code pass.

The example probably looks very contrived, but this occurred in the real world in a much more normal looking piece of code, something along the lines of the below, and results in autoflake removing the import.

```python
from utils.types import Email
from dataclasses import dataclass

@dataclass
class ForeignObject:
    Email: Optional[Email] = None
```

Given the second error message in the output, it seems like pyflakes incorrectly interprets the line as a redefinition in the global scope, while it's actually a new definition in the local scope.

**Comment by asottile** [comment]
so while that sounds weird, the lint is actually correct!

if you inspect `A.__annotations__` you get this:

```
(Pdb) A.__annotations__
{'MappingProxyType': Ellipsis}
```

what has happened is the annotation is deferred until after the assignment, then it use the name in the class scope

**Comment by antonagestam** [comment]
@asottile Huh. It seems the behavior varies for `from __future__ import annotations` though. Is this a bug in Python?

```
$ cat << EOL | python
from __future__ import annotations
from types import MappingProxyType
from typing import get_type_hints

class A:
    MappingProxyType: MappingProxyType = ...


print(get_type_hints(A))
EOL
{'MappingProxyType': <class 'mappingproxy'>}
```

```
$ cat << EOL | python
from types import MappingProxyType
from typing import get_type_hints
                                 
class A:
    MappingProxyType: MappingProxyType = ...
                                            

print(get_type_hints(A))
EOL                     
{'MappingProxyType': Ellipsis}
```

**Comment by DetachHead** [comment]
> so while that sounds weird, the lint is actually correct!
> 
> if you inspect `A.__annotations__` you get this:
> 
> ```
> (Pdb) A.__annotations__
> {'MappingProxyType': Ellipsis}
> ```
> 
> what has happened is the annotation is deferred until after the assignment, then it use the name in the class scope

@asottile the error shouldn't occur when using `__future__.annotations` though, as that doesn't happen because the type annotations are not evaluated:

```py
from __future__ import annotations

from types import MappingProxyType
from typing import get_type_hints


class A:
    MappingProxyType: MappingProxyType = ...


print(A.__annotations__)  # {'MappingProxyType': 'MappingProxyType'}
```

it also works correctly when you evaluate them with `get_type_hints`:
```py
print(get_type_hints(A))  # {'MappingProxyType': <class 'mappingproxy'>}
```

**Comment by asottile** [comment]
actually, `get_type_hints` can't accurately represent the scope so it gets it wrong here -- this is one of the many reasons why `__future__.annotations` hasn't been ratified / finished (from PEP 484):

> The string literal should contain a valid Python expression (i.e., compile(lit, '', 'eval') should be a valid code object) and it should evaluate without errors once the module has been fully loaded. The local and global namespace in which it is evaluated should be the same namespaces in which default arguments to the same function would be evaluated.

`get_type_hints` doesn't (can't) accurately respect the scoping of the string annotation so it tries its best and (incorrectly) uses the global scope
