### ISSUE TITLE
NameError: name 'df' is not defined error when df is defined from prior code run (Spyder)

### ISSUE THREAD

**Issue by sbell007** [PyCQA/pyflakes#650]
I have very large .csv files that I would rather not load every time I run my code. Previously, I would load the data only the first run of the code using:
load_data = 1
if load_data == 1:
     df_raw = pd.read_csv(somefile.csv)
df = df_raw.copy()

On subsequent runs, I would change load_data = 0 which would skip the load data step since df_raw was already loaded in Spyder's Variable Explorer. Unfortunately, I am now getting "NameError: name 'df_raw' is not defined" from Pyflakes E even though df_raw does exist. I can try to write an exception in my code, but this seems to be a bug with how Pyflakes & Spyder interact.

I'm using Python 3.8.8 64bit, Spyder 4.2.5.

**Comment by asottile** [comment]
pyflakes doesn't produce `NameError` so your bug is probably in your code or in spyder

**Comment by sbell007** [comment]
@asottile Any idea what would give this error then:
![Capture](https://user-images.githubusercontent.com/87090638/126391460-495f828d-1ff2-4569-acc6-7c0866536d3e.PNG)

**Comment by asottile** [comment]
that's possibly pyflakes (though pyflakes's error message is lower cased), but it's also not the error message you posted in your original post, nor is it triggered when running pyflakes on the code in your original post

**Comment by sigmavirus24** [comment]
Further, pyflakes doesn't integrate with Spyder. Spyder integrates with pyflakes. If there's something that "should" work but is giving you an error, that's entirely on Spyder.
