### ISSUE TITLE
[pyflakes] redefinition of unused 'on_message' from line 12

### ISSUE THREAD

**Issue by GoldenGamingHQ** [PyCQA/pyflakes#652]
Trying to create a discord bot that sends a message of my schools timetable when typing "!timetable". Which works fine

The problem I'm having is my schools timetable intersects in 2 weeks, and both the first and second week have different periods. I want to make the bot type the classtimes for week A and B in separate commands, although since I need to use "on_message", more than once, The bot won't send the results for '!classtimesA' although it sends for '!classtimesB' which I find very weird and confusing. Here is the code I wrote.

```
import discord
import os
from keep_alive import keep_alive

client = discord.Client()

@client.event
async def on_ready():
    print('We have logged in as {0.user}'.format(client))

@client.event
async def on_message(message):
    if message.author == client.user:
        return


    if message.content.startswith('!timetable'):
        await message.channel.send('Week A:')
        await message.channel.send('Monday Period 3')
        await message.channel.send('Friday Period 3')
        await message.channel.send('Week B:')
        await message.channel.send('Tuesday Period 2')
        await message.channel.send('Friday Period 1')




@client.event
async def on_message(message):
    if message.author == client.user:
        return


    if message.content.startswith('!classtimesA'):
      await message.channel.send('**Week A**')
      await message.channel.send('Tuesday: 11:57am')
      await message.channel.send('Friday: 12:02pm')




@client.event
async def on_message(message):
    if message.author == client.user:
        return


    if message.content.startswith('!classtimesB'):
      await message.channel.send('**Week B**')
      await message.channel.send('Tuesday: 10:23am')
      await message.channel.send('Friday: 9am')

keep_alive()
client.run(os.getenv('TOKEN'))
```

Don't mind the 'keep_alive' code. Thats just the bot receiving pings to stop it from going offline..

If anyone could help with this issue that would be amazing, as this is for a school project.

Thanks.

**Comment by asottile** [comment]
this isn't exactly a support forum -- but pyflakes is hinting to you what the problem is

there's only allowed one `on_message` function (you have 3 -- combine them)
