### ISSUE TITLE
False positive F821 undefined name 'string'

### ISSUE THREAD

**Issue by fmigneault** [PyCQA/pyflakes#653]
I have the following comment in the code.

```python
#  literalDataDomain:
#    type: object
#    properties:
#      valueDefinition:
#        oneOf:
#          - $ref: "#/components/schemas/allowedValues"
#          - $ref: "#/components/schemas/anyValue"
#          - $ref: "#/components/schemas/valuesReference"
#      defaultValue:
#        type: string
#      dataType:
#        $ref: "#/components/schemas/nameReferenceType"
#      uom:
#        $ref: "#/components/schemas/nameReferenceType"
#
```

It describes an OpenAPI schema that employs `type: string`. 
When running `flake8`, it triggers the error `F821 undefined name 'string'`, although this does not apply. 
It looks like it incorrectly interprets it as a Python 2 `# type: <typing>` definition, an thus cannot figure out the "class" `string`.
It doesn't trigger on `type: object` by luck because `object` is an actual Python keyword. 

I can see that it would hard to distinguish if it is a false positive if the `# type: ...` was defined next to a Python line such as below: 
```python 
a = "1"  # type: string
```
But in my case, the comment is directly at the start of the line and surrounded by more comment lines.

Versions: 
```pip
flake8==3.8.3
pyflakes==2.2.0
```

**Comment by asottile** [comment]
mypy rejects this too and the behaviour is meant to help identify that as early as possible:

```console
$ mypy t.py 
t.py:2: error: invalid syntax
Found 1 error in 1 file (errors prevented further checking)
```

an easy workaround is to triple-quote instead of comment characters

**Comment by fmigneault** [comment]
@asottile  
When I apply triple quotes, I instead get `E302 expected 2 blank lines, found 0` since the string is on top of the class. I don't want to add spaces between it and the class because they should stay together.  I also cannot place it inside the class because docstring values are employed to generate documentation details about that class. 
I guess I could add a `noqa` comment to ignore the `E302`, but adding this workaround to already a workaround of `F821` seems like a bad way to resolve. Also very confusing to have only this "comment" as triple quotes when everywhere else uses this convention for docstrings.

**Comment by asottile** [comment]
yeah you can also `# noqa: F821` those particular lines

**Comment by sigmavirus24** [comment]
> Also very confusing to have only this "comment" as triple quotes when everywhere else uses this convention for docstrings.

It's in the official documentation that a triple quote is a way to "comment" things in a multi-line fashion like other languages have `/* */` to do so. It's perhaps not the most common method to do this, but it works and is suggested by docs.python.org

**Comment by sigmavirus24** [comment]
I think I wasn't clear. The Python docs call this out as the only way to do multiline comments
