### ISSUE TITLE
The next release (2.4.0)

### ISSUE THREAD

**Issue by asottile** [PyCQA/pyflakes#656]
I'm planning to do another release with `match` statement support in the three related projects (pyflakes, pycodestyle, and flake8)

this issue is to track that!

**Comment by asottile** [comment]
#657 for the changelog

basically going to release as soon as someone says that looks ok!

**Comment by sigmavirus24** [comment]
Done@asottile

**Comment by asottile** [comment]
this has been released

**Comment by mitchblank** [comment]
Did it just turn out to be a `pyflakes` release?  The body of this issue mentioned that there would be matching `pycodestyle` and `flake8` releases but I don't see those on PyPi yet
