### ISSUE TITLE
F822 not working?

### ISSUE THREAD

**Issue by Dreamsorcerer** [PyCQA/pyflakes#661]
Not sure if there's something misconfigured, or if pyflakes is just not detecting F822 anymore. Any help would be appreciated.

There is a `Signal` at: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/__init__.py#L184
But, it was removed from the code, so should now cause an F822, but flake8 seems to pass.

This results in runtime errors when doing `from aiohttp import *`: https://github.com/aio-libs/aiohttp/issues/6197

**Comment by asvetlov** [comment]
Interesting. I have no idea

**Comment by asottile** [comment]
unclear why, but seems like this is explicitly turned off for `__init__.py`: https://github.com/PyCQA/pyflakes/blob/78d885910781301663a956456e89d1743e037ac3/pyflakes/checker.py#L1020

**Comment by asottile** [comment]
looks like it's been that way for a decade, I'm down for removing the confusing special case: dd5679736ea780ac74343bde015b13883d7aab83

**Comment by asottile** [comment]
oh actually -- I understand why it is this way (though unfortunate) -- so unfortunately it looks like that'll have to stay

```console
$ tree a
a
├── b.py
└── __init__.py

0 directories, 2 files
$ tail -n999 a/*
==> a/b.py <==

==> a/__init__.py <==
__all__ = ('b',)
$ python3 -c 'from a import *; print(dir())'
['__annotations__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'b']
```

**Comment by Dreamsorcerer** [comment]
Didn't even know you could export a module without importing it like that...
We've just done a `from aiohttp import *` as part of a regression test, so I guess we'll live without it if needed.

**Comment by Dreamsorcerer** [comment]
Although, maybe flake8 could check for names matching modules in an `__init__.py` file? Then the check could still work correctly.

**Comment by asottile** [comment]
pyflakes only operates on the source of the file -- it doesn't know about the filesystem

**Comment by webknjaz** [comment]
> it doesn't know about the filesystem

Even if it did, package namespaces could be constructed out of multiple folders from different places on `$PYTHONPATH` IIRC. Right?
