### ISSUE TITLE
pyflakes complains about my style

### ISSUE THREAD

**Issue by nerdfever** [PyCQA/pyflakes#662]
_"Pyflakes makes a simple promise: it will never complain about style"_

Yet my style is to use f-strings whether there's a placeholder or not. AFAICT this is perfectly valid Python and "must placeholders" is not mentioned in PEP 8.

If back when Python was invented quoted strings had been defined to act the way f-strings do now, nobody would be complaning about missing placeholders today.

Yet pyflakes complains:

`F-string is missing placeholders`

This is a matter of style. Either remove the complaint or retract the promise.

**Comment by asottile** [comment]
it captures a common mistake where placeholders were intended but mistakenly left out.  it's not a matter of style
