### ISSUE TITLE
This throws an error but compiles fine

### ISSUE THREAD

**Issue by u9g** [PyCQA/pyflakes#664]
```py
template_iterate_triplets(inp, outp, lambda nums: [(avg := sum(nums)// 3), avg, avg])
```
(the walrus operator part)

**Comment by asottile** [comment]
please fill out the issue template, it is there for a reason!

**Comment by u9g** [comment]
@asottile There literally isn't a template? I just checked? ![image](https://user-images.githubusercontent.com/43508353/144724331-bc516bee-0783-459c-b091-1cb07d132c8f.png)

**Comment by asottile** [comment]
oh, I thought you were on `flake8`, my bad

almost certainly you're using the wrong python version -- from the [README](https://github.com/PyCQA/pyflakes#installation):

> Be sure to install it for a version of Python which is compatible with your codebase
