### ISSUE TITLE
Check for mutable default args

### ISSUE THREAD

**Issue by dannysepler** [PyCQA/pyflakes#665]
Like mentioned here https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments, default mutable arguments can lead to bugs. They are often-overlooked (even by people who know about them), and should be straightforward to check for

I'm not sure _which_ tool should catch this. It didn't feel appropriate for `pycodestyle`, but also `pyflakes` doesn't feel like a perfect home because it's not necessarily a bug. What do you all think?

**Comment by asottile** [comment]
I believe you're looking for flake8-bugbear: https://github.com/PyCQA/flake8-bugbear#list-of-warnings

it doesn't really fit in pyflakes:

> Pyflakes makes a simple promise: it will never complain about style, and it will try very, very hard to never emit false positives.

**Comment by dannysepler** [comment]
amazing, thanks!
