### ISSUE TITLE
False-positive `imported but unused` with PEP 585

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/pyflakes#670]
```py
from collections.abc import Sequence
from typing import TYPE_CHECKING, Iterator

if TYPE_CHECKING:
    from queue import LifoQueue, Queue, PriorityQueue

Alias1 = Sequence["Queue"]
Alias2 = Iterator["LifoQueue"]

class X(Sequence["PriorityQueue"]):
    ...
```

```
test.py:5:5 'queue.Queue' imported but unused
test.py:5:5 'queue.PriorityQueue' imported but unused
```

_I'm aware that the `TYPE_CHECKING` guard isn't necessary in the example above. It's just for illustrative purposes. Sometimes it's useful to prevent circular imports though._

Pyflakes doesn't recognize that `Queue` is used as string in the subscript for `Sequence`. Looking through the code, it seems that imports from `typing` are special cased. I'm not sure if that is enough anymore. With `__class_getitem__` every class could be subscriptable starting with Python 3.7. At last PEP 585 added it to a bunch of stdlib classes which were previously only imported from typing.

The challenge would be how to prevent false positives `undefined name` then.

https://github.com/PyCQA/pyflakes/blob/dbb18432165bdc567e015511b3f3284f0f14cf05/pyflakes/checker.py#L1559-L1563

**Comment by asottile** [comment]
dupe #571 -- this isn't really solvable since pyflakes cannot tell whether your imported generics are types or not (and therefore if those assignments are type aliases or not)
