### ISSUE TITLE
"imported but unused" for `TypeAlias` with string literal type

### ISSUE THREAD

**Issue by lkadian** [PyCQA/pyflakes#671]
[Explicit Type Aliases](https://www.python.org/dev/peps/pep-0613/) with type specified as a string literal are incorrectly flagged as an unused import:

**foo.py**
```python
import sys
from os import PathLike

if sys.version_info[:2] >= (3, 10):
    from typing import TypeAlias
else:
    from typing_extensions import TypeAlias

PathLikeStr: TypeAlias = "PathLike[str]"
```

```bash
$ pyflakes --version
2.4.0 Python 3.8.6 on Linux
$ pyflakes foo.py
foo.py:2:1 'os.PathLike' imported but unused
```

Types in string literals are correctly detected in other scenarios:

**ok.py**
```python
from os import PathLike

def f(path: "PathLike[str]") -> "PathLike[str]":
    return path
```

```bash
$ pyflakes ok.py
$
```

**Comment by asottile** [comment]
pyflakes likely needs special handling to understand `TypeAlias` -- it would go here: https://github.com/PyCQA/pyflakes/blob/dbb18432165bdc567e015511b3f3284f0f14cf05/pyflakes/checker.py#L2374

would you be interested in contributing towards that?

**Comment by lkadian** [comment]
Yes I'd be interested in contributing! I'll give it a go
