### ISSUE TITLE
If statement masks undefined variable

### ISSUE THREAD

**Issue by igordertigor** [PyCQA/pyflakes#673]
When undefined variables are inside the `else` block of an if statement, they don't get reported. Here are three examples equivalent examples, but for one, pyflakes does not create an error:

First example:
```python
a = 2*a
```
Should fail and it pyflakes detects the error. 

Second example
```python
if True:
    a = 2*a
else:
    a = 4
```
Should fail and it pyflakes detects the error.

Third example
```python
if False:
    a = 4
else:
    a = 2*a
```
Is equally broken code, but pyflakes does not detect the error. It is important to have the `a = 4` assignment here. Otherwise, pyflakes would be able to detect the error.

These examples were tested with a fresh virtual environment using python3.8 and the most recent pyflakes version from pypi:
```bash
$ pyflakes --version
2.4.0 Python 3.8.10 on Linux
```

**Comment by asottile** [comment]
pyflakes does not perform branch analysis (very hard problem) so it roughly sees your code as if there weren't any branches
