### ISSUE TITLE
Internal error on `__all__, = ...`

### ISSUE THREAD

**Issue by decorator-factory** [PyCQA/pyflakes#674]
Steps to reproduce:
1. Install `pyflakes==2.4.0`
2. Create a file with the name of `foo.py`
3. Place the following in the file (the comma after `__all__` is intentional):
```py
__all__, = (
    "fizz",
    "buzz",
)
```
4. Run `pyflakes foo.py`

Outcome:
```
Traceback (most recent call last):
  File "/tmp/foo/venv/bin/pyflakes", line 8, in <module>
    sys.exit(main())
...
  File "/tmp/foo/venv/lib/python3.9/site-packages/pyflakes/checker.py", line 591, in __init__
    if isinstance(source.value, (ast.List, ast.Tuple)):
AttributeError: 'Tuple' object has no attribute 'value'
```

After a bit of investigation, [this method](https://github.com/PyCQA/pyflakes/blob/master/pyflakes/checker.py#L580) assumes that `source` is a `ast.Name`. But in reality it can be `ast.Tuple` or some other more complicated target.

I think the right behaviour is to mark this as invalid to the user.

I'd be happy to work on this issue myself.

**Comment by sigmavirus24** [comment]
Why do you _want_ to use use `__all__, = ...`?

**Comment by decorator-factory** [comment]
I don't want to use it, it was most likely a typo. But I don't think pyflakes should crash on this line
