### ISSUE TITLE
No duplicate keys detected for variable attributes

### ISSUE THREAD

**Issue by frrakn** [PyCQA/pyflakes#677]
Duplicate dict keys will not be detected if they are attributes of a variable.

Popular example is enums. As is, the below code will NOT raise any linter issues.
```
class SomeEnum(Enum):
    FOO: 1

d = {
    SomeEnum.FOO: 1
    SomeEnum.FOO: 2
}
```

**Comment by asottile** [comment]
via https://github.com/PyCQA/pyflakes/pull/678#issuecomment-1030767197
