### ISSUE TITLE
Wrong handling of type hinting with redefinition

### ISSUE THREAD

**Issue by POD666** [PyCQA/pyflakes#680]
Here is a code example that seems to work incorrectly:

```python
if typing.TYPE_CHECKING:
    from ... import MyContext
    from ... import MyTask

def get_context():
    # type: () -> MyContext
    
    # avoid cyclic imports:
    from ... import MyContext  # noqa: F811

    return MyContext()

def get_task():
    # type: () -> MyTask
    
    # avoid cyclic imports:
    from ... import get_task

    return get_task()
```

Running pyflakes returns 
* `from ... import MyContext` imported but unused
* redefinition of unused `MyContext`

So my autoflake8 removes `from ... import MyContext` from the typing.TYPE_CHECKING section.

Does it look like a bug that you would fix? 

As a workaround I have added aliases inside functions, so the error doesn't occur anymore:
```python
def get_context():
    # type: () -> MyContext
    
    # avoid cyclic imports:
    from ... import MyContext as MC

    return MC()
```

**Comment by asottile** [comment]
pyflakes does not do branch analysis so it sees conditional imports as non-conditional -- as such this isn't really fixable without solving or partially-solving an intractable problem (branch analysis is a halting-problem)
