### ISSUE TITLE
Undefined name [F821] error

### ISSUE THREAD

**Issue by robinbowes** [PyCQA/pyflakes#681]
Hi,

I'm getting an "undefined name 'wrapper' [F821]" error with the example code taken from [this comment](https://github.com/tiangolo/typer/issues/296#issuecomment-869005608).

```
$ flake8  main.py
main.py:11:6: F821 undefined name 'wrapper'

$ flake8 --version
4.0.1 (mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython 3.9.1 on Darwin
```

I'll copy/paste the code here for convenience:

```
from typing import Callable

import typer
from merge_args import merge_args

app = typer.Typer()


def from_city(
    func: Callable,
) -> "wrapper":
    @merge_args(func)
    def wrapper(
        ctx: typer.Context,
        city: str = typer.Option(
            ..., "--city", "-c", prompt=True, help="The name of the city to say hi from"
        ),
        state: str = typer.Option(
            "VA", "--state", "-s", help="The state you are saying hi from"
        ),
        **kwargs,
    ):
        """Setup for finding city."""
        return func(
            ctx=ctx,
            **kwargs
        )
      
    return wrapper


@app.command()
@from_city
def hi_city(
    ctx: typer.Context,
    name: str = typer.Option(
        ..., "--name", "-n", prompt=True, help="Name of person to say hi to"
    ),
):
    """Say hello."""
    kwargs = ctx.params
    print(f"Hello, {name}. Welcome from {kwargs['city']}, {kwargs['state']}!")


if __name__ == "__main__":
    app()
```

I've found a few mentions of F821, including https://stackoverflow.com/questions/67547135/why-does-flake8-give-the-warning-f821-undefined-name-match-when-using-match which led me here.

Is this a bug with pyflakes, or is there something wrong with the code?

Thx.

**Comment by asottile** [comment]
this is a problem with your code. your forward reference would not resolve according to pep 484

**Comment by robinbowes** [comment]
Ah, OK. It's not actually my code, but it seems to work OK without the forward reference. Sorry for the noise.

**Comment by sigmavirus24** [comment]
Your return annotation doesn't return a type (the forward reference Anthony was talking about). The type of the inner wrapper function is Callable like your annotation for the decorator's parameter
