### ISSUE TITLE
Unused variable warning is suppressed by `del variable`

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/pyflakes#686]
```python
def f():
    a = 1
    del a  # Delete this line, and pyflakes will complain
```

While `del a` does constitute a reference to the variable, it would be great to have a warning for variables which are deleted without *otherwise* being used.

**Comment by asottile** [comment]
this is intentional -- especially for this common pattern:

```python
import x
del x
```

**Comment by Zac-HD** [comment]
Ah, makes sense 👍
