### ISSUE TITLE
if foo == "a" or "b":

### ISSUE THREAD

**Issue by Akuli** [PyCQA/pyflakes#691]
In my experience, at some point during their learning, every beginner tries to use `or` inside an `if` statement in some way that doesn't work. For some beginners, it happens when the beginner is working on a program that is 5 lines long. For others, it happens when their program is 500 lines long, and at that point it can be harder to notice that an if statement isn't working correctly.

Examples from actual stackoverflow questions:

```python3
if "a" or "á" or "à" or "ã" or "â" in someList:
    ...
if proceed == "y" or "Y":
    ...
if name == ("Jesse" or "jesse"):
    ...
if fields[9] != ('A' or 'D' or 'E' or 'N' or 'R'):
    ...
if job == "mechanic" or "tech":
    ...
if ('a' or 'b') in L:
    ...
if x == "monkey" or "monkeys":
    ...
if first == "a" or "e" or "i" or "o" or "u":
    ...
if (len(x) == (4 or 6)) and x.isdigit():
    ...
if user_input == "look" or "look around":
    ...
if request == "y" or "Y":
    ...
if choice == "yes" or "Yes":
    ...
if not ( userDesc==("Y") or ("H") or ("E")):
    ...
elif taxon == "Kids Earrings" or "Earrings":
    ...
```

Currently none of these are linter errors, but all of them could be detected without false positives. Something like `if choice == foo or bar` shouldn't be an error though, because it can be intentional if `bar` is meant to be treated as a boolean. But if `bar` is an integer or string constant, and not a variable name, then that can't be intentional.

Having this in a linter isn't ideal, because usually beginners haven't heard of linters, and not all of them use an IDE that runs linters in the background. But [it seems like cpython maintainers think that adding this to cpython "complicates the code" too much](https://github.com/python/cpython/issues/92739), and having it checked in the linter would be better than nothing.

**Comment by asottile** [comment]
this seems too specific and too high positive for pyflakes, perhaps a better fit for flake8-bugbear

**Comment by Akuli** [comment]
Looking at flake8-bugbear's readme, it says it's for checks that are "very opinionated and do not have a PEP or standard behind them". There's nothing opinionated about these: all examples I showed above are clearly wrong, there's no way any of them do what you intended them to do.

Why exactly would these checks fit better in flake8-bugbear? Is there a philosophy that isn't written in flake8-bugbear's README? Am I missing something else?

**Comment by Akuli** [comment]
I think I get it now: flake8-bugbear catches programming mistakes in general, regardless of whether or it's opinionated. It warns about `++n`, for example, which looks like incrementing and it's actually `+(+n)`. That's quite similar to `if foo == "a" or "b"`, as that too looks like something else than it is.
