### ISSUE TITLE
Output Formatting is Inconsistent

### ISSUE THREAD

**Issue by utkonos** [PyCQA/pyflakes#692]
There is an inconsistency with formatting of error messages. Some include `:` and some don't. A downstream workaround in SublimeLinter now corrects for this:

https://github.com/SublimeLinter/SublimeLinter-pyflakes/pull/17

I can see from the tests that sometimes the `:` is there:

https://github.com/PyCQA/pyflakes/blob/f3b1b44bf3d2d5927004fa1c2fcf1ab2def816b9/pyflakes/test/test_api.py#L507-L513

And sometimes it is not:

https://github.com/PyCQA/pyflakes/blob/f3b1b44bf3d2d5927004fa1c2fcf1ab2def816b9/pyflakes/test/test_api.py#L541-L546

I also tried to find where in pyflakes that `invalid syntax` message is generated and I couldn't find it. Does that message come from outside this package?

Here is an example:

```
<stdin>:1044:12 undefined name 'settingss'
```

VS

```
<stdin>:34:45: invalid syntax
```

Some more discussion here:
https://github.com/SublimeLinter/SublimeLinter/issues/1847

**Comment by asottile** [comment]
one comes from here: https://github.com/PyCQA/pyflakes/blob/2409df015d9d847890716b242cb418047cd9d6b7/pyflakes/messages.py#L16

the other comes from here: https://github.com/PyCQA/pyflakes/blob/2409df015d9d847890716b242cb418047cd9d6b7/pyflakes/reporter.py#L58-L61

**Comment by asottile** [comment]
fwiw you're probably better to wrap `flake8` than pyflakes (you'll get consistent output then, and options for formatting via `--format` or via formatting plugins (`flake8-json`))
