### ISSUE TITLE
erronious F401 when using `from x import y` to import submodule 

### ISSUE THREAD

**Issue by clsater** [PyCQA/pyflakes#696]
```
$ cat test.py
import a
from a import b
print(a.b.c())

$ touch a/__init__.py
$ cat a/b/__init__.py
def c():
    return 1
$ flake8 test.py
test.py:2:1: F401 'a.b' imported but unused
```
Since `from a import b` loads the `b` submodule, `a.b`, line 2 is necessary and should not be removed.

**Comment by asottile** [comment]
you are depending on **import side-effects** and not the names that are being introduced

your code can be rewritten as `import a.b`

**Comment by asottile** [comment]
it is not possible to be known statically whether `a.b` refers to a module `a.b` or an attribute of `b` of `a`

**Comment by asottile** [comment]
import side-effects are bad and the linter is correct to flag them as problematic

**Comment by clsater** [comment]
Ahh, I thought flake8 could traverse the filesystem and look for `a/b/__init__.py` to determine whether `b` is a submodule or not. If it doesn't check the filesystem for imports, then yeah, it's impossible to know what `b` is. It's a similar issue with `from a.b import *`, which flake8 can't analyze either...
