### ISSUE TITLE
Warn about duplicate slots in subclasses

### ISSUE THREAD

**Issue by ethanhs** [PyCQA/pyflakes#712]
Initially inspired by https://github.com/python/mypy/pull/13028

I was reading the Python language reference and found this:

> If a class defines a slot also defined in a base class, the instance variable defined by the base class slot is inaccessible (except by retrieving its descriptor directly from the base class). This renders the meaning of the program undefined. In the future, a check may be added to prevent this.

It would be great to have a lint to check for this, and I imagine it wouldn't be too hard to implement (famous last words).

**Comment by asottile** [comment]
pyflakes doesn't traverse module boundaries so this would need to be in something like mypy or pylint which does

**Comment by asmeurer** [comment]
You might also be interested in https://github.com/ariebovenberg/slotscheck
