### ISSUE TITLE
Symbol incorrectly considered unused (F401) when symbol name matches instance variable name

### ISSUE THREAD

**Issue by Pyprohly** [PyCQA/pyflakes#713]
When future annotations are enabled, a symbol that is used in an instance variable annotation directly on a class definition and whose name matches the instance variable name is wrongly considered unused (F401).

```python
from __future__ import annotations
from datetime import datetime

class A:
    datetime: datetime
```

**Comment by asottile** [comment]
yet another dupe for #648 !
