### ISSUE TITLE
F401 reports unused import, but the import is used in doctest

### ISSUE THREAD

**Issue by FurcyPin** [PyCQA/pyflakes#718]
### How to reproduce

I create a file like this :

```
import time

def fun():
    """
    >>> t = time.time()

    :return:
    """
    print("Doing Nothing")
```

Then I run flake8 on it, and I get : `F401 'time' imported but unused`.
If I remove the `import time` statement, the doctest breaks.

Of course, I could do the import directly inside the doctest, but we could easily imagine how
annoying this would be with a file with 100 methods with doctests that require 10 imports each.
It would also makes the doctest less readable for the user.

**Comment by asottile** [comment]
I believe the correct approach is to make your doctests standalone -- by putting the imports that are only needed for doctests inside of them

**Comment by FurcyPin** [comment]
Yes, this would work as a workaround.

However, I still believe this should be considered as a bug for the following reasons:

1. Removing the "unused" import would actually break things : so if people are relying on some "autofix" it will break it, which will force the users to not trust the autofix. (I don't know if pyflakes has an autofix feature already, but other linters do)
2. On a file with a lot of methods and a lot of docstring, this might add a lot of import lines where one global import would work
3. As a developper, I would like to have the control about the user's experience when they read the docstring, and in some case I might prefer to not repeat the same obvious import in all my method's docstring examples.
4. This is not consistent with PyCharm's behaviour. Unlike pyflakes, PyCharm's does not consider that this import is unused, and the "optimize import" feature does not remove it.
