### ISSUE TITLE
unused import false positive with future annotations

### ISSUE THREAD

**Issue by Numerlor** [PyCQA/pyflakes#719]
With the annotations future import, a false positive unused import is emitted when the module is used in the annotation of a class local name with the same name as the module - for example
```py
from __future__ import annotations

import module


class Text:
    module: module.member
```
emits `'module' imported but unused`. The false positive disappears if the future import is removed, or the local name is changed to not match the module's

**Comment by sigmavirus24** [comment]
Duplicate #713 #699 #682 #648 and probably #579
