### ISSUE TITLE
FStringMissingPlaceholders

### ISSUE THREAD

**Issue by wxtim** [PyCQA/pyflakes#724]
The following pattern was marked as missing placeholders.

```python
regex = rf"^.{{max_line_len}}" 
```

I'm pretty sure that this is a legit use case, but can't find any test too similar in the test harness.

**Comment by asottile** [comment]
there are indeed no placeholders in that string, if you want literal curly braces you should write:

```python
regex = r"^.{max_line_len}"
```

or if your intent was to have a character repeat with a substituted value (like `^.{50}`) you'd do

```python
regex = rf"^.{{{max_line_len}}}"
```

note that in f-strings `{{` is a literal `{`

good lint rule, it saved you from a bug here :)

**Comment by wxtim** [comment]
@asottile - thank you for responding - esp since it was user error!
