### ISSUE TITLE
How to add additional flake8 config lines? 

### ISSUE THREAD

**Issue by Ubaldo79** [PyCQA/pyflakes#730]
I wish to add `--extend-ignore = F405` **flake8** options but I cannot figure out how.
I created a `.flake8 `file in the root folder of my project with the following content

```
[flake8]
extend-ignore = F405
```

That works with **flake8** but it won't work for **pyflakes**.
 
That is, by running

`pyflakes.exe ./src/mymodule.py`

I get `F405 `warnings, but running  

`flake8.exe ./src/mymodule.py `

I won't get any `F405 `warnings. 

How should I let **pyflakes** to recognize my `.flake8` config file?

**Comment by asottile** [comment]
pyflakes does not have a configuration file, nor does it have ignore nor extend-ignore -- those are all flake8 features
