### ISSUE TITLE
Undefined name with assignment expression (PEP 572)

### ISSUE THREAD

**Issue by char101** [PyCQA/pyflakes#735]
Hi,

This code gives `undefined name` warning although `a` is defined in the scope:

```python
if a := 1 and a > 0:
    pass
```

**Comment by asottile** [comment]
another classic case of "assignment expressions are a hidden foot gun"  -- the linter is correct, your code actually evaluates as `a := (1 and a > 0)` -- add parens to fix

**Comment by char101** [comment]
Thanks, I didn't thought about the operation precedence.

**Comment by asottile** [comment]
if there ever a question it's trivial to just run the code and observe the error!
