### ISSUE TITLE
F821 undefined name when using class pattern matching

### ISSUE THREAD

**Issue by jaycle** [PyCQA/pyflakes#736]
Getting F821 running flake8 across this minimum working example:

```py
from result import Ok, Err

def check(result):
    match result:
        case Ok(v):
            print(v)  # F821 undefined name 'v'
        case _:
            print("error")

check(Ok('test'))
check(Ok(1))
check(Err(0))
```

This is using the package https://github.com/rustedpy/result which seems to correctly implement `__match_args__` per [PEP 566](https://peps.python.org/pep-0622/#class-patterns).

**Comment by asottile** [comment]
can't reproduce: **your issue is missing version information** and I suspect you are using an old version

**Comment by jaycle** [comment]
I apologize. I matched the incorrect project dependency and thought I was on latest from pypi. Moving to latest resolved my issue. Thanks!
