### ISSUE TITLE
False positive for F821 when shadowing dict

### ISSUE THREAD

**Issue by olliemath** [PyCQA/pyflakes#738]
Using dict as a function argument name seems to break pyflakes parsing in unexpected ways. Running flake8 on the following weird snippet gives `ex.py:2:13: F821 undefined name 'foo'`:

```python
def f(dict):
    x: dict["foo"] = 1
    return x
```

Flake8 version:
> 5.0.4 (mccabe: 0.7.0, pycodestyle: 2.9.1, pyflakes: 2.5.0) CPython 3.8.10 on Linux

**Comment by asottile** [comment]
you've got an invalid type annotation which isn't correct according to pep 484. pyflakes is correct to error on this

**Comment by olliemath** [comment]
Ahh, I hadn't realised this is **not** related to shadowing the dict name. The error makes more sense now.

**Comment by olliemath** [comment]
> Note that this PEP still explicitly does NOT prevent other uses of annotations, nor does it require (or forbid) any particular processing of annotations, even when they conform to this specification. 

I think you missed this bit of the PEP though - you can use annotations for whatever you like -  this kind of code is perfectly valid python. If pyflakes *only* accepts usage for PEP484-style type annotations, then I guess that's your choice - I didn't know this was a thing.

**Comment by asottile** [comment]
yes -- pyflakes only allows PEP 484 annotations, otherwise using them to decide whether imported names are used or not is meaningless / impossible
