### ISSUE TITLE
F842 local variable is annotated but never used raised incorrectly for variables inside list comprehension since 3.0

### ISSUE THREAD

**Issue by mick88** [PyCQA/pyflakes#743]
```
$ pyflakes --version
3.0.0 Python 3.10.6 on Windows
```

The following code raises "F842 local variable 'cols' is annotated but never used". The type annotation annotates the cols variable used inside type annotation.
```python
        cols: Series
        return [
            list(cols)
            for key, cols in self.dataframe.iterrows()
        ]
```

 There is no other way to type-annotate variable inside iteration or comprehension as far as I am aware, so I create annotation before .

This issue is new in 3.0 and did not show up for me in 2.5

**Comment by asottile** [comment]
cc @dannysepler 

though I'm not sure this is valid -- a type annotation there probably doesn't do anything helpful does it?

**Comment by asottile** [comment]
yeah I think pyflakes is correct to flag this as that annotation does nothing

```console
$ mypy --strict t.py
Success: no issues found in 1 source file
$ cat t.py
from __future__ import annotations

def f() -> list[str]:
    x: int
    return [x for x in ('1', '2', '3')]
```

**Comment by mick88** [comment]
> The one outside the list isn't actually affecting or describing the one in the comprehension.
It does provide a type hint to PyCharm

It also helps self-documenting code as otherwise type of `cols` is ambiguous to developers reading the code.

**Comment by asottile** [comment]
report a bug to PyCharm then, they're mishandling annotations there by ignoring the separate scopes

**Comment by sigmavirus24** [comment]
> It also helps self-documenting code as otherwise type of cols is ambiguous to developers reading the code.

You completely ignored the alternative I provided you that would annotate the right binding in the right context.

**Comment by mick88** [comment]
Thanks, it looks like my use case is rare. I will disable the check until a more convenient solution surfaces.
