### ISSUE TITLE
Report incorrect assigning of dictionary entries with a colon (`:`)

### ISSUE THREAD

**Issue by dannysepler** [PyCQA/pyflakes#756]
Consider the following code

```python
dct = {
    'a': 1,
}
dct['b']: 2
print(dct)  # {'a': 1}
```

This is actually valid python syntax, because it is typing the `'b'` entry as a `2` type. But we can assume the user meant to assign an element rather than type it (especially if there's no equal on this line).

Maybe this is better for `flake8-bugbear` instead, happy to open an issue there.

**Comment by asottile** [comment]
probably better for bugbear yeah -- this is a (imo) wart of the typing system allow you to annotate any *expression*

probably needs to allow `x: Ann`, and `x.y: Ann` and forbid everything else?  there was some discussion of this on typing-sig at one point but I can't find it

**Comment by asottile** [comment]
linked issue is above ^^ thanks!
