### ISSUE TITLE
Regression false positive F811 redefinition between typing and class attribute

### ISSUE THREAD

**Issue by fmigneault** [PyCQA/pyflakes#757]
I have a definition that looks like the following (exact code here for reference: https://github.com/crim-ca/weaver/blob/master/weaver/formats.py) :

```python
if TYPE_CHECKING:
    from typing import Any, Dict, List, Optional, Tuple, Union

    from weaver.typedefs import JSON

# [...]

class OutputFormat(Constants):
    """
    Renderer output formats for :term:`CLI`, `OpenAPI` and HTTP response content generation.
    """
    JSON = classproperty(fget=lambda self: "json", doc="""
    Representation as :term:`JSON` (object), which can still be manipulated in code.
    """)

# [...]
```  

Using older packages, everything passes validation (as expected).
```
flake8-5.0.4
pycodestyle-2.9.1
pyflakes-2.5.0
```

Using more recent versions: 
```
flake8-6.0.0 
pycodestyle-2.10.0 
pyflakes-3.0.1
```
The following is (incorrectly) flagged:
```shell
Running pep8 code style checks...
./weaver/formats.py:93:5: F811 redefinition of unused 'JSON' from line 24
```

Because the second definition is scoped inside the class, there shouldn't be any redefinition issue.

**Comment by asottile** [comment]
please read the changelog before creating issues -- `# type:` comment support was removed in 3.0.0

**Comment by fmigneault** [comment]
That is not a `# type:` comment. It is simply an annotation imported from another module.

**Comment by fmigneault** [comment]
If I simply copy-paste the `JSON` type definitions instead of doing `from weaver.typedefs import JSON` inside the `weaver.format` file where it is used, the F811 redefinition disappears. 

```
if TYPE_CHECKING:
    Number = Union[int, float]
    ValueType = Union[str, Number, bool]
    AnyValueType = Optional[ValueType]  # avoid naming ambiguity with PyWPS AnyValue
    _JSON: TypeAlias = "JSON"
    _JsonObjectItemAlias: TypeAlias = "_JsonObjectItem"
    _JsonListItemAlias: TypeAlias = "_JsonListItem"
    _JsonObjectItem = Dict[str, Union[AnyValueType, _JSON, _JsonObjectItemAlias, _JsonListItemAlias]]
    _JsonListItem = List[Union[AnyValueType, _JSON, _JsonObjectItem, _JsonListItemAlias]]
    _JsonItem = Union[AnyValueType, _JSON, _JsonObjectItem, _JsonListItem]
    JSON = Union[Dict[str, Union[_JSON, _JsonItem]], List[Union[_JSON, _JsonItem]], AnyValueType]
```

So what is the difference in this case? It is specified exactly the same way.

**Comment by asottile** [comment]
pyflakes does not report unused module _assignments_, only unused imports

**Comment by asottile** [comment]
pyflakes does not do branch analysis

**Comment by fmigneault** [comment]
Ok. Thanks for your support.
