### ISSUE TITLE
Potential FN: Unused variable missed

### ISSUE THREAD

**Issue by woodruffw** [PyCQA/pyflakes#758]
Hi there! First of all, thanks for maintaining `pyflakes` -- I use it via `flake8` on just about every Python project I work on, and it's been a consistently invaluable part of my toolbox 🙂 

I'm one of the maintainers of `pip-audit`, and I'm doing a post-mortem followup on a release bug that we didn't catch with linting: https://github.com/pypa/pip-audit/issues/441

In particular, the code in question looked roughly like this (simplified):

```python
    if vuln_count > 0:
        with _output_io(args.output) as io:
            print(formatter.format(result, fixes), file=io)
    else:
        # other stuff...
        
        if skip_count > 0 or formatter.is_manifest:
            with _output_io(args.output) as io:
                print(formatter.format(result, fixes), file=args.output)
```

whereas it _should_ have been:

```python
    if vuln_count > 0:
        with _output_io(args.output) as io:
            print(formatter.format(result, fixes), file=io)
    else:
        # other stuff...
        
        if skip_count > 0 or formatter.is_manifest:
            with _output_io(args.output) as io:
                print(formatter.format(result, fixes), file=io)
```

(Note the change from `file=args.output` to `file=io` on the last line).

In this case, I would have expected an error like this from `pyflakes` (via `flake8`):

```
pip_audit/_cli.py:542:45: F841 local variable 'io' is assigned to but never used
```

...but no warning is produced.

However, if I change `io` to another name, like `io_2`, a warning *is* produced:

```
pip_audit/_cli.py:542:45: F841 local variable 'io_2' is assigned to but never used
```

My original guess was that this was a shadowing/non-lexical scoping bug, since the two context managers have the same binding (`io`). But they're in different branch structures, so they shouldn't share even a non-lexical scope.

**Comment by asottile** [comment]
dupe #715
