### ISSUE TITLE
Unused import not caught depending on import method

### ISSUE THREAD

**Issue by jsundahl** [PyCQA/pyflakes#762]
#### pyflakes version
`3.0.1 Python 3.11.0 on Linux`

#### setup

these are the files we will be linting:
```
$ cat main.py
import foo.used
import foo.unused

foo.used.something = "something"
```
```
$ cat main_caught.py
from foo import used
from foo import unused

used.something = "something"

```

create the files it imports
```
$ mkdir foo
$ touch foo/unused.py
$ touch foo/used.py
```

#### actual behavior
unused import in main.py is not caught
```
$ pyflakes main.py
```

unused import in main_caught.py is caught
```
$ pyflakes main_caught.py 
main_caught.py:2:1: 'foo.unused' imported but unused
```

#### expected behavior
`foo.unused` should be marked as unused in `main.py`

**Comment by asottile** [comment]
please search the issue tracker for duplicates, there are many and with explanations
