### ISSUE TITLE
F401 (flake8): fails when used in Jinja

### ISSUE THREAD

**Issue by gilboare** [PyCQA/pyflakes#767]
Is there a way to avoid this from failing

```
from airflow.macros import ds_add, ds_format

SNOWSQL_VARIABLES = (
    " --variable start_date={{ macros.ds_add(macros.ds_format(data_interval_start, '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%d'), -1) }} "  # As a best practice, upload an extra day's worth of data with each import. https://support.google.com/google-ads/answer/7014069
    + " --variable end_date={{ macros.ds_format(data_interval_end, '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%d') }} "
    + " --variable airflow_run_id={{ run_id }} "
    + "  --variable query_tag={{ dag.dag_id }} "
)
```

> F401 'airflow.macros.ds_add' imported but unused
> F401 'airflow.macros.ds_format' imported but unused

**Comment by sigmavirus24** [comment]
Is `# noqa: F401` on the import line unacceptable? What fix are you looking for?

**Comment by gilboare** [comment]
These functions are actually used, they are referenced in the Jinja template e.g `{{ macros.ds_format(data_interval_end, '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%d') }}`. I want the rule not to fail in case the function is used in Jinja like in this example.

**Comment by asottile** [comment]
flake8 (1) does not implement any checks so this is not the place to report this and (2) your code is correctly failing linting -- if some other system is magically pulling in globals and substituting them into a string then yeah you've got an unlintable system and you should be seeking something less magical

**Comment by sigmavirus24** [comment]
> These functions are actually used, they are referenced in the Jinja template e.g `{{ macros.ds_format(data_interval_end, '%Y-%m-%dT%H:%M:%S%z', '%Y-%m-%d') }}`. I want the rule not to fail in case the function is used in Jinja like in this example.

They are used by a system that's invisible to pyflakes. Your example has no indication it's using Jinja templates and pyflakes can't just assume folks using curly braces are doing something specific or magical. From the perspective of the abstract syntax tree, there are no call sites for the items you're importing. The strings look like plain strings. There's little to be done in pyflakes

**Comment by gilboare** [comment]
ok thanks for your responses 👍
