### ISSUE TITLE
support partially qualified object access on modules

### ISSUE THREAD

**Issue by sanderr** [PyCQA/pyflakes#769]
Sometimes I find it useful to use partially qualified names to refer to objects in another module. In some cases it is a solid middle ground between just importing the object or deepest submodule without any context, and having to be way too verbose with fully qualified names. I do have to admit that I haven't seen this being used often, so I don't know how common or conventional it is.

An exagerated example to highlight the use case:
```python
import this.is.my.deeply.nested.meaningful_name.common_name
from this.is.my.deeply.nested import meaningful_namespace

print(meaningful_name.common_name.my_object)
# compared to very verbose
print(this.is.my.deeply.nested.meaningful_name.common_name.my_object)
# or use the common name without its context
from this.is.my.deeply.nested.meaningful_name import common_name
print(common_name.my_object)
```

An example you can actually run but that doesn't show the motivation so much (I wouldn't use it myself in this case). I picked it only because it's one of the few cases in CPython's standard library that is sufficiently nested.
```python
import concurrent.futures.thread
from concurrent import futures

print(futures.thread.ThreadPoolExecutor)
```

Invoking `pyflakes` on this results in `main.cf:1:1: 'concurrent.futures.thread' imported but unused`. I would like it to be smart enough to recognize the semi-qualified access.

This is somewhere between a bug report for a false positive and a feature request because I'm not sure how common this approach is and whether you even want to endorse it. Would it be aligned with pyflake's intent to support something like this?

**Comment by asottile** [comment]
please search for duplicates, there are several

**Comment by sanderr** [comment]
I must confess I didn't think to search for closed issues. I did a second search now and found a few with similarities (#429 and #137 for "missing" warnings, #159 and #248 for something close to what I propose here). I also read [this write-up about why you are conservative](https://github.com/asottile/scratch/wiki/Why-doesn't-flake8-mark-this-as-an-unused-import%3F) about this.

So, there seem to be two closely related (perceived) issues, and I don't really follow your rationale for the current behavior for either of them. You say that depending on import side effects is a bad practice, and yet you are conservative in the case where I fully agree with that assessment, but you do raise the error in this case here, for which I now present a clear motivation to allow it. I would personally think it would make sense to do it the other way around.

Therefore I don't think this is a strict duplicate of any of these tickets, as it brings both a clear motivation, and I'll get into a detailed rationale below. I'd be happy to discuss this further if you disagree.

# external import side effects

Let's start with your write-up: I fully agree with your reasoning there. However, I don't follow your conclusion, and I haven't seen you go into more detail in any of the above linked tickets. Could you shed some light on that? The part that isn't clear to me is why would you not raise a warning in that case? Yes, the import is required for the snippet to work as intended, but in other instances imports for the sole purpose of a side effect aren't endorsed either: if I have a module with only `import module_with_a_side_effect`, `pyflakes` does raise the warning. I don't see what makes this scenario different.

# internal import side effects

Now, if we look at my example snippet, this has some similarities with the example in your write-up, but I think that the key difference is that it is explicitly visible in this module: it's an explicit side effect on an object that has a name in this module's namespace. This makes it exactly as predictable as any other import. We could argue about whether it's good practice or not, but regardless of that I think it's a very different case.

# Conclusion
1. In the first example there's a black box which may happen to have a side effect on something that is accessible from this namespace. I don't think this is something `pyflakes` should have to take into account. You could think of all sorts of exotic things that happen in this black box that may affect pretty much anything. Therefore I would think it appropriate if a warning is raised here.
2. In the example I give here, it isn't about any black box behavior, rather an alias is introduced to refer to a namespace. This is basically the equivalent of `meaningful_name = this.is.my.deeply.nested.meaningful_name` but it isn't recognized as such by `pyflakes`. It's a valid and predictable construct, and I believe it could be supported without violating any of the arguments you made on the other threads.

I'd be interested to hear your thoughts on this.

**Comment by sanderr** [comment]
I see that, but neither does making an incomplete argument for a cause mean that the cause is invalid. I'm making an argument that I don't think has been made yet, and I'm just trying to spark a healthy discussion about something that I think could be improved upon. I might be willing to further contribute to this, but that requires getting a concensus first. If that concensus is that the current behavior is the desired behavior, that's fair, but I don't feel like this should just be disregarded out of hand just because someone else already reported it at some point but didn't follow through with the rationale.
I acknowledge that this is your domain and that you've been thinking about this for way longer than I have, but that doesn't mean that I can't have a valid point about a decision that has been made in the past. Have you read my post above? What do you think about it? If you still disagree, could you enlighten me as to why?

**Comment by asottile** [comment]
you're not making a new argument -- your case is dependent on import side-effects which pyflakes is correct to say you shouldn't do

**Comment by sanderr** [comment]
Then you don't agree there's a big practical difference between what I call the internal and the external side effects? One being a black box and the other being nothing more than a predictable alias

Apart from that, if that is your stance, wouldn't you agree there's an inconsistency in allowing it in some cases and not in others?

Those are two arguments I haven't seen before, that's what I feel is the core of my message here.

Finally I wonder why you say pyflakes "is correct" to do so. Do you have a reference on that? I'm not trying to provoke you, I'm genuinly curious because I searched for it but didn't find anything. Is this just your viewpoint or is there a broader agreement on this?

**Comment by asottile** [comment]
I mean you're willing to get a second opinion -- @sigmavirus24 is the main other active maintainer

**Comment by asottile** [comment]
> sound and conplete rationale
import side-effects bad

**Comment by sanderr** [comment]
But I'm missing the why. I don't see it as black and white as you seem to do, I think there are two cases that differ widely, so I'm wondering why you don't. I accept I may be wrong, but in my experience insight comes from discussion and explaining the why. I might come to see it your wya or you might come to see it mine. Perhaps neither of those but at least we can understand where the other is coming from. I'm not getting that from a partially motivated statement repeated in response to any argument I make.

**Comment by asottile** [comment]
I'm being brief because these things are already stated in the several duplicates.  you're wasting a lot of your time and some of my time by continuing this.  action at a distance is bad, even if it's cute and saves you a little bit of typing -- there are better alternatives that don't involve abusing imports for side-effects.

**Comment by sanderr** [comment]
Then could you point me to where these things are stated? I didn't find any discussion that touches on the arguments I bring up here so as far as I can see adjacent things have been discussed (and even there I didn't find any reasoning other than your write-up), but not this specifically.

It's not about saving typing, it's about clarity, and I wouldn't call the aliasing approach an abuse of the import system, and there is no action at a distance involved at all. If anything it is very much an OO style. For the other class of import side effects I couldn't agree with you more, but for this one I just don't see how what you're saying applies.
