### ISSUE TITLE
F831: duplicate argument '_' in function definition

### ISSUE THREAD

**Issue by gdlx** [PyCQA/pyflakes#784]
F831 is raised when having multiple "_" arguments but I think it should not.

Here's my example of a callback where I receive arguments that I don't use, but F831 consider them as duplicates:
![image](https://github.com/PyCQA/pyflakes/assets/1533042/c9280c87-f63d-49de-b9b5-669531b50923)

**Comment by asottile** [comment]
it absolutely should, it's a syntax error

**Comment by gdlx** [comment]
Yeah, just noted that, sorry 😖
Maybe it should be a python change but I won't go that way 😅
Thanks !
