### ISSUE TITLE
FString check does not handle concatenated strings correctly

### ISSUE THREAD

**Issue by florath** [PyCQA/pyflakes#785]
pyflakes does not handle concatenated strings correctly.

Example:

    print(f"This is the output of something: "
          "{something}")

outputs:

    fstring.py:1:7: f-string is missing placeholders

Version: 3.0.1 Python 3.10.12 on Linux

**Comment by sigmavirus24** [comment]
No I believe your code is wrong. The second string in your concatenation will not be interpolated. You need to prefix the second string with an f

**Comment by florath** [comment]
You are right!
Sorry for the wrong report.
