### ISSUE TITLE
Errors should be generated for "illegal" accesses to module-level variables with leading double underscores

### ISSUE THREAD

**Issue by jack-joindeed** [PyCQA/pyflakes#788]
This file passes with pyflakes 3.1.0

```python
__MY_PROP = 123

class Test:
    @property
    def prop(self) -> int:
        return __MY_PROP


def main() -> None:
    test = Test()
    print(test.prop)


if __name__ == '__main__':
    main()
```

But we get a runtime traceback on python 3.12 (and some earlier versions):

```
Traceback (most recent call last):
  File "/private/tmp/wat.py", line 16, in <module>
    main()
  File "/private/tmp/wat.py", line 12, in main
    print(test.prop)
          ^^^^^^^^^
  File "/private/tmp/wat.py", line 7, in prop
    return __MY_PROP
           ^^^^^^^^^
NameError: name '_Test__MY_PROP' is not defined
```

Changing `__MY_PROP` to having a single leading underscore cause the error to go away.

This is probably extendable to other areas where private variables are accessed like `MyClass().__foo()`, but I'm just reporting the single case I know I'd like to see a lint for.

**Comment by asottile** [comment]
dupe #267 please search next time

**Comment by jack-joindeed** [comment]
Beggin' ye pardon, mi'lord, fer not finding some other issue that doesn't have the keywords I was looking for. I shall appropriate flog meself.
