### ISSUE TITLE
F811 redefinition of unused '_' - should underscore be excluded?

### ISSUE THREAD

**Issue by r-downing** [PyCQA/pyflakes#795]
Contrived example: say you wanted to import something but not have it be in the namespace. Maybe the importing has side-effects, or you're loading a pytest plugin, etc... 

If you were to `import X as _` and then reassign `_` elsewhere, this triggers the error `test.py:3:4: F811 redefinition of unused '_' from line 1` 

```python
from sys import path as _

a, _ = (1, 2)
```

Should `_` or things starting with `_` be excluded form this check, since `_` is kind of meant to be unused / throwaway-assignment, etc?

**Comment by asottile** [comment]
loading a pytest plugin should be done with the `pytest_plugins` module list, not import side effects

import side effects are not a good idea in general and so pyflakes is correct to flag suspicious code such as the contrived example
