### ISSUE TITLE
Spurious F811 when a method in a class overrides an "unused import"

### ISSUE THREAD

**Issue by ztane** [PyCQA/pyflakes#796]
With complaints about `copy` being unused disabled from flake8, this code oddly thinks a method definition inside a class overrides the unused import! pyflakes 3.1.0. If for example I add `print(copy)` then no diagnostics are produced...

```
import copy


class Foo:
    def copy(self):
        return 42
```

**Comment by asottile** [comment]
dupe #445 please search next time
