### ISSUE TITLE
Docu: What does pyflake checks for?

### ISSUE THREAD

**Issue by buhtz** [PyCQA/pyflakes#798]
I can not find in your docu what "errors" do pyflakes checks for?

It seems to me like a "minimal linter" because it do not check for PEP8 by design. So what else is there to check for? I am seriously asking.

**Comment by jack-mcivor** [comment]
Flake8 maintains a list of checks pyflakes does here https://flake8.pycqa.org/en/latest/user/error-codes.html

**Comment by buhtz** [comment]
The list is about flake8 not pyflakes. To my understanding pyflakes is just a minor part of flake8. Flake8 do cover much more then pyflakes does.
And the link is about a foreign project. The info is still missing in your project. It is unclear for new users what your linter do check for.

i would keep the issue open.
