### ISSUE TITLE
False Positive: walrus in a list comprehension

### ISSUE THREAD

**Issue by bradezard131** [PyCQA/pyflakes#800]
Minimal reproduction:

```python
def foo(x):
    fns = [lambda x: x + 1, lambda x: x + 2, lambda x: x + 3]
    return [(x := fn(x)) for fn in fns]
```

This raises F841 incorrectly asserting that the `x` variable assigned in the comprehension is never used

**Comment by asottile** [comment]
what version are you using?

**Comment by bradezard131** [comment]
`pyflakes==3.2.0` which afaict is the latest?

**Comment by sigmavirus24** [comment]
What version of python are you running on?

**Comment by bradezard131** [comment]
Python 3.10.12

**Comment by asottile** [comment]
please try out #801

**Comment by bradezard131** [comment]
Yep that fixes it for me
