### ISSUE TITLE
False positive F841 and F821

### ISSUE THREAD

**Issue by gml16** [PyCQA/pyflakes#806]
Hello, I believe this is a false positive of errors  F841 and F821:
```
try:
    assert False, "assert false"
except Exception as e:  # triggers F841
    def fn():
        print("error", e)  # triggers F821
    fn()
```

Running `flake8` on this small file gives the following errors:
- F841 local variable 'e' is assigned to but never used
- F821 undefined name 'e'

Unless I'm missing something, `e` is well defined here as it is within the `expect` scope.

`flake8==7.0.0 pyflakes==3.2.0`

**Comment by asottile** [comment]
please search for duplicates next time

**Comment by gml16** [comment]
Thank you for your quick response. I must admit I did search for duplicates and am unsure which issue you are referring to. Maybe you mean #800 ? In any case, does this mean this should not happen anymore in the next release? Thanks for your help

**Comment by gml16** [comment]
It sounds like you are frustrated with people not searching through duplicates. I understand that. 

I've looked up issues up until 2017 and you may be referring to this one: #265. If that is the case, you'll notice that Python3 does run the example code successfully:
```
try:
    assert False, "assert false"
except Exception as e:  # triggers F841
    def fn():
        print("error", e)  # triggers F821
    fn()                                                                                                                                                             
>>> error assert false
```

**Comment by gml16** [comment]
Given the resolution in the other issues mentioned by #265, I understand that support for this is not planned as this pattern is deemed unsafe. Thanks for your help
