### ISSUE TITLE
 import * 误报的问题  The issue of import * false positives

### ISSUE THREAD

**Issue by lsm1103** [PyCQA/pyflakes#810]
会对 import * 的情况进行误报。如果是因为静态无法知晓 * 里面是否包含具体逻辑代码里面使用的类、函数、变量，是否可以动态加载该导入库去检查（当然这好像不是静态检查的范畴）
`
from manim import *
class PlotFunctions(Scene):
    def construct(self):
        axes = Axes(
            x_range=[-3, 3, 1],
            y_range=[-5, 5, 1],
            x_length=6,
            y_length=6,
            axis_config={
                "numbers_to_include": np.arange(-3, 4, 1),
                "decimal_number_config": {"num_decimal_places": 2},
            },
            tips=True,
        )
        labels = axes.get_axis_labels(x_label="x", y_label="y")
        # Define the function
        func = lambda x: x**2
        # Create graph
        graph = axes.get_graph(
            func, color=YELLOW, x_range=[-3, 3, 0.1]
        )
        # Create graph label
        graph_label = axes.get_graph_label(
            graph, 
            x_val=2,
            direction=UP,
            color=RED,
            label="y=x^2"
        )
        self.play(Create(axes), Write(labels))
        self.play(Create(graph), Write(graph_label), run_time=3)
        self.wait(1)
`

output
`
Python 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.22.2 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.22.2
example.py:1:1: 'from manim import *' used; unable to detect undefined names
example.py:3:21: 'Scene' may be undefined, or defined from star imports: manim
example.py:5:16: 'Axes' may be undefined, or defined from star imports: manim
example.py:11:39: 'np' may be undefined, or defined from star imports: manim
example.py:24:25: 'YELLOW' may be undefined, or defined from star imports: manim
example.py:31:23: 'UP' may be undefined, or defined from star imports: manim
example.py:32:19: 'RED' may be undefined, or defined from star imports: manim
example.py:36:19: 'Create' may be undefined, or defined from star imports: manim
example.py:36:33: 'Write' may be undefined, or defined from star imports: manim
example.py:37:19: 'Create' may be undefined, or defined from star imports: manim
example.py:37:34: 'Write' may be undefined, or defined from star imports: manim
Out[1]: False
`

这是我在源码里面找到的，是否可以解决这个问题？该怎么使用
![image](https://github.com/PyCQA/pyflakes/assets/37491314/2ee3af5f-322e-4091-ad3e-4b11bddafe67)

**Comment by asottile** [comment]
this is working as intended
