### ISSUE TITLE
Remove Python 2.x code?

### ISSUE THREAD

**Issue by edreamleo** [PyCQA/pyflakes#813]
The latest readme says "[pyflakes] supports all active versions of Python: 3.8+".

Yet `checker.py` contains the following `counter` function:
```python
def counter(items):
    """
    Simplest required implementation of collections.Counter. Required as 2.6
    does not have Counter in collections.
    """
    results = {}
    for item in items:
        results[item] = results.get(item, 0) + 1
    return results
```
Why is this function necessary?

**Comment by asottile** [comment]
it still works and nobody has bothered to remove it
